#!/usr/bin/env python3
# [SONNET-4.6] sq-lhcot.2 (issue #2789) — generator for the DRAFT external-key `.spqv`
# interoperability-profile conformance corpus (KERN boundary #1746).
#
# WHY A SEPARATE PYTHON ENCODER, AND NOT `cargo test -- --bless`
# -------------------------------------------------------------
# The point of these fixtures is CROSS-REPOSITORY agreement: Kern/PSS and sparq must emit the
# same bytes for the same logical table. A corpus generated by the Rust encoder and then checked
# by the Rust parser proves only that one implementation is self-consistent — it cannot catch a
# spec ambiguity, because both sides share the same reading of it. This script is therefore a
# SECOND, INDEPENDENT implementation of the version-0 block writer, written from the profile
# document (`research/spqv-external-key-profile.md`) rather than from `src/external_key.rs`.
# `tests/external_key_profile.rs` re-encodes every accepted fixture and asserts the bytes are
# IDENTICAL to what this script wrote, so a disagreement between the two encoders is a red test.
#
# The corpus is stdlib-only, deterministic, and byte-stable: re-running this script on any machine
# must reproduce the committed files exactly. It computes NO digests — every "key" below is a fixed
# opaque byte pattern, because sparq neither defines nor derives external keys.
#
#   usage:  python3 crates/sparq-vectors/tests/fixtures/external-key/generate.py
#
# Rebuild the corpus only to ADD a case or to follow a profile change; changing an existing
# fixture's bytes is a format change and needs the same review as one.

import os
import struct

HERE = os.path.dirname(os.path.abspath(__file__))

MAGIC = b"SPQVXKEY"
DRAFT_VERSION = 0
SHA2_256 = 0x12  # multicodec code, used purely as a realistic opaque value
SHA2_512 = 0x13
MAX_KEY_LEN = 64
MAX_SIG_LEN = 64 * 1024

# Rows appended as (fixture, expect, entries, hash_code, key_len, detail).
MANIFEST = []


def key(seed, length=32):
    """A fixed opaque byte pattern standing in for a producer-supplied digest.

    Deliberately NOT a hash of anything: this profile treats external keys as opaque, and a
    fixture that computed one would imply sparq owns a key-derivation scheme. It does not.
    """
    return bytes(((i * 7 + seed) & 0xFF) for i in range(length))


def blob(b):
    return struct.pack("<I", len(b)) + b


def provenance(model_id, model_version, content_version, verbalization, metric=0, norm=1,
               reserved=b""):
    """`EmbeddingProvenance::to_bytes` (block version 1) — see src/spqv_provenance.rs."""
    return (
        struct.pack("<H", 1)
        + bytes([metric, norm])
        + blob(model_id.encode())
        + blob(model_version.encode())
        + blob(content_version.encode())
        + blob(verbalization.encode())
        + blob(reserved)
    )


def block(hash_code, key_len, entries, prov=b"", signature=b"", version=DRAFT_VERSION, flags=0,
          count=None):
    """The version-0 block. `count` overrides the declared entry count (for malformed fixtures)."""
    ordered = sorted(entries, key=lambda e: e[0])
    declared = len(ordered) if count is None else count
    out = bytearray()
    out += MAGIC
    out += struct.pack("<HHIIQI", version, flags, hash_code, key_len, declared, len(prov))
    out += prov
    for digest, slot in ordered:
        out += digest
        out += struct.pack("<I", slot)
    out += struct.pack("<I", len(signature))
    out += signature
    return bytes(out)


def emit(name, data, expect, entries="-", hash_code="-", key_len="-", detail=""):
    with open(os.path.join(HERE, name), "wb") as fh:
        fh.write(data)
    MANIFEST.append((name, expect, str(entries), str(hash_code), str(key_len), detail))


def accept(name, data, entries, hash_code, key_len, detail):
    emit(name, data, "accept", entries, hash_code, key_len, detail)


def reject(name, data, err_substring):
    emit(name, data, "reject", detail=err_substring)


# --------------------------------------------------------------------------------------------
# POSITIVE fixtures — every one must parse, and re-encoding it must reproduce these exact bytes.
# --------------------------------------------------------------------------------------------

accept(
    "pos-empty.bin",
    block(SHA2_256, 32, []),
    0, hex(SHA2_256), 32,
    "an empty table is well-formed: a producer with no external keys yet still declares its "
    "(code, length) profile",
)

accept(
    "pos-three-keys.bin",
    block(SHA2_256, 32, [(key(1), 0), (key(2), 1), (key(3), 2)]),
    3, hex(SHA2_256), 32,
    "the canonical shape: three 32-byte keys in ascending digest order",
)

accept(
    "pos-provenance.bin",
    block(
        SHA2_256, 32, [(key(1), 0), (key(2), 1)],
        prov=provenance("text-embedding-3-small", "2024-01", "verb-v2", "entity-verbalized"),
    ),
    2, hex(SHA2_256), 32,
    "an external key is generation-independent but NOT embedding-space-independent, so the table "
    "binds the embedding provenance",
)

accept(
    "pos-signature.bin",
    block(SHA2_256, 32, [(key(5), 7)], signature=bytes([0xDE, 0xAD, 0xBE, 0xEF])),
    1, hex(SHA2_256), 32,
    "the signature area round-trips as OPAQUE bytes; no implementation verifies it under the "
    "draft profile, and its presence asserts nothing",
)

accept(
    "pos-sha2-512-keys.bin",
    block(SHA2_512, 64, [(key(1, 64), 0), (key(2, 64), 1)]),
    2, hex(SHA2_512), 64,
    "a 64-byte digest at the length cap — the entry width is derived from the header, never "
    "assumed to be 32",
)

# --------------------------------------------------------------------------------------------
# NEGATIVE fixtures — every one must be REJECTED, with an error mentioning the recorded substring.
# --------------------------------------------------------------------------------------------

reject("neg-truncated-header.bin", block(SHA2_256, 32, [])[:16], "truncated")

reject("neg-bad-magic.bin", b"XPQVXKEY" + block(SHA2_256, 32, [])[8:], "magic")

reject(
    # A file written against the FROZEN profile. It must fail LOUDLY here rather than be
    # re-interpreted under draft rules — that is what makes version 0 safe to ship.
    "neg-frozen-profile-version.bin",
    block(SHA2_256, 32, [(key(1), 0)], version=1),
    "version",
)

reject("neg-nonzero-flags.bin", block(SHA2_256, 32, [(key(1), 0)], flags=1), "reserved")

reject("neg-zero-key-len.bin", block(SHA2_256, 0, []), "must not be 0")

reject(
    "neg-oversized-key-len.bin",
    block(SHA2_256, MAX_KEY_LEN + 1, []),
    "cap",
)

# Entries in descending order: legal bytes, illegal ordering.
_desc = bytearray(block(SHA2_256, 32, [(key(1), 0), (key(2), 1)]))
_desc[32:68], _desc[68:104] = _desc[68:104], _desc[32:68]
reject("neg-unsorted-entries.bin", bytes(_desc), "strictly ascending")

# The same key twice — one key must resolve to exactly one slot.
_dup = bytearray(block(SHA2_256, 32, [(key(1), 0), (key(2), 1)]))
_dup[68:100] = _dup[32:64]
reject("neg-duplicate-key.bin", bytes(_dup), "strictly ascending")

reject(
    # Declares three entries, carries two: the parser must bound the section against the buffer
    # instead of trusting the count.
    "neg-truncated-entries.bin",
    block(SHA2_256, 32, [(key(1), 0), (key(2), 1)], count=3),
    "truncated",
)

reject(
    # count = u64::MAX must be an error, not an allocation attempt.
    "neg-absurd-entry-count.bin",
    block(SHA2_256, 32, [(key(1), 0)], count=0xFFFFFFFFFFFFFFFF),
    "overruns",
)

reject("neg-trailing-bytes.bin", block(SHA2_256, 32, [(key(1), 0)]) + b"\x00", "trailing")

# An unknown metric tag inside the bound provenance block (tag 200 is not a defined metric).
_prov = bytearray(provenance("m", "", "", ""))
_prov[2] = 200
reject(
    "neg-corrupt-provenance.bin",
    block(SHA2_256, 32, [(key(1), 0)], prov=bytes(_prov)),
    "provenance block does not parse",
)

# A signature length above the cap, declared with no bytes behind it.
_sig = bytearray(block(SHA2_256, 32, [(key(1), 0)]))
_sig[-4:] = struct.pack("<I", MAX_SIG_LEN + 1)
reject("neg-oversized-signature-len.bin", bytes(_sig), "cap")


with open(os.path.join(HERE, "MANIFEST.tsv"), "w", encoding="utf-8") as fh:
    fh.write(
        "# [SONNET-4.6] sq-lhcot.2 (#2789) DRAFT external-key .spqv profile conformance corpus.\n"
        "# Profile: research/spqv-external-key-profile.md. Regenerate: generate.py (see its header).\n"
        "# An `accept` row's detail column is prose; a `reject` row's is a REQUIRED error substring:\n"
        "# a conforming parser must refuse the fixture AND say why. Columns are tab-separated;\n"
        "# `-` means not-applicable. Cross-repository consumers read this file, not the .rs test.\n"
        "#\n"
        "fixture\texpect\tentries\thash_code\tkey_len\tdetail\n"
    )
    for row in MANIFEST:
        fh.write("\t".join(row) + "\n")

print("wrote {} fixtures + MANIFEST.tsv".format(len(MANIFEST)))
