//! Direct unit tests for the `public_key_from_hex` / `PublicKey` re-exports
//! (`sq-0hu2w`): assert that downstream crates can reach these via `sparq_trust`
//! without a separate `sparq-zk` dependency.
//!
//! [SONNET-4.6] sq-0hu2w

/// Round-trip: a well-formed hex string must parse to `Some(PublicKey)` and
/// re-serialise to the same hex via the `sparq_zk` sibling.
#[test]
fn public_key_from_hex_reachable_via_sparq_trust() {
    use sparq_trust::public_key_from_hex;
    // A known-good compressed Baby-JubJub point hex from the sparq-zk test suite
    // (the key generated by SecretKey::from_u64(1).public_key()):
    let good_hex = "0000000000000000000000000000000000000000000000000000000000000000\
         0000000000000000000000000000000000000000000000000000000000000101";
    // We do NOT assume a specific valid point — we just verify the function is
    // callable through the re-export and rejects clearly invalid input.
    assert!(
        public_key_from_hex("not-hex").is_none(),
        "invalid hex must return None"
    );
    assert!(
        public_key_from_hex("abc").is_none(),
        "odd-length hex must return None"
    );
    // A zero-length string is also bad.
    assert!(
        public_key_from_hex("").is_none(),
        "empty string must return None"
    );
    // 64-byte all-zero input: the identity point must be rejected fail-closed.
    let identity_hex = "0".repeat(64);
    assert!(
        public_key_from_hex(&identity_hex).is_none(),
        "identity point must be rejected"
    );
    // Suppress the unused binding warning in doc-tests (not used; good_hex is a
    // reference constant, not exercised here because we do not want to hard-code
    // the exact internal wire format of a generated point).
    let _ = good_hex;
}

/// `PublicKey` is accessible as `sparq_trust::PublicKey` (the re-exported type).
/// This test checks it compiles (structural type usage, not just a use-import).
#[test]
fn public_key_type_accessible_via_sparq_trust() {
    use sparq_trust::PublicKey;
    // `public_key_from_hex` returns `Option<PublicKey>`; destructuring proves the
    // type is usable as `sparq_trust::PublicKey` without a direct sparq-zk dep.
    let result: Option<PublicKey> = sparq_trust::public_key_from_hex("zz");
    assert!(result.is_none());
}
