// [GPT-5.6] sq-hggpo: property tests for derivation PROV-O structure.

use std::collections::HashSet;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use oxrdf::{NamedNode, NamedOrBlankNode, Term, Triple};
use proptest::prelude::*;
use sparq_core::Graph;
use sparq_engine::QueryBudget;
use sparq_prov::{
    derive_construct, derive_construct_with_budget, derive_update, derive_update_with_budget,
    ProvConfig,
};

const PROV: &str = "http://www.w3.org/ns/prov#";
const RDF_TYPE: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";

fn fixed_clock() -> SystemTime {
    UNIX_EPOCH + Duration::from_secs(1_700_000_000)
}

fn config(inputs: &[u8]) -> ProvConfig {
    ProvConfig {
        activity: Some(NamedNode::new_unchecked("http://example.test/activity")),
        entity: Some(NamedNode::new_unchecked("http://example.test/output")),
        used: inputs
            .iter()
            .map(|id| NamedNode::new_unchecked(format!("http://example.test/input/{id}")))
            .collect(),
        agent: None,
        clock: fixed_clock,
    }
}

fn input_graph(ids: &[u8]) -> Graph {
    let triples = ids
        .iter()
        .map(|id| {
            format!(
                "<http://example.test/s/{id}> <http://example.test/p> <http://example.test/o/{id}> ."
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    Graph::load_str(&triples, "ntriples").expect("generated input is valid N-Triples")
}

fn triple_key(triple: &Triple) -> String {
    format!("{} {} {}", triple.subject, triple.predicate, triple.object)
}

fn assert_round_trip(expected: &[Triple], serialized: &str) {
    let parsed = Graph::load_str(serialized, "ntriples")
        .expect("serialized provenance must parse through sparq-core");
    let actual: HashSet<String> = parsed
        .iter_ids()
        .map(|ids| {
            format!(
                "{} {} {}",
                parsed.dict.term(ids[0]),
                parsed.dict.term(ids[1]),
                parsed.dict.term(ids[2])
            )
        })
        .collect();
    let expected: HashSet<String> = expected.iter().map(triple_key).collect();
    assert_eq!(actual, expected, "serialization changed the PROV graph");
}

fn has_edge(graph: &[Triple], subject: &NamedNode, predicate: &str, object: &NamedNode) -> bool {
    graph.iter().any(|triple| {
        triple.subject == NamedOrBlankNode::NamedNode(subject.clone())
            && triple.predicate.as_str() == predicate
            && triple.object == Term::NamedNode(object.clone())
    })
}

fn distinct(mut values: Vec<u8>) -> Vec<u8> {
    values.sort_unstable();
    values.dedup();
    values
}

// [GPT-5.6] sq-ddy14: check generation multiplicity on the raw triple vector so a
// duplicate emission cannot be hidden by RDF graph/set normalization.
fn assert_entity_generation_invariant(graph: &[Triple]) -> Result<(), String> {
    let entity_type = Term::NamedNode(NamedNode::new_unchecked(format!("{PROV}Entity")));
    let activity_type = Term::NamedNode(NamedNode::new_unchecked(format!("{PROV}Activity")));
    let entities: HashSet<NamedOrBlankNode> = graph
        .iter()
        .filter(|triple| triple.predicate.as_str() == RDF_TYPE && triple.object == entity_type)
        .map(|triple| triple.subject.clone())
        .collect();

    for entity in entities {
        let generating_activities: Vec<&Term> = graph
            .iter()
            .filter(|triple| {
                triple.subject == entity
                    && triple.predicate.as_str() == format!("{PROV}wasGeneratedBy")
            })
            .map(|triple| &triple.object)
            .collect();
        if generating_activities.len() != 1 {
            return Err(format!(
                "{entity} must have exactly one prov:wasGeneratedBy edge, found {}",
                generating_activities.len()
            ));
        }

        let activity = match generating_activities[0] {
            Term::NamedNode(activity) => NamedOrBlankNode::NamedNode(activity.clone()),
            Term::BlankNode(activity) => NamedOrBlankNode::BlankNode(activity.clone()),
            Term::Triple(_) => unreachable!("RDF-star terms cannot name a PROV activity"),
            other => {
                return Err(format!(
                    "{entity} was generated by non-resource object {other}"
                ));
            }
        };
        if !graph.iter().any(|triple| {
            triple.subject == activity
                && triple.predicate.as_str() == RDF_TYPE
                && triple.object == activity_type
        }) {
            return Err(format!(
                "generating node {activity} must be typed prov:Activity"
            ));
        }

        let started = single_timestamp(graph, &activity, "startedAtTime")?;
        let ended = single_timestamp(graph, &activity, "endedAtTime")?;
        if started > ended {
            return Err(format!(
                "activity {activity} starts after it ends: {started} > {ended}"
            ));
        }
    }
    Ok(())
}

fn single_timestamp<'a>(
    graph: &'a [Triple],
    activity: &NamedOrBlankNode,
    local_name: &str,
) -> Result<&'a str, String> {
    let predicate = format!("{PROV}{local_name}");
    let values: Vec<&str> = graph
        .iter()
        .filter(|triple| triple.subject == *activity && triple.predicate.as_str() == predicate)
        .filter_map(|triple| match &triple.object {
            Term::Literal(value) => Some(value.value()),
            _ => None,
        })
        .collect();
    if values.len() != 1 {
        return Err(format!(
            "activity {activity} must have exactly one prov:{local_name} literal, found {}",
            values.len()
        ));
    }
    Ok(values[0])
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(256))]

    #[test]
    fn construct_provenance_is_structurally_complete(
        source_ids in prop::collection::vec(0_u8..24, 0..12),
        input_ids in prop::collection::vec(0_u8..24, 0..12),
        budgeted in any::<bool>(),
    ) {
        let source_ids = distinct(source_ids);
        let input_ids = distinct(input_ids);
        let graph = input_graph(&source_ids);
        let query = "CONSTRUCT { ?s <http://example.test/outputPredicate> ?o } WHERE { ?s <http://example.test/p> ?o }";
        let derivation = if budgeted {
            derive_construct_with_budget(&graph, query, config(&input_ids), &QueryBudget::unlimited())
        } else {
            derive_construct(&graph, query, config(&input_ids))
        }.expect("generated CONSTRUCT must execute");

        prop_assert_eq!(derivation.triples().len(), source_ids.len());
        let provenance = derivation.prov_graph();
        let used_predicate = format!("{PROV}used");
        let generated_predicate = format!("{PROV}wasGeneratedBy");
        for id in &input_ids {
            let input = NamedNode::new_unchecked(format!("http://example.test/input/{id}"));
            prop_assert!(has_edge(&provenance, derivation.activity(), &used_predicate, &input));
        }
        prop_assert!(has_edge(
            &provenance,
            derivation.entity(),
            &generated_predicate,
            derivation.activity(),
        ));
        prop_assert_eq!(assert_entity_generation_invariant(&provenance), Ok(()));
        let (started, ended) = derivation.timing();
        prop_assert!(started <= ended);
        assert_round_trip(&provenance, &derivation.prov_ntriples());
    }

    #[test]
    fn update_provenance_is_structurally_complete(
        output_ids in prop::collection::vec(0_u8..24, 0..12),
        input_ids in prop::collection::vec(0_u8..24, 0..12),
        budgeted in any::<bool>(),
    ) {
        let output_ids = distinct(output_ids);
        let input_ids = distinct(input_ids);
        let mut graph = Graph::load_str("", "ntriples").expect("empty graph is valid");
        let body = output_ids.iter().map(|id| {
            format!("<http://example.test/s/{id}> <http://example.test/p> <http://example.test/o/{id}> .")
        }).collect::<Vec<_>>().join(" ");
        let update = format!("INSERT DATA {{ {body} }}");
        let derivation = if budgeted {
            derive_update_with_budget(&mut graph, &update, config(&input_ids), &QueryBudget::unlimited())
        } else {
            derive_update(&mut graph, &update, config(&input_ids))
        }.expect("generated INSERT DATA must execute");

        prop_assert_eq!(derivation.inserted().len(), output_ids.len());
        let provenance = derivation.prov_graph();
        let used_predicate = format!("{PROV}used");
        let generated_predicate = format!("{PROV}wasGeneratedBy");
        for id in &input_ids {
            let input = NamedNode::new_unchecked(format!("http://example.test/input/{id}"));
            prop_assert!(has_edge(&provenance, derivation.activity(), &used_predicate, &input));
        }
        if output_ids.is_empty() {
            prop_assert!(!has_edge(
                &provenance,
                derivation.entity(),
                &generated_predicate,
                derivation.activity(),
            ));
        } else {
            prop_assert!(has_edge(
                &provenance,
                derivation.entity(),
                &generated_predicate,
                derivation.activity(),
            ));
        }
        prop_assert_eq!(assert_entity_generation_invariant(&provenance), Ok(()));
        let (started, ended) = derivation.timing();
        prop_assert!(started <= ended);
        assert_round_trip(&provenance, &derivation.prov_ntriples());
    }
}

/// Mutation witness: appending the same edge must fail even though an `>= 1`
/// existence check would still pass. [GPT-5.6] sq-ddy14
#[test]
fn duplicate_generation_edge_violates_exact_multiplicity() {
    let graph = input_graph(&[1]);
    let derivation = derive_construct(
        &graph,
        "CONSTRUCT { ?s <http://example.test/outputPredicate> ?o } WHERE { ?s <http://example.test/p> ?o }",
        config(&[2]),
    )
    .expect("fixed CONSTRUCT must execute");
    let mut provenance = derivation.prov_graph();
    let duplicate = provenance
        .iter()
        .find(|triple| triple.predicate.as_str() == format!("{PROV}wasGeneratedBy"))
        .expect("derived entity has a generation edge")
        .clone();
    provenance.push(duplicate);

    let error = assert_entity_generation_invariant(&provenance)
        .expect_err("a duplicate generation edge must violate exact multiplicity");
    assert!(
        error.contains("exactly one prov:wasGeneratedBy edge, found 2"),
        "unexpected invariant error: {error}"
    );
}
