//! Tests for the U1 personal-data-storage generator (bead `sq-i6du2.2`).
//!
//! Bead `sq-i6du2.2` un-ignores the two scaffold placeholder tests and adds
//! additional non-vacuous tests covering:
//! - determinism (same seed → byte-identical N-Quads and decisions)
//! - oracle fail-closed (no matching allow → Deny for all three models)
//! - owner-always-allowed (the canonical WAC pod invariant)
//! - unknown-agent-deny (fail-closed for unlisted agents)
//! - non-empty corpus (generator produces data at SF=1)
//! - W2 query fixtures present and non-vacuous
//! - expressibility matrix entries for ClientRestricted and Group audiences
//!
//! This file ONLY edits the test file; it does NOT touch any other file.

use sparq_acbench::QueryClass;

/// Compile-time check: the `QueryClass` type is importable from the crate root.
#[test]
fn query_class_accessible() {
    // QueryClass derives PartialEq; verify it compiles.
    assert_eq!(QueryClass::Point, QueryClass::Point);
    assert_ne!(QueryClass::Point, QueryClass::Scan);
}

/// Compile-time check: `PersonalDataset` is importable from `personal`.
#[test]
fn personal_dataset_type_accessible() {
    let _: fn(&sparq_acbench::GenParams) -> sparq_acbench::personal::PersonalDataset =
        sparq_acbench::personal::generate;
}

/// Determinism invariant: same seed → byte-identical N-Quads.
///
/// Exercises the core benchmark credibility guarantee (§2.1 design record):
/// identical `GenParams` produces byte-identical output on every run.
#[test]
fn generate_u1_determinism() {
    use sparq_acbench::{personal, GenParams};
    let params = GenParams::smoke();
    let ds1 = personal::generate(&params);
    let ds2 = personal::generate(&params);
    assert_eq!(
        ds1.data_nquads, ds2.data_nquads,
        "U1 generator must be deterministic: same seed → same N-Quads"
    );
    assert_eq!(
        ds1.expected_decisions.len(),
        ds2.expected_decisions.len(),
        "U1 generator must be deterministic: same seed → same number of expected decisions"
    );
}

/// Oracle fail-closed: every WAC expected decision in the corpus must match the
/// by-construction oracle result.
///
/// This is the central oracle soundness check: the `expected_decisions` field
/// is generated by the same oracle, so this test is effectively a round-trip
/// check. A mismatch would indicate a bug in the decision generation loop.
#[test]
fn generate_u1_oracle_fail_closed() {
    use sparq_acbench::{oracle_wac, personal, GenParams};
    let params = GenParams::smoke();
    let ds = personal::generate(&params);
    // Every expected decision in the WAC lane must match the oracle.
    for ed in ds
        .expected_decisions
        .iter()
        .filter(|e| e.model == sparq_acbench::AcModel::Wac)
    {
        let oracle_result = oracle_wac(&ed.request, &ds.intents);
        assert_eq!(
            oracle_result, ed.decision,
            "U1 WAC oracle mismatch for request {:?}",
            ed.request
        );
    }
}

/// Owner-always-allowed invariant: the pod owner must be granted Allow on every
/// resource under WAC (the canonical owner-centric Solid pod shape).
#[test]
fn owner_always_allowed_wac() {
    use sparq_acbench::{personal, AcModel, AccessMode, Decision, GenParams, Request};
    let params = GenParams::smoke();
    let ds = personal::generate(&params);

    // Extract owner URI from the first WAC expected decision.
    // The owner is the agent that has Allow on ALL resources.
    let owner_ed = ds
        .expected_decisions
        .iter()
        .find(|e| e.model == AcModel::Wac && e.decision == Decision::Allow)
        .expect("U1 must produce at least one Allow decision");
    let owner_uri = &owner_ed.request.agent;

    // Collect all unique resource URIs from the intent table.
    let resource_uris: Vec<String> = ds
        .intents
        .iter()
        .map(|r| r.resource_uri.clone())
        .collect::<std::collections::HashSet<_>>()
        .into_iter()
        .collect();

    for resource_uri in &resource_uris {
        let req = Request {
            agent: owner_uri.clone(),
            client: None,
            resource: resource_uri.clone(),
            mode: AccessMode::read_only(),
        };
        // Owner must be allowed for every resource that the owner owns
        // (pod root subtree intent covers all resources in the pod).
        let decision = sparq_acbench::oracle_wac(&req, &ds.intents);
        // The owner subtree grant covers any URI starting with the pod root.
        // Resources in the pod start with the pod base URI, so all should be Allow.
        assert_eq!(
            decision,
            Decision::Allow,
            "Owner must have WAC Allow on resource {resource_uri}"
        );
    }
}

/// Unknown-agent-deny: an agent not listed in any policy must be Denied on
/// non-public resources (fail-closed default).
#[test]
fn unknown_agent_denied_on_private_resources() {
    use sparq_acbench::{personal, AcModel, AccessMode, Decision, GenParams, Request};
    let params = GenParams::smoke();
    let ds = personal::generate(&params);

    let unknown = "https://pod.example/unknown/profile/card#me";
    // Find at least one expected Deny for the unknown agent in the WAC lane.
    let deny_count = ds
        .expected_decisions
        .iter()
        .filter(|e| {
            e.model == AcModel::Wac && e.request.agent == unknown && e.decision == Decision::Deny
        })
        .count();

    assert!(
        deny_count > 0,
        "U1 must produce at least one WAC Deny for the unknown agent (fail-closed)"
    );

    // Verify each Deny round-trips through the oracle.
    for ed in ds
        .expected_decisions
        .iter()
        .filter(|e| e.model == AcModel::Wac && e.request.agent == unknown)
    {
        let oracle = sparq_acbench::oracle_wac(&ed.request, &ds.intents);
        assert_eq!(
            oracle, ed.decision,
            "Oracle mismatch for unknown agent request"
        );
    }

    // Also verify: an explicit request for an unlisted resource URI returns Deny.
    let unlisted_req = Request {
        agent: unknown.to_string(),
        client: None,
        resource: "https://pod.example/user42/nonexistent/resource999".to_string(),
        mode: AccessMode::read_only(),
    };
    let decision = sparq_acbench::oracle_wac(&unlisted_req, &ds.intents);
    assert_eq!(
        decision,
        Decision::Deny,
        "Fail-closed: unlisted resource must return Deny"
    );
}

/// Non-empty corpus: the generator must produce a non-trivial number of
/// N-Quads lines, intents, and expected decisions at SF=1.
#[test]
fn non_empty_corpus_at_sf1() {
    use sparq_acbench::{personal, GenParams};
    let params = GenParams::smoke();
    let ds = personal::generate(&params);

    assert!(
        ds.data_nquads.len() >= 10,
        "U1 must produce at least 10 N-Quads at SF=1 (got {})",
        ds.data_nquads.len()
    );
    assert!(
        ds.intents.len() >= 3,
        "U1 must produce at least 3 intent rows at SF=1 (got {})",
        ds.intents.len()
    );
    assert!(
        ds.expected_decisions.len() >= 3,
        "U1 must produce at least 3 expected decisions at SF=1 (got {})",
        ds.expected_decisions.len()
    );
}

/// W2 query fixtures: at least one fixture of each class must be present.
#[test]
fn w2_fixtures_present() {
    use sparq_acbench::{personal, GenParams, QueryClass};
    let params = GenParams::smoke();
    let ds = personal::generate(&params);

    let has_point = ds.queries.iter().any(|q| q.class == QueryClass::Point);
    let has_scan = ds.queries.iter().any(|q| q.class == QueryClass::Scan);
    let has_join = ds.queries.iter().any(|q| q.class == QueryClass::Join);
    let has_agg = ds.queries.iter().any(|q| q.class == QueryClass::Aggregate);

    assert!(has_point, "U1 must produce at least one Q-point fixture");
    assert!(has_scan, "U1 must produce at least one Q-scan fixture");
    assert!(has_join, "U1 must produce at least one Q-join fixture");
    assert!(has_agg, "U1 must produce at least one Q-agg fixture");
}

/// Expressibility matrix: ClientRestricted audience must be Approximation in WAC
/// and Native in ACP and ODRL (design record §2.2 documented asymmetry).
#[test]
fn expressibility_matrix_client_restricted() {
    use sparq_acbench::{
        personal, AcModel, AccessMode, Audience, Condition, Effect, Expressibility, GenParams,
        IntentRow, Scope,
    };
    // Build a minimal ClientRestricted intent row to probe the expressibility matrix.
    let row = IntentRow {
        audience: Audience::ClientRestricted {
            agent: "https://agent.example/a#me".to_string(),
            client: "https://app.example/myapp".to_string(),
        },
        scope: Scope::Resource,
        mode: AccessMode::read_only(),
        condition: Condition::None,
        effect: Effect::Allow,
        resource_uri: "https://pod.example/res1".to_string(),
    };

    let wac_expr = personal::wac_expressibility(&row);
    let acp_expr = personal::acp_expressibility(&row, &[]);
    let odrl_expr = personal::odrl_expressibility(&row);

    assert_eq!(
        wac_expr,
        Expressibility::Approximation,
        "WAC ClientRestricted must be Approximation (acl:origin approximates acp:client)"
    );
    assert_eq!(
        acp_expr,
        Expressibility::Native,
        "ACP ClientRestricted must be Native (acp:client)"
    );
    assert_eq!(
        odrl_expr,
        Expressibility::Native,
        "ODRL ClientRestricted must be Native"
    );

    // Unused import guard: reference GenParams and AcModel to avoid dead_code warnings.
    let _ = (AcModel::Wac, GenParams::smoke());
}

/// Expressibility matrix: Group audience must be Native in WAC, Expansion in ACP
/// (per-member expansion), Native in ODRL (odrl:PartyCollection).
#[test]
fn expressibility_matrix_group() {
    use sparq_acbench::{
        personal, AcModel, AccessMode, Audience, Condition, Effect, Expressibility, GenParams,
        IntentRow, Scope,
    };
    let row = IntentRow {
        audience: Audience::Group("https://pod.example/groups/friends/".to_string()),
        scope: Scope::Resource,
        mode: AccessMode::read_only(),
        condition: Condition::None,
        effect: Effect::Allow,
        resource_uri: "https://pod.example/res2".to_string(),
    };

    let wac_expr = personal::wac_expressibility(&row);
    let acp_expr_resolved = personal::acp_expressibility(
        &row,
        &[
            "https://agent.example/a1#me".to_string(),
            "https://agent.example/a2#me".to_string(),
        ],
    );
    let odrl_expr = personal::odrl_expressibility(&row);

    assert_eq!(
        wac_expr,
        Expressibility::Native,
        "WAC Group must be Native (acl:agentGroup)"
    );
    // ACP expands group to per-member matchers: Expansion(2) for 2 members.
    assert_eq!(
        acp_expr_resolved,
        Expressibility::Expansion(2),
        "ACP Group with 2 members must be Expansion(2)"
    );
    assert_eq!(
        odrl_expr,
        Expressibility::Native,
        "ODRL Group must be Native (odrl:PartyCollection)"
    );

    let _ = (AcModel::Wac, GenParams::smoke());
}

/// ACP oracle round-trip: every ACP expected decision must match the oracle.
#[test]
fn generate_u1_oracle_acp_round_trip() {
    use sparq_acbench::{oracle_acp, personal, AcModel, GenParams};
    let params = GenParams::smoke();
    let ds = personal::generate(&params);
    for ed in ds
        .expected_decisions
        .iter()
        .filter(|e| e.model == AcModel::Acp)
    {
        let oracle_result = oracle_acp(&ed.request, &ds.intents);
        assert_eq!(
            oracle_result, ed.decision,
            "U1 ACP oracle mismatch for request {:?}",
            ed.request
        );
    }
}

/// ODRL oracle round-trip: every ODRL expected decision must match the oracle.
#[test]
fn generate_u1_oracle_odrl_round_trip() {
    use sparq_acbench::{oracle_odrl, personal, AcModel, GenParams};
    let params = GenParams::smoke();
    let ds = personal::generate(&params);
    for ed in ds
        .expected_decisions
        .iter()
        .filter(|e| e.model == AcModel::Odrl)
    {
        let oracle_result = oracle_odrl(&ed.request, &ds.intents);
        assert_eq!(
            oracle_result, ed.decision,
            "U1 ODRL oracle mismatch for request {:?}",
            ed.request
        );
    }
}

/// Policy graphs non-empty: WAC, ACP, and ODRL policy graphs must each contain
/// at least one compiled policy entry.
#[test]
fn compiled_policies_non_empty() {
    use sparq_acbench::{personal, GenParams};
    let params = GenParams::smoke();
    let ds = personal::generate(&params);

    assert!(
        !ds.wac_policy.is_empty(),
        "WAC policy graph must be non-empty"
    );
    assert!(
        !ds.acp_policy.is_empty(),
        "ACP policy graph must be non-empty"
    );
    assert!(
        !ds.odrl_policy.is_empty(),
        "ODRL policy graph must be non-empty"
    );
}

/// N-Quads sorted invariant: data_nquads must be lexicographically sorted
/// (enforced by the generator for determinism).
#[test]
fn data_nquads_sorted() {
    use sparq_acbench::{personal, GenParams};
    let params = GenParams::smoke();
    let ds = personal::generate(&params);

    let mut sorted = ds.data_nquads.clone();
    sorted.sort();
    assert_eq!(
        ds.data_nquads, sorted,
        "data_nquads must be lexicographically sorted for determinism"
    );
}
