// [OPUS-4.8] written while Fable 5 unavailable — re-review when Fable returns.
//! sq-c5f: gate-count regression gate.
//!
//! Records the ACIR/UltraHonk gate count (`bb gates -s ultra_honk` →
//! `circuit_size`, the noir-optimisation ground truth) of every compiled
//! `zk/compose/` circuit-family member in a CHECKED-IN snapshot
//! (`tests/gate_count_snapshot.json`), and a test that recompiles each member,
//! reads its real `circuit_size`, and FAILS if it exceeds
//! `baseline * (1 + tolerance/100)`. This prevents silent circuit BLOAT (a
//! refactor that quietly doubles a relation's constraints).
//!
//! Tolerance (3%, in the snapshot) absorbs the small cross-platform/build
//! variance in bb's gate counts — measured ~0.5–0.75% on the scan members
//! between the darwin-arm64 baseline and this box's linux-x86_64 build, and 0%
//! on the filter members — while still tripping on real growth (a relation that
//! grows typically moves tens of percent, far outside 3%).
//!
//! Toolchain-gated: needs `nargo` + `bb`. Skips cleanly when absent (like the
//! e2e full-prove tests), so default CI without the toolchain stays green. It is
//! NOT `#[ignore]`d — gate counts are cheap (compile + `bb gates`, no proving),
//! so the regression gate runs in the normal suite when the toolchain is
//! present.
//!
//! [FABLE-5] sq-7pifo: because it is non-`#[ignore]`d it is SKIPPED by the
//! zk-toolchain lane's `cargo test -- --ignored` step, and the default ci.yml
//! lanes have no `nargo`/`bb` so it self-skips there — i.e. it ran in NO CI lane
//! and its baselines went silently stale (the sq-25mgo fix grew filter_f64 well
//! past the checked-in regression tolerance untripped). The zk-toolchain lane now runs the
//! non-ignored `gate_count` + `sparql_catalog` binaries in a dedicated step (WITH
//! the toolchain present) so an intentional circuit change must re-baseline in
//! the same PR — see `.github/workflows/zk-toolchain.yml`.
//!
//! Re-baseline after an INTENTIONAL circuit change: run
//! `bench/zk-compose/scripts/gate_counts.sh` and copy the new `circuit_size`
//! values into `tests/gate_count_snapshot.json` (and the bench JSON).

use serde::Deserialize;
use std::path::{Path, PathBuf};
use std::process::Command;

/// The checked-in baseline snapshot (compiled into the test binary).
const SNAPSHOT_JSON: &str = include_str!("gate_count_snapshot.json");

/// The published bench gate-count JSON (regenerated by
/// `bench/zk-compose/scripts/gate_counts.sh`). Compiled in so the parity test
/// below catches snapshot↔bench drift WITHOUT needing the file at runtime.
const BENCH_JSON: &str = include_str!("../../../bench/zk-compose/gate_counts_latest.json");

#[derive(Deserialize)]
struct Snapshot {
    tolerance_pct: f64,
    members: std::collections::BTreeMap<String, u64>,
    /// sq-ncvq.8 (Gate G5): top-level `zk/` `bin` packages that are deliberately
    /// NOT gate-count-baselined (a `bin` that drives library tests, not a deployed
    /// proving circuit). Map of package name → reason.
    /// `snapshot_covers_top_level_circuits` requires every top-level `bin` circuit
    /// to be either a `members` baseline or listed here. [OPUS-4.8] sq-5reoy: this
    /// is currently empty — the only former entry (the xpath unit-test harness)
    /// moved to the `sparq-org/noir_XPath` face repo when the `zk/xpath` tree was
    /// externalized (#1599), leaving `zk/compose` as the sole in-tree circuit family.
    #[serde(default)]
    exempt_circuits: std::collections::BTreeMap<String, String>,
}

/// `bench/zk-compose/gate_counts_latest.json` shape (the `sparq_ieee754` JSON
/// convention — the `circuit_size` shape that originated in the ieee754 lineage,
/// now the sparq-org/noir_IEEE754 face repo, sq-5reoy):
/// `{ "benchmarks": { "<member>": { "circuit_size": N } } }`.
#[derive(Deserialize)]
struct BenchGateCounts {
    benchmarks: std::collections::BTreeMap<String, BenchEntry>,
}
#[derive(Deserialize)]
struct BenchEntry {
    circuit_size: u64,
}

/// `bb gates` output shape: `{ "functions": [ { "circuit_size": N, ... } ] }`.
#[derive(Deserialize)]
struct BbGates {
    functions: Vec<BbFunction>,
}
#[derive(Deserialize)]
struct BbFunction {
    circuit_size: u64,
}

fn toolchain_available() -> bool {
    fn on_path(tool: &str) -> bool {
        Command::new(tool)
            .arg("--version")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    }
    on_path("nargo") && on_path("bb")
}

/// The repo's top-level `zk/` directory, relative to this crate (workspace
/// layout: `crates/sparq-zk-compose` → `../../zk`).
fn zk_root() -> PathBuf {
    let here = Path::new(env!("CARGO_MANIFEST_DIR"));
    here.parent()
        .and_then(Path::parent)
        .map(|root| root.join("zk"))
        .expect("workspace layout")
}

/// `zk/compose/` workspace root. Mirrors `CircuitProver::from_crate_root`.
fn compose_dir() -> PathBuf {
    zk_root().join("compose")
}

/// Minimal `Nargo.toml` reader: the `[package] name` and `type`, without pulling
/// in a TOML crate (these files are machine/hand-written in a fixed, simple
/// shape). Returns `(name, type)` where `type` is `""` for a `[workspace]` root
/// (no `[package]`). Good enough for the G5 coverage scan — it only needs to
/// tell a `bin` proving circuit apart from a `lib`/workspace.
fn parse_nargo_toml(path: &Path) -> Option<(String, String)> {
    let text = std::fs::read_to_string(path).ok()?;
    let mut in_package = false;
    let mut name = None;
    let mut pkg_type = String::new();
    for raw in text.lines() {
        let line = raw.trim();
        if line.starts_with('[') {
            in_package = line == "[package]";
            continue;
        }
        if !in_package {
            continue;
        }
        if let Some(v) = line.strip_prefix("name") {
            if let Some(val) = v.trim_start().strip_prefix('=') {
                name = Some(val.trim().trim_matches('"').to_string());
            }
        } else if let Some(v) = line.strip_prefix("type") {
            if let Some(val) = v.trim_start().strip_prefix('=') {
                pkg_type = val.trim().trim_matches('"').to_string();
            }
        }
    }
    name.map(|n| (n, pkg_type))
}

/// Recursively collect every `bin`-type Noir package under `zk/`, EXCLUDING the
/// `zk/compose/` family (already covered by `snapshot_covers_every_member`) and
/// any `target/` build dir. Returns `(package_name, manifest_dir)` pairs. A
/// `bin` package is a deployable proving circuit (it has a `main`); `lib`
/// packages and `[workspace]` roots have no `circuit_size` and are skipped.
fn top_level_bin_circuits(zk: &Path) -> Vec<(String, PathBuf)> {
    let compose = zk.join("compose");
    let mut found = Vec::new();
    let mut stack = vec![zk.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let entries = match std::fs::read_dir(&dir) {
            Ok(e) => e,
            Err(_) => continue,
        };
        for entry in entries.flatten() {
            if !entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
                continue;
            }
            let path = entry.path();
            // zk/compose is the EXISTING gate's domain; target/ is build output.
            if path == compose || entry.file_name() == "target" {
                continue;
            }
            if let Some((name, ty)) = parse_nargo_toml(&path.join("Nargo.toml")) {
                if ty == "bin" {
                    found.push((name, path.clone()));
                }
            }
            stack.push(path);
        }
    }
    found.sort();
    found
}

/// Compile the whole workspace once (idempotent), producing `target/<pkg>.json`
/// ACIR for every member.
fn compile_workspace(dir: &Path) {
    let out = Command::new("nargo")
        .arg("compile")
        .arg("--workspace")
        .current_dir(dir)
        .output()
        .expect("nargo runs");
    assert!(
        out.status.success(),
        "nargo compile --workspace failed:\n{}",
        String::from_utf8_lossy(&out.stderr)
    );
}

/// `bb gates -s ultra_honk` → the member's `circuit_size`.
fn gate_count(dir: &Path, member: &str) -> u64 {
    let acir = dir.join("target").join(format!("{member}.json"));
    let out = Command::new("bb")
        .arg("gates")
        .arg("-s")
        .arg("ultra_honk")
        .arg("-b")
        .arg(&acir)
        .output()
        .expect("bb runs");
    assert!(
        out.status.success(),
        "bb gates {member} failed:\n{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let parsed: BbGates =
        serde_json::from_slice(&out.stdout).expect("bb gates emits the expected JSON shape");
    parsed
        .functions
        .first()
        .expect("at least one function in the circuit")
        .circuit_size
}

/// sq-c5f — the regression gate. For every member in the checked-in snapshot,
/// assert the live gate count has not regressed beyond the tolerance.
#[test]
fn gate_count_regression() {
    if !toolchain_available() {
        eprintln!("nargo/bb absent; skipping gate-count regression gate");
        return;
    }
    let snapshot: Snapshot =
        serde_json::from_str(SNAPSHOT_JSON).expect("gate_count_snapshot.json parses");
    let dir = compose_dir();
    compile_workspace(&dir);

    let mut regressions = Vec::new();
    for (member, &baseline) in &snapshot.members {
        let live = gate_count(&dir, member);
        let ceiling = (baseline as f64 * (1.0 + snapshot.tolerance_pct / 100.0)).floor() as u64;
        let delta_pct = (live as f64 - baseline as f64) / baseline as f64 * 100.0;
        eprintln!("{member}: baseline={baseline} live={live} ({delta_pct:+.2}%) ceiling={ceiling}");
        if live > ceiling {
            regressions.push(format!(
                "{member}: live={live} exceeds ceiling={ceiling} (baseline={baseline}, +{delta_pct:.2}% > {:.1}% tolerance)",
                snapshot.tolerance_pct
            ));
        }
    }

    assert!(
        regressions.is_empty(),
        "circuit gate-count REGRESSION(s) detected (silent bloat — re-baseline only if INTENTIONAL):\n{}",
        regressions.join("\n")
    );
}

/// Belt-and-braces: the snapshot must cover every compiled member directory under
/// `zk/compose/` (so a new family member can't be added without a baseline). This
/// runs WITHOUT the toolchain — it only reads directory names + the snapshot.
#[test]
fn snapshot_covers_every_member() {
    let snapshot: Snapshot =
        serde_json::from_str(SNAPSHOT_JSON).expect("gate_count_snapshot.json parses");
    let dir = compose_dir();
    if !dir.exists() {
        eprintln!("zk/compose absent; skipping coverage check");
        return;
    }
    // Member packages are the subdirs with a Nargo.toml that are NOT the shared
    // `compose_core` library (which is not a proving member).
    let mut missing = Vec::new();
    for entry in std::fs::read_dir(&dir).expect("read zk/compose") {
        let entry = entry.expect("dir entry");
        if !entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
            continue;
        }
        let name = entry.file_name().to_string_lossy().into_owned();
        if name == "compose_core" || name == "target" {
            continue;
        }
        if !entry.path().join("Nargo.toml").exists() {
            continue;
        }
        if !snapshot.members.contains_key(&name) {
            missing.push(name);
        }
    }
    assert!(
        missing.is_empty(),
        "compiled member(s) have NO gate-count baseline in tests/gate_count_snapshot.json: {missing:?} \
         — add a baseline (run bench/zk-compose/scripts/gate_counts.sh)"
    );
}

/// sq-ifur — snapshot ↔ bench JSON parity. The published bench gate-count JSON
/// (`bench/zk-compose/gate_counts_latest.json`) and the regression-gate snapshot
/// (`gate_count_snapshot.json`) MUST cover exactly the same members with exactly
/// the same `circuit_size`. They are two views of one measurement, and the
/// re-baseline procedure (run `gate_counts.sh`, copy into both) is only correct
/// if they stay in lockstep.
///
/// This is the regression guard for the silent-drop bug sq-ifur closed: the bench
/// script's member list was a HAND-MAINTAINED array that had fallen behind the
/// snapshot (no `holder_pok`, no `hidden_issuer_d4`, no join/scan-lattice members),
/// so the bench JSON's `holder_pok` baseline was simply never published. The script
/// now derives its members FROM this snapshot, and this test makes any future
/// divergence a hard failure. Runs WITHOUT the toolchain — it only parses the two
/// checked-in JSONs.
#[test]
fn bench_json_matches_snapshot() {
    let snapshot: Snapshot =
        serde_json::from_str(SNAPSHOT_JSON).expect("gate_count_snapshot.json parses");
    let bench: BenchGateCounts =
        serde_json::from_str(BENCH_JSON).expect("gate_counts_latest.json parses");

    // BTreeMap → deterministic, sorted membership comparison.
    let snap_members: Vec<&String> = snapshot.members.keys().collect();
    let bench_members: Vec<&String> = bench.benchmarks.keys().collect();
    assert_eq!(
        snap_members, bench_members,
        "member set drift between tests/gate_count_snapshot.json and \
         bench/zk-compose/gate_counts_latest.json — re-run \
         bench/zk-compose/scripts/gate_counts.sh and copy the result into BOTH"
    );

    let mut mismatches = Vec::new();
    for (member, &baseline) in &snapshot.members {
        let bench_size = bench.benchmarks[member].circuit_size;
        if bench_size != baseline {
            mismatches.push(format!("{member}: snapshot={baseline} bench={bench_size}"));
        }
    }
    assert!(
        mismatches.is_empty(),
        "circuit_size disagrees between snapshot and bench JSON (they must be ONE \
         measurement — re-baseline both together):\n{}",
        mismatches.join("\n")
    );
}

/// [OPUS-4.8] sq-ncvq.8 (Gate G5) — extend the gate-count snapshot coverage
/// beyond `zk/compose/` to EVERY top-level `zk/` proving circuit. A "proving
/// circuit" is a `bin`-type Noir package (it has a `main`, so it has a
/// `circuit_size`); `lib` packages and `[workspace]` roots are not proven and
/// carry no gate-count guarantee.
///
/// `snapshot_covers_every_member` already fails if a `zk/compose/` member lacks
/// a baseline. This test closes the same gap for a NEW top-level circuit family
/// added elsewhere under `zk/` (e.g. a future `zk/<family>/<circuit>` `bin`):
/// it must have either a `members` baseline OR an explicit `exempt_circuits`
/// entry (with a documented reason). So a deployable circuit cannot silently
/// ship without a gate-count baseline.
///
/// [OPUS-4.8] sq-5reoy: after the `zk/ieee754` and `zk/xpath` trees were
/// externalized to the `sparq-org/noir_IEEE754` / `sparq-org/noir_XPath` face
/// repos (#1599), `zk/compose/` is the only in-tree circuit family, so there are
/// no top-level `bin` packages outside it and `exempt_circuits` is empty (the
/// former `xpath_unit_tests` harness is now covered by the face repo's CI).
/// Runs WITHOUT the toolchain — it only reads `Nargo.toml`s + the snapshot.
///
/// [OPUS-4.8] sq-ncvq.10 doc-sync: this test is the "Enforced by: **G5**" cell of
/// the "ZK verifier / circuits" row in the AGENTS.md "Post-batch re-evaluation
/// checklist" table (alongside the reactive `flow-on:new-zk-circuit-gatecount`
/// rule). That table row and this docstring are the two halves of the same rule —
/// change one and update the other; the divergence is what sq-ncvq.10 prevents.
#[test]
fn snapshot_covers_top_level_circuits() {
    let snapshot: Snapshot =
        serde_json::from_str(SNAPSHOT_JSON).expect("gate_count_snapshot.json parses");
    let zk = zk_root();
    if !zk.exists() {
        eprintln!("zk/ absent; skipping top-level circuit coverage check");
        return;
    }

    let mut uncovered = Vec::new();
    for (name, path) in top_level_bin_circuits(&zk) {
        let covered =
            snapshot.members.contains_key(&name) || snapshot.exempt_circuits.contains_key(&name);
        if !covered {
            uncovered.push(format!("{name} ({})", path.display()));
        }
    }

    assert!(
        uncovered.is_empty(),
        "top-level zk/ proving circuit(s) have NO gate-count baseline AND NO \
         exempt_circuits entry in tests/gate_count_snapshot.json: {uncovered:?} \
         — add a `members` baseline (run bench/zk-compose/scripts/gate_counts.sh) \
         for a deployed circuit, or an `exempt_circuits` entry (with a reason) for \
         a non-deployed bin (e.g. a test harness)"
    );

    // Guard against a stale exemption: every exempt_circuits key must still be a
    // real top-level bin package (or a compose member), else the exemption is
    // dead and should be removed.
    let live: std::collections::BTreeSet<String> = top_level_bin_circuits(&zk)
        .into_iter()
        .map(|(n, _)| n)
        .collect();
    let mut stale = Vec::new();
    for name in snapshot.exempt_circuits.keys() {
        if !live.contains(name) && !snapshot.members.contains_key(name) {
            stale.push(name.clone());
        }
    }
    assert!(
        stale.is_empty(),
        "exempt_circuits entr(ies) no longer match any top-level zk/ bin package \
         — remove the dead exemption from tests/gate_count_snapshot.json: {stale:?}"
    );
}
