// [OPUS-4.8] written while Fable 5 unavailable — re-review when Fable returns.
//! sq-1s2.1.2: SPARQL ZK gate-cost catalog ↔ snapshot consistency gate.
//!
//! `bench/zk-compose/sparql_feature_catalog.json` is a coverage map AND an
//! optimisation-target list for the ZK-SPARQL engine (design:
//! `research/zk-field-native-encoding.md` §6, PR #765). It is GENERATED by
//! `bench/zk-compose/scripts/sparql_catalog.py`, which joins each query's
//! `circuit_size` from the regression-gated snapshot
//! (`tests/gate_count_snapshot.json`) so the two can never drift.
//!
//! This test re-checks the COMMITTED catalog JSON against the COMMITTED snapshot
//! WITHOUT the nargo/bb toolchain (it only parses two checked-in JSONs), so it
//! runs in the normal suite and is deterministic / non-flaky. It enforces the
//! §6.3 anti-drift contract:
//!
//!   * every `zk_members` entry of a covered query names a member that EXISTS in
//!     the snapshot (a typo or a removed member is a hard failure);
//!   * every covered query's `circuit_size` EQUALS the max of its named members'
//!     snapshot sizes (the join is faithful — no hand-typed number that could
//!     disagree with the regression-gated value);
//!   * every per-member `circuit_size_per_member` value EQUALS the snapshot;
//!   * every GAP (`status` containing "NO ZK CIRCUIT YET") carries
//!     `circuit_size: null` and an EMPTY `zk_members` (NEVER a fabricated number);
//!   * the `summary` counts match the actual query rows.
//!
//! If this fails after an INTENTIONAL circuit change, re-run
//! `bench/zk-compose/scripts/gate_counts.sh` (re-baseline the snapshot + bench
//! JSON) and then `bench/zk-compose/scripts/sparql_catalog.py >
//! bench/zk-compose/sparql_feature_catalog.json` to re-join the new numbers.

use serde::Deserialize;
use std::collections::BTreeMap;

/// The regression-gate snapshot (the source of truth for `circuit_size`).
const SNAPSHOT_JSON: &str = include_str!("gate_count_snapshot.json");
/// The generated SPARQL feature catalog under test.
const CATALOG_JSON: &str = include_str!("../../../bench/zk-compose/sparql_feature_catalog.json");

/// Substring marking a coverage GAP (no ZK circuit). Kept in lockstep with the
/// `STATUS_GAP` string in `sparql_catalog.py`.
const GAP_MARKER: &str = "NO ZK CIRCUIT YET";

#[derive(Deserialize)]
struct Snapshot {
    members: BTreeMap<String, u64>,
}

#[derive(Deserialize)]
struct Catalog {
    summary: Summary,
    queries: BTreeMap<String, Query>,
}

#[derive(Deserialize)]
struct Summary {
    total_queries: usize,
    covered: usize,
    partial: usize,
    gaps: usize,
    high_gate_flagged: Vec<String>,
}

#[derive(Deserialize)]
struct Query {
    #[allow(dead_code)]
    feature: String,
    sparql: String,
    zk_members: Vec<String>,
    /// `null` for gaps and verifier-side-only rows; an integer for covered rows.
    circuit_size: Option<u64>,
    status: String,
    flag: Option<String>,
    #[serde(default)]
    circuit_size_per_member: BTreeMap<String, u64>,
    #[serde(default)]
    floor_member: Option<String>,
    #[serde(default)]
    floor_circuit_size: Option<u64>,
    /// Honesty flag for the bounded property-path closures (`p?`/`p+`/`p*`):
    /// they are covered ONLY under the EXISTENCE-ONLY bounded statement
    /// (research/zksparql-fragment-extension.md §4), never the unbounded SPARQL
    /// closure. `false`/absent for every other row.
    #[serde(default)]
    bounded: bool,
}

impl Query {
    fn is_gap(&self) -> bool {
        self.status.contains(GAP_MARKER)
    }
    fn is_covered(&self) -> bool {
        self.status == "covered"
    }
}

fn load() -> (Snapshot, Catalog) {
    let snapshot: Snapshot =
        serde_json::from_str(SNAPSHOT_JSON).expect("gate_count_snapshot.json parses");
    let catalog: Catalog =
        serde_json::from_str(CATALOG_JSON).expect("sparql_feature_catalog.json parses");
    (snapshot, catalog)
}

/// Every member named by a covered query MUST exist in the regression-gated
/// snapshot — a typo or a removed member is a hard failure (the anti-drift
/// contract, §6.3). Gaps must name NO members.
#[test]
fn catalog_members_exist_in_snapshot() {
    let (snapshot, catalog) = load();
    let mut errors = Vec::new();
    for (id, q) in &catalog.queries {
        for m in &q.zk_members {
            if !snapshot.members.contains_key(m) {
                errors.push(format!(
                    "{id}: zk_member '{m}' is absent from gate_count_snapshot.json"
                ));
            }
        }
        if let Some(fm) = &q.floor_member {
            if !snapshot.members.contains_key(fm) {
                errors.push(format!(
                    "{id}: floor_member '{fm}' is absent from the snapshot"
                ));
            }
        }
        if q.is_gap() && !q.zk_members.is_empty() {
            errors.push(format!(
                "{id}: status is a GAP but it names ZK members {:?} — a gap has no circuit",
                q.zk_members
            ));
        }
    }
    assert!(
        errors.is_empty(),
        "catalog ↔ snapshot member mismatch (re-run bench/zk-compose/scripts/sparql_catalog.py):\n{}",
        errors.join("\n")
    );
}

/// The JOIN is faithful: every covered query's `circuit_size` equals the MAX of
/// its named members' snapshot sizes, and every `circuit_size_per_member` value
/// equals the snapshot. A number can only come from the snapshot — never
/// hand-typed into the catalog where it could disagree.
#[test]
fn covered_circuit_sizes_match_snapshot() {
    let (snapshot, catalog) = load();
    let mut errors = Vec::new();
    for (id, q) in &catalog.queries {
        // Per-member join check (applies to any row with members).
        for (m, &size) in &q.circuit_size_per_member {
            match snapshot.members.get(m) {
                Some(&snap) if snap == size => {}
                Some(&snap) => errors.push(format!(
                    "{id}: per-member {m} catalog={size} != snapshot={snap}"
                )),
                None => errors.push(format!("{id}: per-member {m} absent from snapshot")),
            }
        }
        if let (Some(fm), Some(fsize)) = (&q.floor_member, q.floor_circuit_size) {
            if let Some(&snap) = snapshot.members.get(fm) {
                if snap != fsize {
                    errors.push(format!(
                        "{id}: floor {fm} catalog={fsize} != snapshot={snap}"
                    ));
                }
            }
        }
        if q.is_covered() {
            // Headline circuit_size = max over named members' snapshot sizes.
            let max = q
                .zk_members
                .iter()
                .filter_map(|m| snapshot.members.get(m).copied())
                .max();
            assert!(
                !q.zk_members.is_empty(),
                "{id}: covered query has no zk_members"
            );
            match (q.circuit_size, max) {
                (Some(cs), Some(mx)) if cs == mx => {}
                (cs, mx) => errors.push(format!(
                    "{id}: covered circuit_size={cs:?} != max(member snapshot sizes)={mx:?}"
                )),
            }
        }
    }
    assert!(
        errors.is_empty(),
        "catalog circuit_size disagrees with the regression-gated snapshot \
         (re-run bench/zk-compose/scripts/sparql_catalog.py to re-join):\n{}",
        errors.join("\n")
    );
}

/// Honesty gate (load-bearing, §6.1): a GAP NEVER carries a fabricated gate
/// number. Every gap row must have `circuit_size: null` and the gap flag.
#[test]
fn gaps_carry_no_fabricated_number() {
    let (_snapshot, catalog) = load();
    let mut errors = Vec::new();
    for (id, q) in &catalog.queries {
        if q.is_gap() {
            if q.circuit_size.is_some() {
                errors.push(format!(
                    "{id}: GAP must have circuit_size: null, found {:?} — NEVER fabricate a gate number",
                    q.circuit_size
                ));
            }
            if q.flag.as_deref() != Some("NO_ZK_CIRCUIT_YET") {
                errors.push(format!(
                    "{id}: GAP must carry flag NO_ZK_CIRCUIT_YET, found {:?}",
                    q.flag
                ));
            }
        }
    }
    assert!(
        errors.is_empty(),
        "a gap row carries a fabricated number or wrong flag:\n{}",
        errors.join("\n")
    );
}

/// The `summary` counts and `high_gate_flagged` list must match the actual rows,
/// so a stale summary (e.g. a hand-edited JSON) is caught.
#[test]
fn summary_matches_rows() {
    let (_snapshot, catalog) = load();
    let mut covered = 0;
    let mut partial = 0;
    let mut gaps = 0;
    let mut high_gate: Vec<String> = Vec::new();
    for (id, q) in &catalog.queries {
        if q.is_gap() {
            gaps += 1;
        } else if q.is_covered() {
            covered += 1;
        } else {
            partial += 1;
        }
        if matches!(
            q.flag.as_deref(),
            Some("HIGH_GATE_blake3_binding") | Some("HIGH_GATE_lattice")
        ) {
            high_gate.push(id.clone());
        }
    }
    high_gate.sort();
    let mut want_high = catalog.summary.high_gate_flagged.clone();
    want_high.sort();

    assert_eq!(
        catalog.summary.total_queries,
        catalog.queries.len(),
        "summary.total_queries disagrees with the row count"
    );
    assert_eq!(catalog.summary.covered, covered, "summary.covered mismatch");
    assert_eq!(catalog.summary.partial, partial, "summary.partial mismatch");
    assert_eq!(catalog.summary.gaps, gaps, "summary.gaps mismatch");
    assert_eq!(
        want_high, high_gate,
        "summary.high_gate_flagged disagrees with the flagged rows"
    );
}

/// Sanity: the catalog spans the full SPARQL 1.1 feature surface the §6 design
/// requires — including EVERY property-path modifier — and is honest about which
/// the fragment gate accepts. After the fragment-gate extension (sq-3kd2g.6) the
/// bounded closures `?`/`+`/`*` are `covered` under an existence-only bounded
/// statement (flagged `bounded`), while constructs the gate rejects fail-closed
/// (OPTIONAL, aggregates, BIND, negation) stay honest GAPs. Guards against a
/// future edit silently dropping a feature row or misstating its status (the
/// value of the catalog is its COMPLETENESS and its honesty vs the gate).
#[test]
fn catalog_spans_required_features() {
    let (_snapshot, catalog) = load();

    // Every property-path modifier in the design must have a row.
    for id in [
        "Q13_path_sequence",     // /
        "Q14_path_inverse",      // ^
        "Q15_path_alternative",  // |
        "Q16_path_zero_or_one",  // ?
        "Q17_path_one_or_more",  // +
        "Q18_path_zero_or_more", // *
    ] {
        assert!(
            catalog.queries.contains_key(id),
            "missing property-path row {id} — the catalog must cover every path modifier"
        );
    }

    // The UNBOUNDED-depth closures `+`/`*` are now ACCEPTED by the extended
    // fragment gate (fragment_query) and dispatch to the bounded
    // `path_reach_d{d}_k{k}_n{n}` family (sq-3kd2g.6, opt-in `extended-fragment`).
    // They are covered ONLY in the BOUNDED, existence-only sense (design §4: the
    // depth bound is a public input) — so each must be `covered`, carry the
    // `bounded` honesty flag, and name only `path_reach_*` members joined from the
    // regression-gated snapshot. Their closures have NO fixed depth
    // (`PathClosure::{OneOrMore,ZeroOrMore}.fixed_k() == None`), so any compiled
    // `d>=2` member satisfies the dispatcher. This is the anti-drift guard for the
    // flip side of §1's Q13/Q14 finding: a closure must never be labelled a flat
    // unbounded `covered`, nor left a stale GAP now that the gate accepts it.
    for id in ["Q17_path_one_or_more", "Q18_path_zero_or_more"] {
        let q = &catalog.queries[id];
        assert!(
            q.is_covered(),
            "{id}: bounded path closure is accepted by the fragment gate and maps to \
             the path_reach family — must be `covered` (bounded), not a stale GAP"
        );
        assert!(
            q.bounded,
            "{id}: a path closure is covered ONLY under the bounded existence-only \
             statement (design §4) — must carry the `bounded` honesty flag so it is \
             never read as an unbounded-closure claim"
        );
        assert!(
            !q.zk_members.is_empty()
                && q.zk_members.iter().all(|m| m.starts_with("path_reach_")),
            "{id}: bounded path closure must name only path_reach_* members, found {:?}",
            q.zk_members
        );
    }

    // `p?` (Q16, ZeroOrOne) is a FIXED-depth closure: the dispatcher pins it to
    // depth bound 1 (`PathClosure::ZeroOrOne.fixed_k() == 1`) and rejects any bound
    // member whose `d != 1` (`FragmentDispatchError::PathDepthExceedsClosure`) so a
    // deeper chain cannot masquerade as `p?`. Every compiled `path_reach` member is
    // `d>=2` — there is NO `d=1` member — so an accepted `p?` query can bind none of
    // them and it is NOT covered today. It stays an honest GAP until a `d=1` member
    // is compiled and snapshotted. The invariant this pins: `p?` may be marked
    // covered ONLY if it names a `path_reach_d1_*` member (guarding against a
    // regression that re-lists the deeper members and re-claims coverage).
    {
        let q = &catalog.queries["Q16_path_zero_or_one"];
        if q.is_covered() {
            assert!(
                q.zk_members.iter().any(|m| m.starts_with("path_reach_d1_")),
                "Q16 (p?) is a fixed depth-1 closure: it may be `covered` only when it \
                 names a d=1 member (path_reach_d1_*), else the dispatcher rejects every \
                 listed member as PathDepthExceedsClosure. Found {:?}",
                q.zk_members
            );
        } else {
            assert!(
                q.is_gap() && q.zk_members.is_empty(),
                "Q16 (p?): with no compiled d=1 member it must be an honest GAP with no \
                 listed members, found status/members {:?}",
                q.zk_members
            );
        }
    }

    // The constructs the gate REJECTS fail-closed (OUT-by-design or not-yet-built)
    // must stay honest GAPs — never fabricated as covered/partial.
    for id in [
        "Q10_optional",              // non-monotone (closed-world) — OUT
        "Q19_aggregate_group_by",    // pattern-level completeness — OUT
        "Q21_bind_expression",       // expression estate — phase 3
        "Q23_negation_minus_notexists", // closed-world negation — OUT
    ] {
        assert!(
            catalog.queries[id].is_gap(),
            "{id}: rejected fail-closed by the fragment gate — must be an honest GAP"
        );
    }

    // The complex-FILTER datatype lanes must all be present and covered.
    for id in [
        "Q03_filter_integer_ge",
        "Q04_filter_signed_integer_ge",
        "Q05_filter_decimal_le",
        "Q06_filter_double_gt",
    ] {
        assert!(
            catalog.queries[id].is_covered(),
            "{id}: numeric FILTER lane must be covered"
        );
    }

    // The four blake3-bound numeric-FILTER lanes are the value-hook reduction
    // target — all flagged HIGH_GATE_blake3_binding.
    for id in [
        "Q03_filter_integer_ge",
        "Q04_filter_signed_integer_ge",
        "Q05_filter_decimal_le",
        "Q06_filter_double_gt",
    ] {
        assert_eq!(
            catalog.queries[id].flag.as_deref(),
            Some("HIGH_GATE_blake3_binding"),
            "{id}: numeric FILTER lane must be flagged as the value-hook reduction target"
        );
    }

    // Every query carries a non-empty SPARQL snippet (it is a query catalog).
    for (id, q) in &catalog.queries {
        assert!(!q.sparql.trim().is_empty(), "{id}: empty SPARQL");
    }
}
