//! [OPUS-4.8] sq-d3d8 (epic sq-3183): OPT-IN federation discovery descriptors.
//!
//! Two read-only RDF documents that make a `sparq-server` instance a *discoverable*
//! federation node:
//!
//!   * **VoID** (`GET /.well-known/void`) — a [W3C VoID](https://www.w3.org/TR/void/)
//!     description of the served dataset (triple/entity/class/property counts +
//!     class/property partitions), generated by [`sparq_introspect::Introspection::to_void`].
//!   * **SPARQL Service Description** (a `GET` on the SPARQL endpoint with **no `query`
//!     parameter**, per [SPARQL 1.1 Protocol §2.1.2 / Service Description
//!     §2](https://www.w3.org/TR/sparql11-service-description/)) — an `sd:Service`
//!     advertising the endpoint URL, the supported SPARQL query languages, the supported
//!     result formats, and the default dataset (linked to the VoID document).
//!
//! ## OPT-IN — feature `federation-descriptors` AND a config flag, both OFF by default
//!
//! This whole module is compiled only behind the `federation-descriptors` cargo feature.
//! Even with the feature on, the endpoints are served only when
//! [`ServerConfig::federation_descriptors`](crate::ServerConfig::federation_descriptors) is
//! `true` (CLI `--federation-descriptors` / env `SPARQ_FEDERATION_DESCRIPTORS=1`). With the
//! feature ON but the flag OFF (the default even when compiled in):
//!
//!   * `GET /.well-known/void` returns `404` (the route is mounted but the handler refuses);
//!   * a `GET /sparql` with no `query` returns the historical `400 missing 'query'`.
//!
//! So discovery is never exposed unless an operator deliberately turns it on, and a build
//! without the feature pays *zero* cost — no `sparq-introspect` dependency, no new routes,
//! byte-identical to before. `sparq-core` / `sparq-engine` are untouched: the descriptor
//! generation reads a pinned snapshot `&Graph` through the existing public introspection API.
//!
//! ## Cost
//!
//! Generating the VoID/SD scans the snapshot (the same cost as a `?s ?p ?o` dump plus the
//! per-class/predicate aggregation [`Introspection::build`] already does). It is therefore a
//! request-time scan, not amortised — appropriate for an occasionally-polled discovery
//! endpoint, and another reason it is opt-in rather than always-on.

use oxrdf::Triple;

use sparq_core::Graph;
use sparq_introspect::Introspection;

use crate::negotiate::{negotiate_graph, GraphFormat};

/// `sd:` — the SPARQL 1.1 Service Description vocabulary namespace.
const SD_NS: &str = "http://www.w3.org/ns/sparql-service-description#";
/// `void:` — the VoID vocabulary namespace (the dataset the SD links to).
const VOID_NS: &str = "http://rdfs.org/ns/void#";
/// `dcterms:` — used for the `dcterms:source` link from the SD to the VoID document.
const DCTERMS_NS: &str = "http://purl.org/dc/terms/";
const RDF_TYPE: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";

/// The W3C IRIs for the SPARQL query languages the engine accepts (advertised via
/// `sd:supportedLanguage`). The engine evaluates SPARQL 1.1 Query; UPDATE is also supported
/// on the protocol's write path, so both are advertised.
const SD_LANGUAGES: &[&str] = &[
    "http://www.w3.org/ns/sparql-service-description#SPARQL11Query",
    "http://www.w3.org/ns/sparql-service-description#SPARQL11Update",
];

/// The W3C media-type IRIs (`<https://www.w3.org/ns/formats/...>`) for the result/RDF
/// serialisations the server can return, advertised via `sd:resultFormat`. These mirror the
/// formats [`crate::negotiate`] produces (SELECT/ASK results + CONSTRUCT/DESCRIBE graphs).
const SD_RESULT_FORMATS: &[&str] = &[
    // SPARQL results
    "http://www.w3.org/ns/formats/SPARQL_Results_JSON",
    "http://www.w3.org/ns/formats/SPARQL_Results_XML",
    "http://www.w3.org/ns/formats/SPARQL_Results_CSV",
    "http://www.w3.org/ns/formats/SPARQL_Results_TSV",
    // RDF graph serialisations (CONSTRUCT / DESCRIBE / GSP read)
    "http://www.w3.org/ns/formats/Turtle",
    "http://www.w3.org/ns/formats/N-Triples",
    "http://www.w3.org/ns/formats/RDF_XML",
];

/// A negotiated descriptor response: the serialised body plus its `Content-Type`.
pub struct Descriptor {
    pub content_type: &'static str,
    pub body: String,
}

/// Negotiates the RDF serialisation for a descriptor from the request `Accept` header.
///
/// Reuses the same Turtle / N-Triples / RDF-XML negotiation as the GSP-read + CONSTRUCT
/// surface ([`negotiate_graph`]), but with a Turtle default (the conventional, most readable
/// descriptor serialisation) rather than N-Triples — a bare `curl` of a `.well-known/void`
/// should land on Turtle.
fn negotiate_descriptor(accept: Option<&str>) -> GraphFormat {
    match accept {
        // A non-empty Accept that names at least one concrete media type → honour the
        // client's preference via the shared graph negotiation.
        Some(a) if !a.trim().is_empty() && !is_wildcard_only(a) => negotiate_graph(Some(a)),
        // Empty / absent / wildcard-only Accept → Turtle (the readable default for a human
        // or a generic discovery client hitting the well-known URL).
        _ => GraphFormat::Turtle,
    }
}

/// `true` when every media range in the `Accept` header is the `*/*` catch-all (so the
/// client expressed no concrete preference). Handles q-values and multiple ranges, e.g.
/// `*/*`, `*/*;q=0.8`, `*/* , */*;q=0.1` — all wildcard-only. A single concrete type
/// anywhere (e.g. `text/turtle, */*`) makes it non-wildcard so the client preference wins.
fn is_wildcard_only(accept: &str) -> bool {
    accept.split(',').filter(|r| !r.trim().is_empty()).all(|range| {
        // Strip parameters (`;q=…`, `;charset=…`) and compare the media range itself.
        range.split(';').next().unwrap_or("").trim() == "*/*"
    })
}

/// Serialises a triple list in the negotiated [`GraphFormat`], reusing the crate's graph
/// serialisers (the same writers the GSP-read path uses), so the descriptor is guaranteed
/// well-formed in whichever syntax is chosen.
fn serialise(triples: &[Triple], fmt: GraphFormat) -> (&'static str, String) {
    let body = match fmt {
        GraphFormat::NTriples => crate::graph::triples_to_ntriples(triples),
        GraphFormat::Turtle => crate::graph::triples_to_turtle(triples),
        GraphFormat::RdfXml => crate::graph::triples_to_rdfxml(triples),
    };
    (fmt.content_type(), body)
}

/// Parses an N-Triples document (the output of [`Introspection::to_void`] / [`sd_ntriples`])
/// into an [`oxrdf::Triple`] vector so it can be re-serialised in the negotiated syntax.
///
/// The inputs are machine-generated, well-formed N-Triples (oxrdf `Display` per term), so a
/// parse error here is a programming error, not a client-facing one — we surface it as an
/// internal error rather than silently dropping triples.
fn parse_ntriples(nt: &str) -> Result<Vec<Triple>, String> {
    let mut out = Vec::new();
    for r in oxttl::NTriplesParser::new().for_slice(nt.as_bytes()) {
        out.push(r.map_err(|e| format!("internal: malformed descriptor N-Triples: {e}"))?);
    }
    Ok(out)
}

/// Builds the VoID descriptor for `graph`, named `dataset_iri`, serialised per `accept`.
///
/// `dataset_iri` is the IRI that names the `void:Dataset` (conventionally the dataset's URL,
/// e.g. `https://host/.well-known/void#dataset`). Generation delegates to
/// [`Introspection::to_void_with_cs`] — the standard VoID counts + class/property partitions,
/// **plus** the characteristic-set source statistics (the sparq `scs:` extension; see
/// [`Introspection::to_void_with_cs`] / sq-mr32, federation A3/Z2). The CS stats ride the
/// same opt-in `federation-descriptors` gating as the rest of this module: a federation
/// client polling `/.well-known/void` on a CS-aware sparq node gets per-entity-type predicate
/// co-occurrence + multiplicity for sharp star/multi-join source selection, while a
/// VoID-only client reads the unchanged standard partitions and ignores the rest. The only
/// work here is re-serialising into the negotiated syntax.
pub fn void_descriptor(
    graph: &Graph,
    dataset_iri: &str,
    accept: Option<&str>,
) -> Result<Descriptor, String> {
    let nt = Introspection::build(graph).to_void_with_cs(dataset_iri);
    let triples = parse_ntriples(&nt)?;
    let fmt = negotiate_descriptor(accept);
    let (content_type, body) = serialise(&triples, fmt);
    Ok(Descriptor { content_type, body })
}

/// Builds the SPARQL Service Description for the endpoint, serialised per `accept`.
///
/// * `service_iri` names the `sd:Service` (conventionally the endpoint URL, e.g.
///   `https://host/sparql`).
/// * `endpoint_iri` is the `sd:endpoint` value (the same endpoint URL).
/// * `dataset_iri` is the `void:Dataset` the default graph exposes — linked both as the
///   `sd:defaultDataset`'s `sd:defaultGraph` (typed as a `void:Dataset`) and via
///   `dcterms:source` to the VoID document, so a federation client can discover counts from
///   one descriptor and the capability profile from the other.
///
/// The SD advertises: the endpoint, `sd:Service` typing, the supported query languages
/// ([`SD_LANGUAGES`]), the supported result formats ([`SD_RESULT_FORMATS`]), and the default
/// dataset/graph linked to the VoID dataset IRI.
pub fn service_description(
    service_iri: &str,
    endpoint_iri: &str,
    dataset_iri: &str,
    accept: Option<&str>,
) -> Result<Descriptor, String> {
    let nt = sd_ntriples(service_iri, endpoint_iri, dataset_iri);
    let triples = parse_ntriples(&nt)?;
    let fmt = negotiate_descriptor(accept);
    let (content_type, body) = serialise(&triples, fmt);
    Ok(Descriptor { content_type, body })
}

/// Renders the Service Description as N-Triples (the syntactic subset every serialiser can
/// re-emit). Hand-written rather than via a builder dependency — the SD is a small fixed
/// shape, so a few `writeln!`s keep it dependency-free and auditable.
fn sd_ntriples(service_iri: &str, endpoint_iri: &str, dataset_iri: &str) -> String {
    use std::fmt::Write as _;
    let sd = |local: &str| format!("{SD_NS}{local}");
    // oxrdf NamedNode Display is N-Triples-safe (escapes/brackets correctly). Use the
    // CHECKED constructor: `service_iri`/`endpoint_iri`/`dataset_iri` are ultimately
    // derived from the request `Host` header, and although the HTTP layer now validates
    // the base IRI, we defend in depth here so an invalid IRI can never emit malformed
    // N-Triples (which would fail re-parse → a 500). An invalid value falls back to a
    // fixed safe IRI rather than corrupting the document.
    const SAFE_IRI: &str = "http://localhost/invalid-iri";
    let iri = |s: &str| {
        oxrdf::NamedNode::new(s)
            .unwrap_or_else(|_| oxrdf::NamedNode::new_unchecked(SAFE_IRI))
            .to_string()
    };

    let svc = iri(service_iri);
    let mut out = String::new();

    // ---- The sd:Service: typing, endpoint, supported languages, supported result formats.
    let _ = writeln!(out, "{svc} <{RDF_TYPE}> <{}> .", sd("Service"));
    let _ = writeln!(out, "{svc} <{}> {} .", sd("endpoint"), iri(endpoint_iri));
    for lang in SD_LANGUAGES {
        let _ = writeln!(out, "{svc} <{}> {} .", sd("supportedLanguage"), iri(lang));
    }
    for f in SD_RESULT_FORMATS {
        let _ = writeln!(out, "{svc} <{}> {} .", sd("resultFormat"), iri(f));
    }

    // ---- The default dataset (a blank node) → default graph → the VoID dataset.
    let ds = "_:dataset";
    let g = "_:defaultGraph";
    let _ = writeln!(out, "{svc} <{}> {ds} .", sd("defaultDataset"));
    let _ = writeln!(out, "{ds} <{RDF_TYPE}> <{}> .", sd("Dataset"));
    let _ = writeln!(out, "{ds} <{}> {g} .", sd("defaultGraph"));
    let _ = writeln!(out, "{g} <{RDF_TYPE}> <{}> .", sd("Graph"));
    // Also type the default graph as a void:Dataset (the descriptor that carries counts),
    // and add a dcterms:source pointer from the service to the VoID document.
    let _ = writeln!(out, "{g} <{RDF_TYPE}> <{VOID_NS}Dataset> .");
    let _ = writeln!(out, "{svc} <{DCTERMS_NS}source> {} .", iri(dataset_iri));

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn graph() -> Graph {
        Graph::load_str(
            "@prefix ex: <http://ex/> .\n\
             ex:alice a ex:Person ; ex:knows ex:bob .\n\
             ex:bob a ex:Person .\n",
            "turtle",
        )
        .unwrap()
    }

    #[test]
    fn void_turtle_carries_triples_count() {
        let d = void_descriptor(
            &graph(),
            "http://host/.well-known/void#dataset",
            Some("text/turtle"),
        )
        .unwrap();
        assert_eq!(d.content_type, "text/turtle; charset=utf-8");
        assert!(
            d.body.contains("triples"),
            "VoID must carry void:triples: {}",
            d.body
        );
        // The raw VoID N-Triples carries the void:triples predicate.
        let nt = Introspection::build(&graph()).to_void("http://host/.well-known/void#dataset");
        assert!(nt.contains("<http://rdfs.org/ns/void#triples>"));
    }

    #[test]
    fn void_descriptor_carries_characteristic_set_stats() {
        // [OPUS-4.8] sq-mr32 (federation A3/Z2): the served VoID must now also carry the
        // characteristic-set source statistics (sparq `scs:` extension), in valid RDF.
        // N-Triples first (exact predicate IRIs), then Turtle (must re-parse).
        let nt = void_descriptor(
            &graph(),
            "http://host/.well-known/void#dataset",
            Some("application/n-triples"),
        )
        .unwrap();
        let b = &nt.body;
        // Standard VoID is still present (CS rides ALONGSIDE, never replaces it).
        assert!(b.contains("<http://rdfs.org/ns/void#Dataset>"), "{b}");
        // Dataset links to characteristic sets + carries the EXACT distinct-set count.
        assert!(
            b.contains("<http://sparq.dev/ns/cs#characteristicSet>"),
            "served VoID must link the dataset to characteristic sets: {b}"
        );
        assert!(
            b.contains("<http://sparq.dev/ns/cs#distinctCharacteristicSets>"),
            "served VoID must carry the distinct-set count: {b}"
        );
        // A CS node: typed, with subjects + per-predicate stat nodes (property + triples
        // + avg multiplicity).
        assert!(
            b.contains("<http://sparq.dev/ns/cs#CharacteristicSet>"),
            "{b}"
        );
        assert!(b.contains("<http://sparq.dev/ns/cs#subjects>"), "{b}");
        assert!(b.contains("<http://sparq.dev/ns/cs#predicateStat>"), "{b}");
        assert!(
            b.contains("<http://sparq.dev/ns/cs#avgMultiplicity>"),
            "{b}"
        );
        // Per-predicate stat reuses void:property/void:triples and names a real predicate.
        assert!(b.contains("<http://rdfs.org/ns/void#property>"), "{b}");
        assert!(
            b.contains("<http://ex/knows>"),
            "CS stat must name the predicate: {b}"
        );

        // Turtle serialisation of the same document must be well-formed RDF and still
        // carry the CS extension namespace.
        let tt = void_descriptor(&graph(), "http://host/ds", Some("text/turtle")).unwrap();
        assert_eq!(tt.content_type, "text/turtle; charset=utf-8");
        let mut n = 0usize;
        for r in oxttl::TurtleParser::new().for_slice(tt.body.as_bytes()) {
            r.expect("VoID+CS Turtle must be valid RDF");
            n += 1;
        }
        assert!(n >= 10, "VoID+CS should have many triples, got {n}");
        assert!(
            tt.body.contains("sparq.dev/ns/cs#"),
            "Turtle VoID must carry the CS extension vocab: {}",
            tt.body
        );
    }

    #[test]
    fn void_ntriples_negotiated() {
        let d = void_descriptor(&graph(), "http://host/ds", Some("application/n-triples")).unwrap();
        assert_eq!(d.content_type, "application/n-triples; charset=utf-8");
        assert!(d.body.contains("<http://rdfs.org/ns/void#Dataset>"));
    }

    #[test]
    fn void_default_is_turtle() {
        // No Accept (None), empty, and any WILDCARD-ONLY Accept (incl. q-values and
        // multiple wildcard ranges) all default to Turtle — not just the literal "*/*".
        for accept in [
            None,
            Some("*/*"),
            Some(""),
            Some("*/*;q=0.8"),
            Some(" */* , */*;q=0.1 "),
        ] {
            let d = void_descriptor(&graph(), "http://host/ds", accept).unwrap();
            assert_eq!(
                d.content_type, "text/turtle; charset=utf-8",
                "accept={accept:?}"
            );
        }
        // A concrete type alongside a wildcard still honours the concrete preference.
        let d = void_descriptor(&graph(), "http://host/ds", Some("application/n-triples, */*"))
            .unwrap();
        assert_eq!(d.content_type, "application/n-triples; charset=utf-8");
    }

    #[test]
    fn sd_invalid_iri_falls_back_not_500() {
        // A bad (header-derived) IRI must not produce malformed N-Triples that fail the
        // re-parse → a 500. The checked constructor swaps it for a safe IRI instead, so
        // the descriptor still builds and re-parses cleanly.
        let d = service_description(
            "http://bad host/sparql", // space ⇒ invalid IRI
            "http://bad host/sparql",
            "http://host/ds",
            Some("application/n-triples"),
        )
        .expect("invalid Host-derived IRI must fall back, not error/500");
        assert_eq!(d.content_type, "application/n-triples; charset=utf-8");
        assert!(
            d.body.contains("/invalid-iri"),
            "invalid IRI should be replaced by the safe fallback: {}",
            d.body
        );
    }

    #[test]
    fn sd_advertises_endpoint_languages_formats() {
        let d = service_description(
            "http://host/sparql",
            "http://host/sparql",
            "http://host/.well-known/void#dataset",
            Some("application/n-triples"),
        )
        .unwrap();
        assert_eq!(d.content_type, "application/n-triples; charset=utf-8");
        let b = &d.body;
        // sd:Service typing + endpoint.
        assert!(b.contains("<http://www.w3.org/ns/sparql-service-description#Service>"));
        assert!(b.contains("<http://www.w3.org/ns/sparql-service-description#endpoint>"));
        assert!(b.contains("<http://host/sparql>"));
        // supportedLanguage SPARQL11Query.
        assert!(b.contains("SPARQL11Query"));
        // a result format.
        assert!(b.contains("SPARQL_Results_JSON"));
        assert!(b.contains("/formats/Turtle"));
        // defaultDataset link + dcterms:source to the VoID document.
        assert!(b.contains("#defaultDataset"));
        assert!(b.contains("<http://purl.org/dc/terms/source>"));
        assert!(b.contains("<http://host/.well-known/void#dataset>"));
    }

    #[test]
    fn sd_reparses_as_turtle() {
        // Turtle serialisation must be well-formed (round-trips through oxttl).
        let d = service_description(
            "http://host/sparql",
            "http://host/sparql",
            "http://host/ds",
            Some("text/turtle"),
        )
        .unwrap();
        assert_eq!(d.content_type, "text/turtle; charset=utf-8");
        let mut n = 0;
        for r in oxttl::TurtleParser::new().for_slice(d.body.as_bytes()) {
            r.expect("SD Turtle must be valid");
            n += 1;
        }
        assert!(n >= 3, "SD should have several triples, got {n}");
    }
}
