//! [`ObjectModel`] → Rust source: the "how does that read as Rust" half.
//!
//! [FABLE-5] (sq-1rg2q.12) The emitted module is **dependency-free**: it defines
//! its own `Triple`-shaped input view and needs nothing but `std`, so it drops
//! into any crate (and compiles standalone with a bare `rustc`) without dragging
//! the RDF stack behind it. Feed it triples from `sparq-core`, `sparq-wrapper`,
//! or anything else.
//!
//! Emission is a pure function of the IR, and the IR is totally ordered, so
//! `emit(&lower(&m)?)` is byte-identical across runs.

use crate::schema::{
    Cardinality, ClassMarker, Field, ModelType, ObjectModel, RustScalar, ValueType,
};

/// The fixed header of every generated module: the `Triple` input view, the
/// `LoadError` type, the typed-reference machinery and the loader helpers.
const PRELUDE: &str = r#"// @generated by sparq-wrapper-shacl from a SHACL shapes graph. Do not edit.
//
// This module is a typed READER, not a SHACL validator. Only the structural
// constraints — sh:path, sh:minCount/sh:maxCount, sh:datatype, sh:class,
// sh:node and sh:closed — are represented here; every other component
// (sh:pattern, sh:minInclusive, sh:in, sh:or, sh:qualifiedValueShape,
// sh:sparql, ...) is NOT enforced by this code. Validate with a real SHACL
// processor before trusting a graph.
//
// sh:datatype is checked in BOTH the ways SHACL requires: the literal's
// datatype IRI must be one the field accepts, AND the lexical form must be
// well formed for it. Well-formedness is enforced for the XSD boolean,
// floating-point, decimal and integer families, value range included — so
// "not-an-integer"^^xsd:integer and "128"^^xsd:byte are both rejected. Every
// other datatype (xsd:string, xsd:anyURI, the date/time family,
// rdf:langString, anything outside the XSD namespace) has NO lexical check
// here: its form is taken as given. See lexical_space_ok.
//
// Two further limits are deliberate, not oversights:
//   * `sh:class` is checked against DIRECT `rdf:type` triples only. This code
//     has no rdfs:subClassOf closure, so a value typed only as a SUBCLASS of
//     the required class is rejected here but conforms under SHACL.
//   * Nesting is bounded by MAX_NESTING_DEPTH; cyclic data yields
//     LoadError::DepthExceeded rather than recursing forever.
#![allow(dead_code)]

use std::fmt;

/// The deepest `sh:node` nesting a loader will follow before giving up.
pub const MAX_NESTING_DEPTH: u32 = 32;

const RDF_TYPE: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";

const XSD: &str = "http://www.w3.org/2001/XMLSchema#";

/// Whether a triple's object is a node (IRI or blank node) or a literal.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ObjectKind<'a> {
    /// An IRI or blank-node object; `Triple::object` is its identifier.
    Node,
    /// A literal object; `Triple::object` is its lexical form.
    Literal {
        /// The literal's datatype IRI.
        datatype: &'a str,
    },
}

/// One input triple. Subjects and node objects are identifiers (an IRI, or a
/// blank-node label); literal objects carry their lexical form plus datatype.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Triple<'a> {
    /// The subject identifier.
    pub subject: &'a str,
    /// The predicate IRI.
    pub predicate: &'a str,
    /// The object identifier or lexical form.
    pub object: &'a str,
    /// What kind of object it is.
    pub object_kind: ObjectKind<'a>,
}

impl<'a> Triple<'a> {
    /// A triple whose object is an IRI or blank node.
    pub fn node(subject: &'a str, predicate: &'a str, object: &'a str) -> Self {
        Self { subject, predicate, object, object_kind: ObjectKind::Node }
    }

    /// A triple whose object is a literal with the given datatype IRI.
    pub fn literal(subject: &'a str, predicate: &'a str, lexical: &'a str, datatype: &'a str) -> Self {
        Self { subject, predicate, object: lexical, object_kind: ObjectKind::Literal { datatype } }
    }
}

/// An unconstrained value: whatever the triple carried.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Value {
    /// An IRI or blank-node object.
    Node(String),
    /// A literal object.
    Literal {
        /// The lexical form.
        lexical: String,
        /// The datatype IRI.
        datatype: String,
    },
}

/// The class set a typed reference is checked against.
pub trait ClassMarker {
    /// The acceptable `rdf:type` IRIs; a value matching ANY of them conforms.
    const CLASS_IRIS: &'static [&'static str];
}

/// A reference to a node whose class was checked against `M`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Ref<M: ClassMarker> {
    iri: String,
    marker: std::marker::PhantomData<M>,
}

impl<M: ClassMarker> Ref<M> {
    /// The referenced node's identifier.
    pub fn iri(&self) -> &str {
        &self.iri
    }

    /// The class IRIs this reference was checked against.
    pub fn class_iris() -> &'static [&'static str] {
        M::CLASS_IRIS
    }
}

/// Why a graph could not be read into a generated type.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum LoadError {
    /// A closed shape's subject carries a predicate outside its whitelist.
    ClosedShapeViolation {
        /// The shape that is closed.
        shape: &'static str,
        /// The offending subject.
        subject: String,
        /// The predicate that is not allowed.
        predicate: String,
    },
    /// A required field had no value.
    MissingRequired {
        /// The shape being loaded.
        shape: &'static str,
        /// The field's predicate IRI.
        predicate: &'static str,
    },
    /// Fewer values than `sh:minCount` allows.
    TooFewValues {
        /// The shape being loaded.
        shape: &'static str,
        /// The field's predicate IRI.
        predicate: &'static str,
        /// The required minimum.
        min: u64,
        /// How many values were found.
        found: usize,
    },
    /// More values than `sh:maxCount` allows.
    TooManyValues {
        /// The shape being loaded.
        shape: &'static str,
        /// The field's predicate IRI.
        predicate: &'static str,
        /// The permitted maximum.
        max: u64,
        /// How many values were found.
        found: usize,
    },
    /// A `sh:datatype` field had a node object.
    ExpectedLiteral {
        /// The shape being loaded.
        shape: &'static str,
        /// The field's predicate IRI.
        predicate: &'static str,
        /// The offending object.
        object: String,
    },
    /// A `sh:class` / `sh:node` field had a literal object.
    ExpectedNode {
        /// The shape being loaded.
        shape: &'static str,
        /// The field's predicate IRI.
        predicate: &'static str,
        /// The offending object.
        object: String,
    },
    /// A literal's datatype is outside the field's `sh:datatype` set.
    DatatypeMismatch {
        /// The shape being loaded.
        shape: &'static str,
        /// The field's predicate IRI.
        predicate: &'static str,
        /// The accepted datatype IRIs.
        expected: &'static [&'static str],
        /// The datatype that was found.
        found: String,
    },
    /// A literal's lexical form is not well formed for its datatype, or does
    /// not parse into the field's Rust scalar.
    LexicalForm {
        /// The shape being loaded.
        shape: &'static str,
        /// The field's predicate IRI.
        predicate: &'static str,
        /// The lexical form that was rejected.
        value: String,
        /// What it was checked against: the datatype IRI whose lexical space
        /// rejected it, or the Rust type it would not parse into.
        expected: &'static str,
    },
    /// A referenced node carries no accepted `rdf:type`.
    ClassMismatch {
        /// The shape being loaded.
        shape: &'static str,
        /// The field's predicate IRI.
        predicate: &'static str,
        /// The referenced node.
        subject: String,
        /// The accepted class IRIs.
        expected: &'static [&'static str],
    },
    /// Nesting ran past `MAX_NESTING_DEPTH` (cyclic or pathological data).
    DepthExceeded {
        /// The shape at which the limit was hit.
        shape: &'static str,
    },
}

impl fmt::Display for LoadError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::ClosedShapeViolation { shape, subject, predicate } => write!(
                f,
                "{shape}: closed shape forbids <{predicate}> on {subject}"
            ),
            Self::MissingRequired { shape, predicate } => {
                write!(f, "{shape}: required <{predicate}> has no value")
            }
            Self::TooFewValues { shape, predicate, min, found } => write!(
                f,
                "{shape}: <{predicate}> needs at least {min} values, found {found}"
            ),
            Self::TooManyValues { shape, predicate, max, found } => write!(
                f,
                "{shape}: <{predicate}> allows at most {max} values, found {found}"
            ),
            Self::ExpectedLiteral { shape, predicate, object } => {
                write!(f, "{shape}: <{predicate}> expects a literal, found {object}")
            }
            Self::ExpectedNode { shape, predicate, object } => {
                write!(f, "{shape}: <{predicate}> expects a node, found literal {object:?}")
            }
            Self::DatatypeMismatch { shape, predicate, expected, found } => write!(
                f,
                "{shape}: <{predicate}> expects datatype one of {expected:?}, found <{found}>"
            ),
            Self::LexicalForm { shape, predicate, value, expected } => write!(
                f,
                "{shape}: <{predicate}> value {value:?} does not parse as {expected}"
            ),
            Self::ClassMismatch { shape, predicate, subject, expected } => write!(
                f,
                "{shape}: <{predicate}> value {subject} has no rdf:type in {expected:?}"
            ),
            Self::DepthExceeded { shape } => {
                write!(f, "{shape}: nesting exceeded MAX_NESTING_DEPTH")
            }
        }
    }
}

impl std::error::Error for LoadError {}

/// Every object of `(subject, predicate)`, in input order.
fn objects<'a>(subject: &str, predicate: &str, triples: &[Triple<'a>]) -> Vec<Triple<'a>> {
    triples
        .iter()
        .filter(|t| t.subject == subject && t.predicate == predicate)
        .copied()
        .collect()
}

fn check_count(
    shape: &'static str,
    predicate: &'static str,
    found: usize,
    min: Option<u64>,
    max: Option<u64>,
) -> Result<(), LoadError> {
    if let Some(min) = min {
        if (found as u64) < min {
            return Err(LoadError::TooFewValues { shape, predicate, min, found });
        }
    }
    if let Some(max) = max {
        if (found as u64) > max {
            return Err(LoadError::TooManyValues { shape, predicate, max, found });
        }
    }
    Ok(())
}

/// Rejects any predicate on `subject` outside a closed shape's whitelist.
fn check_closed(
    shape: &'static str,
    subject: &str,
    allowed: &'static [&'static str],
    triples: &[Triple<'_>],
) -> Result<(), LoadError> {
    for t in triples.iter().filter(|t| t.subject == subject) {
        if !allowed.contains(&t.predicate) {
            return Err(LoadError::ClosedShapeViolation {
                shape,
                subject: subject.to_string(),
                predicate: t.predicate.to_string(),
            });
        }
    }
    Ok(())
}

/// The literal's lexical form, after checking its datatype is accepted AND its
/// lexical form is well formed for that datatype.
fn lexical<'a>(
    shape: &'static str,
    predicate: &'static str,
    t: &Triple<'a>,
    datatypes: &'static [&'static str],
) -> Result<&'a str, LoadError> {
    let ObjectKind::Literal { datatype } = t.object_kind else {
        return Err(LoadError::ExpectedLiteral {
            shape,
            predicate,
            object: t.object.to_string(),
        });
    };
    // Keep the matched `&'static str`, not the borrowed one, so the error can
    // name the datatype whose lexical space rejected the value.
    let Some(accepted) = datatypes.iter().copied().find(|d| *d == datatype) else {
        return Err(LoadError::DatatypeMismatch {
            shape,
            predicate,
            expected: datatypes,
            found: datatype.to_string(),
        });
    };
    if lexical_space_ok(accepted, t.object) {
        Ok(t.object)
    } else {
        Err(LoadError::LexicalForm {
            shape,
            predicate,
            value: t.object.to_string(),
            expected: accepted,
        })
    }
}

/// Whether `raw` is well formed for `datatype`.
///
/// SHACL's sh:datatype constraint requires a value node to be a literal of the
/// datatype AND to be well formed, so a matching datatype IRI is not enough:
/// "not-an-integer"^^xsd:integer must be rejected. Checked here are the XSD
/// boolean, floating-point, decimal and integer families — the integer family
/// including each datatype's VALUE range, so "2147483648"^^xsd:int and
/// "128"^^xsd:byte are rejected too. Any other datatype has no mechanical check
/// and is accepted as given; see the module header.
fn lexical_space_ok(datatype: &str, raw: &str) -> bool {
    let Some(local) = datatype.strip_prefix(XSD) else {
        return true;
    };
    if let Some((min, max)) = integer_range(local) {
        return integer_in_range(raw, min, max);
    }
    match local {
        // xsd:boolean has four lexical forms, not two.
        "boolean" => matches!(raw, "true" | "false" | "1" | "0"),
        "decimal" => is_decimal(raw),
        "float" | "double" => parse_float(raw).is_some(),
        _ => true,
    }
}

/// The `(min, max)` value space of an XSD integer datatype, in `i128` — wide
/// enough for `xsd:long` and `xsd:unsignedLong` alike. `None` on a side means
/// that side is unbounded, so an arbitrarily long lexical form is in range.
/// Returns `None` for a datatype outside the integer family.
fn integer_range(local: &str) -> Option<(Option<i128>, Option<i128>)> {
    Some(match local {
        "integer" => (None, None),
        "nonPositiveInteger" => (None, Some(0)),
        "negativeInteger" => (None, Some(-1)),
        "nonNegativeInteger" => (Some(0), None),
        "positiveInteger" => (Some(1), None),
        "long" => (Some(i64::MIN as i128), Some(i64::MAX as i128)),
        "int" => (Some(-2_147_483_648), Some(2_147_483_647)),
        "short" => (Some(-32_768), Some(32_767)),
        "byte" => (Some(-128), Some(127)),
        "unsignedLong" => (Some(0), Some(u64::MAX as i128)),
        "unsignedInt" => (Some(0), Some(4_294_967_295)),
        "unsignedShort" => (Some(0), Some(65_535)),
        "unsignedByte" => (Some(0), Some(255)),
        _ => return None,
    })
}

/// The integer lexical space — an optional sign then at least one digit, with
/// leading zeros permitted — plus the datatype's value range.
fn integer_in_range(raw: &str, min: Option<i128>, max: Option<i128>) -> bool {
    let (negative, digits) = match raw.strip_prefix('-') {
        Some(rest) => (true, rest),
        None => (false, raw.strip_prefix('+').unwrap_or(raw)),
    };
    if digits.is_empty() || !digits.bytes().all(|b| b.is_ascii_digit()) {
        return false;
    }
    match raw.parse::<i128>() {
        Ok(v) => min.is_none_or(|m| v >= m) && max.is_none_or(|m| v <= m),
        // Well formed but too many digits for i128: only an unbounded side can
        // still accept it, and the sign says which side is under pressure.
        Err(_) if negative => min.is_none(),
        Err(_) => max.is_none(),
    }
}

/// The xsd:decimal lexical space: an optional sign, then digits with an
/// optional fractional part, and NO exponent (that is xsd:double).
fn is_decimal(raw: &str) -> bool {
    let body = raw.strip_prefix(|c| c == '-' || c == '+').unwrap_or(raw);
    let (int, frac) = body.split_once('.').unwrap_or((body, ""));
    !(int.is_empty() && frac.is_empty())
        && int.bytes().all(|b| b.is_ascii_digit())
        && frac.bytes().all(|b| b.is_ascii_digit())
}

fn scalar_string(
    shape: &'static str,
    predicate: &'static str,
    t: &Triple<'_>,
    datatypes: &'static [&'static str],
) -> Result<String, LoadError> {
    lexical(shape, predicate, t, datatypes).map(str::to_string)
}

fn scalar_bool(
    shape: &'static str,
    predicate: &'static str,
    t: &Triple<'_>,
    datatypes: &'static [&'static str],
) -> Result<bool, LoadError> {
    match lexical(shape, predicate, t, datatypes)? {
        "true" | "1" => Ok(true),
        "false" | "0" => Ok(false),
        other => Err(LoadError::LexicalForm {
            shape,
            predicate,
            value: other.to_string(),
            expected: "bool",
        }),
    }
}

fn scalar_i64(
    shape: &'static str,
    predicate: &'static str,
    t: &Triple<'_>,
    datatypes: &'static [&'static str],
) -> Result<i64, LoadError> {
    // `lexical` has already rejected anything outside the datatype's value
    // range, and only datatypes whose range fits i64 reach here, so this parse
    // cannot fail for a value that got this far — it stays as a safety net for
    // a hand-edited copy of this module.
    let raw = lexical(shape, predicate, t, datatypes)?;
    raw.parse::<i64>().map_err(|_| LoadError::LexicalForm {
        shape,
        predicate,
        value: raw.to_string(),
        expected: "i64",
    })
}

fn scalar_f32(
    shape: &'static str,
    predicate: &'static str,
    t: &Triple<'_>,
    datatypes: &'static [&'static str],
) -> Result<f32, LoadError> {
    let raw = lexical(shape, predicate, t, datatypes)?;
    parse_float(raw).map(|v| v as f32).ok_or(LoadError::LexicalForm {
        shape,
        predicate,
        value: raw.to_string(),
        expected: "f32",
    })
}

fn scalar_f64(
    shape: &'static str,
    predicate: &'static str,
    t: &Triple<'_>,
    datatypes: &'static [&'static str],
) -> Result<f64, LoadError> {
    let raw = lexical(shape, predicate, t, datatypes)?;
    parse_float(raw).ok_or(LoadError::LexicalForm {
        shape,
        predicate,
        value: raw.to_string(),
        expected: "f64",
    })
}

/// XSD spells the specials `INF` / `-INF` / `NaN`; Rust spells them `inf` /
/// `-inf` / `NaN`, and would also accept `infinity`, which XSD does not.
fn parse_float(raw: &str) -> Option<f64> {
    match raw {
        "INF" | "+INF" => Some(f64::INFINITY),
        "-INF" => Some(f64::NEG_INFINITY),
        "NaN" => Some(f64::NAN),
        _ if raw.eq_ignore_ascii_case("inf")
            || raw.eq_ignore_ascii_case("infinity")
            || raw.eq_ignore_ascii_case("nan") =>
        {
            None
        }
        _ => raw.parse::<f64>().ok(),
    }
}

/// The object's node identifier, rejecting a literal.
fn node_iri(
    shape: &'static str,
    predicate: &'static str,
    t: &Triple<'_>,
) -> Result<String, LoadError> {
    match t.object_kind {
        ObjectKind::Node => Ok(t.object.to_string()),
        ObjectKind::Literal { .. } => Err(LoadError::ExpectedNode {
            shape,
            predicate,
            object: t.object.to_string(),
        }),
    }
}

/// DIRECT `rdf:type` membership — see the module header on subclass closure.
fn check_class(
    shape: &'static str,
    predicate: &'static str,
    subject: &str,
    expected: &'static [&'static str],
    triples: &[Triple<'_>],
) -> Result<(), LoadError> {
    let typed = triples.iter().any(|t| {
        t.subject == subject
            && t.predicate == RDF_TYPE
            && t.object_kind == ObjectKind::Node
            && expected.contains(&t.object)
    });
    if typed {
        Ok(())
    } else {
        Err(LoadError::ClassMismatch {
            shape,
            predicate,
            subject: subject.to_string(),
            expected,
        })
    }
}

fn reference<M: ClassMarker>(
    shape: &'static str,
    predicate: &'static str,
    t: &Triple<'_>,
    triples: &[Triple<'_>],
) -> Result<Ref<M>, LoadError> {
    let iri = node_iri(shape, predicate, t)?;
    check_class(shape, predicate, &iri, M::CLASS_IRIS, triples)?;
    Ok(Ref { iri, marker: std::marker::PhantomData })
}

fn value_of(t: &Triple<'_>) -> Value {
    match t.object_kind {
        ObjectKind::Node => Value::Node(t.object.to_string()),
        ObjectKind::Literal { datatype } => Value::Literal {
            lexical: t.object.to_string(),
            datatype: datatype.to_string(),
        },
    }
}
"#;

/// Renders an object model as a standalone Rust module.
///
/// The result is a complete module body: write it to `<name>.rs` and pull it in
/// with `mod <name>;`. It is deterministic — the same [`ObjectModel`] always
/// produces the same bytes.
#[must_use]
pub fn emit(model: &ObjectModel) -> String {
    let mut out = String::with_capacity(PRELUDE.len() + 1024 * model.types.len());
    out.push_str(PRELUDE);
    for marker in &model.class_markers {
        emit_marker(&mut out, marker);
    }
    for ty in &model.types {
        emit_type(&mut out, ty);
    }
    out
}

fn emit_marker(out: &mut String, marker: &ClassMarker) {
    out.push_str(&format!(
        "\n/// Class marker for {}.\n\
         #[derive(Clone, Copy, Debug, PartialEq, Eq)]\n\
         pub struct {};\n\n\
         impl ClassMarker for {} {{\n    \
         const CLASS_IRIS: &'static [&'static str] = &[{}];\n\
         }}\n",
        marker
            .classes
            .iter()
            .map(|c| format!("`<{c}>`"))
            .collect::<Vec<_>>()
            .join(", "),
        marker.name,
        marker.name,
        str_slice(&marker.classes),
    ));
}

fn emit_type(out: &mut String, ty: &ModelType) {
    out.push_str(&format!(
        "\n/// Generated from the node shape {}.\n#[derive(Clone, Debug, PartialEq)]\npub struct {} {{\n",
        ty.shape, ty.name
    ));
    for field in &ty.fields {
        out.push_str(&format!(
            "    /// `<{}>`{}\n    pub {}: {},\n",
            field.predicate,
            cardinality_note(field),
            field.name,
            field_type(field)
        ));
    }
    out.push_str("}\n");

    out.push_str(&format!("\nimpl {} {{\n", ty.name));
    out.push_str(&format!(
        "    /// The shapes-graph node this type was generated from.\n    pub const SHAPE: &'static str = {};\n",
        lit(&ty.shape)
    ));
    out.push_str(&format!(
        "\n    /// `sh:targetClass` IRIs declared by the shape.\n    pub const TARGET_CLASSES: &'static [&'static str] = &[{}];\n",
        str_slice(&ty.target_classes)
    ));
    if let Some(allowed) = &ty.closed {
        out.push_str(&format!(
            "\n    /// The `sh:closed` predicate whitelist: a conforming subject may carry\n    \
             /// no other predicate.\n    pub const ALLOWED_PREDICATES: &'static [&'static str] = &[{}];\n",
            str_slice(allowed)
        ));
    }

    let uses_graph = ty.closed.is_some() || !ty.fields.is_empty();
    let uses_depth = ty
        .fields
        .iter()
        .any(|f| matches!(f.value, ValueType::Nested { .. }));

    out.push_str(&format!(
        "\n    /// Reads `subject` out of `triples`.\n    ///\n    \
         /// # Errors\n    ///\n    /// Returns the first [`LoadError`] the subject's triples\n    \
         /// violate; see the module header for what is and is not checked.\n    \
         pub fn load(subject: &str, triples: &[Triple<'_>]) -> Result<Self, LoadError> {{\n        \
         Self::load_at(subject, triples, 0)\n    }}\n"
    ));

    out.push_str(&format!(
        "\n    fn load_at({}: &str, {}: &[Triple<'_>], {}: u32) -> Result<Self, LoadError> {{\n",
        param("subject", uses_graph),
        param("triples", uses_graph),
        param("depth", uses_depth),
    ));
    if uses_depth {
        out.push_str(
            "        if depth >= MAX_NESTING_DEPTH {\n            \
             return Err(LoadError::DepthExceeded { shape: Self::SHAPE });\n        }\n",
        );
    }
    if ty.closed.is_some() {
        out.push_str(
            "        check_closed(Self::SHAPE, subject, Self::ALLOWED_PREDICATES, triples)?;\n",
        );
    }
    for field in &ty.fields {
        emit_field_load(out, field);
    }
    out.push_str("        Ok(Self {");
    if ty.fields.is_empty() {
        out.push_str("})\n");
    } else {
        out.push('\n');
        for field in &ty.fields {
            out.push_str(&format!("            {},\n", field.name));
        }
        out.push_str("        })\n");
    }
    out.push_str("    }\n}\n");
}

/// Emits the `let <field> = …;` block that reads one field.
fn emit_field_load(out: &mut String, field: &Field) {
    let p = lit(&field.predicate);
    out.push_str(&format!(
        "        let __objects = objects(subject, {p}, triples);\n"
    ));
    match field.cardinality {
        Cardinality::Optional => {
            out.push_str(&format!(
                "        check_count(Self::SHAPE, {p}, __objects.len(), None, Some(1))?;\n\
                 \x20       let {name} = match __objects.first() {{\n            \
                 Some(t) => Some({expr}),\n            None => None,\n        }};\n",
                name = field.name,
                expr = value_expr(field, boxed(field)),
            ));
        }
        Cardinality::Required => {
            out.push_str(&format!(
                "        check_count(Self::SHAPE, {p}, __objects.len(), Some(1), Some(1))?;\n\
                 \x20       let {name} = {{\n            \
                 let t = __objects.first().ok_or(LoadError::MissingRequired {{\n                \
                 shape: Self::SHAPE,\n                predicate: {p},\n            }})?;\n            \
                 {expr}\n        }};\n",
                name = field.name,
                expr = value_expr(field, boxed(field)),
            ));
        }
        Cardinality::Many { min, max } => {
            out.push_str(&format!(
                "        check_count(Self::SHAPE, {p}, __objects.len(), {min}, {max})?;\n\
                 \x20       let mut {name} = Vec::with_capacity(__objects.len());\n        \
                 for t in &__objects {{\n            {name}.push({expr});\n        }}\n",
                min = opt_u64(min),
                max = opt_u64(max),
                name = field.name,
                expr = value_expr(field, false),
            ));
        }
    }
}

/// The expression producing ONE value of `field` from a `t: &Triple<'_>`.
fn value_expr(field: &Field, boxed: bool) -> String {
    let p = lit(&field.predicate);
    let inner = match &field.value {
        ValueType::Scalar(s) => format!(
            "{}(Self::SHAPE, {p}, t, &[{}])?",
            match s.rust {
                RustScalar::String => "scalar_string",
                RustScalar::Bool => "scalar_bool",
                RustScalar::I64 => "scalar_i64",
                RustScalar::F32 => "scalar_f32",
                RustScalar::F64 => "scalar_f64",
            },
            str_slice(&s.datatypes),
        ),
        ValueType::Reference(marker) => {
            format!("reference::<{marker}>(Self::SHAPE, {p}, t, triples)?")
        }
        ValueType::Nested {
            type_name,
            class_marker,
        } => {
            let class_check = match class_marker {
                Some(m) => format!(
                    "\n                check_class(Self::SHAPE, {p}, &__iri, {m}::CLASS_IRIS, triples)?;"
                ),
                None => String::new(),
            };
            format!(
                "{{\n                let __iri = node_iri(Self::SHAPE, {p}, t)?;{class_check}\n                \
                 {type_name}::load_at(&__iri, triples, depth + 1)?\n            }}"
            )
        }
        ValueType::Term => "value_of(t)".to_string(),
    };
    if boxed {
        format!("Box::new({inner})")
    } else {
        inner
    }
}

/// A `sh:node` value is boxed at cardinality 0..1 / 1..1 so a shape that
/// (transitively) nests itself still has a finite Rust type. `Vec` already
/// provides the indirection.
fn boxed(field: &Field) -> bool {
    matches!(field.value, ValueType::Nested { .. })
        && !matches!(field.cardinality, Cardinality::Many { .. })
}

fn field_type(field: &Field) -> String {
    let base = match &field.value {
        ValueType::Scalar(s) => s.rust.rust_type().to_string(),
        ValueType::Reference(marker) => format!("Ref<{marker}>"),
        ValueType::Nested { type_name, .. } => type_name.clone(),
        ValueType::Term => "Value".to_string(),
    };
    let base = if boxed(field) {
        format!("Box<{base}>")
    } else {
        base
    };
    match field.cardinality {
        Cardinality::Optional => format!("Option<{base}>"),
        Cardinality::Required => base,
        Cardinality::Many { .. } => format!("Vec<{base}>"),
    }
}

fn cardinality_note(field: &Field) -> String {
    match field.cardinality {
        Cardinality::Optional => " — `sh:maxCount 1`.".to_string(),
        Cardinality::Required => " — `sh:minCount 1`, `sh:maxCount 1`.".to_string(),
        Cardinality::Many { min, max } => match (min, max) {
            (None, None) => " — unconstrained cardinality.".to_string(),
            (Some(min), None) => format!(" — `sh:minCount {min}`."),
            (None, Some(max)) => format!(" — `sh:maxCount {max}`."),
            (Some(min), Some(max)) => format!(" — `sh:minCount {min}`, `sh:maxCount {max}`."),
        },
    }
}

fn param(name: &str, used: bool) -> String {
    if used {
        name.to_string()
    } else {
        format!("_{name}")
    }
}

fn opt_u64(v: Option<u64>) -> String {
    match v {
        Some(n) => format!("Some({n})"),
        None => "None".to_string(),
    }
}

fn str_slice(items: &[String]) -> String {
    items
        .iter()
        .map(|s| lit(s))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Renders `s` as a Rust string literal.
fn lit(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 || c as u32 == 0x7f => {
                out.push_str(&format!("\\u{{{:x}}}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn string_literals_are_escaped() {
        assert_eq!(lit("http://a/b"), "\"http://a/b\"");
        assert_eq!(lit("a\"b\\c"), "\"a\\\"b\\\\c\"");
        assert_eq!(lit("a\u{1}b"), "\"a\\u{1}b\"");
    }

    #[test]
    fn an_empty_model_still_emits_the_prelude() {
        let src = emit(&ObjectModel::default());
        assert_eq!(src, PRELUDE);
        assert!(src.contains("pub enum LoadError"));
    }
}
