//! Poseidon2 Noir cross-test: PROVES the Rust implementation is
//! bit-compatible with the Noir stack the circuits will use.
//!
//! Vectors were generated by `nargo execute` (nargo 1.0.0-beta.21) on the
//! fixture package `tests/fixtures/noir_poseidon2/` (noir-lang/poseidon
//! v0.3.0; `std::hash::poseidon2_permutation` is the bn254 blackbox), and
//! are hardcoded here so the gate is deterministic. When `nargo` is on PATH
//! the test ALSO re-runs the fixture and cross-checks the live output, so a
//! toolchain bump that changed hashing semantics fails loudly instead of
//! silently invalidating every recorded commitment.

use sparq_zk::field::{field_from_hex_str, field_to_hex, Fr};
use sparq_zk::poseidon2;

/// `nargo execute` println output of the fixture, in order.
const NOIR_PERMUTATION_11_22_33_44: [&str; 4] = [
    "0x23b773bfa90b7f060c909da636d36b721aafc18fb4ce10aa91fc814297d6e3de",
    "0x2002a3f683a0d5fd347321687df45ef51ef753f81e952183edf4e724791ae9d9",
    "0x27bb3ef6f59a58b458bb3f72370d5e20e0473fcc1ec062032e0ad2827a8ef7fc",
    "0x2486f45dd81c5dd990e879f5f711ed8ef69d0bc8d0b8528c5498bb8584de13da",
];

const NOIR_HASHES: [(&[u64], &str); 5] = [
    (
        &[1],
        "0x168758332d5b3e2d13be8048c8011b454590e06c44bce7f702f09103eef5a373",
    ),
    (
        &[1, 2],
        "0x038682aa1cb5ae4e0a3f13da432a95c77c5c111f6f030faf9cad641ce1ed7383",
    ),
    (
        &[1, 2, 3],
        "0x23864adb160dddf590f1d3303683ebcb914f828e2635f6e85a32f0a1aecd3dd8",
    ),
    (
        &[1, 2, 3, 4],
        "0x130bf204a32cac1f0ace56c78b731aa3809f06df2731ebcf6b3464a15788b1b9",
    ),
    (
        &[5, 6, 7, 8, 9, 10, 11],
        "0x0ceb49bb97a406f119fcceb666e68b0acb48c286d9e011a4fa9427cd49989db5",
    ),
];

const NOIR_HASH_40_LEAVES: &str =
    "0x046964eee810ddedae9085f126317d43ad22b719fedfba0a78a1de86795dffee";

#[test]
fn permutation_matches_noir_blackbox() {
    let input = [
        Fr::from(11u64),
        Fr::from(22u64),
        Fr::from(33u64),
        Fr::from(44u64),
    ];
    let out = poseidon2::permutation(&input);
    for (got, expected) in out.iter().zip(NOIR_PERMUTATION_11_22_33_44) {
        assert_eq!(field_to_hex(got), expected);
    }
}

#[test]
fn sponge_hash_matches_noir_poseidon_library() {
    for (input, expected) in NOIR_HASHES {
        let fields: Vec<Fr> = input.iter().map(|&x| Fr::from(x)).collect();
        assert_eq!(
            field_to_hex(&poseidon2::hash(&fields)),
            expected,
            "input {input:?}"
        );
    }
    // Commitment-scale fold: 40 leaves (a credential-sized graph).
    let leaves: Vec<Fr> = (1..=40u64).map(Fr::from).collect();
    assert_eq!(field_to_hex(&poseidon2::hash(&leaves)), NOIR_HASH_40_LEAVES);
}

/// Live regeneration: if `nargo` is installed, re-execute the fixture and
/// assert its println output still equals the vectors above (and therefore
/// the Rust implementation). Fails on any drift; runs the static checks
/// only when nargo is absent (e.g. minimal CI).
#[test]
fn nargo_live_cross_check() {
    let fixture =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/noir_poseidon2");
    let out = match std::process::Command::new("nargo")
        .arg("execute")
        .current_dir(&fixture)
        .output()
    {
        Ok(o) => o,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            eprintln!("nargo not on PATH; live cross-check covered by the static vectors");
            return;
        }
        Err(e) => panic!("failed to spawn nargo: {e}"),
    };
    assert!(
        out.status.success(),
        "nargo execute failed:\n{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let stdout = String::from_utf8_lossy(&out.stdout);
    let mut lines = stdout
        .lines()
        .filter(|l| l.starts_with("0x") || l.starts_with('['));

    // Permutation line: `[0x…, 0x…, 0x…, 0x…]`.
    let perm_line = lines.next().expect("permutation output line");
    let perm: Vec<&str> = perm_line.trim_matches(['[', ']']).split(", ").collect();
    assert_eq!(
        perm,
        NOIR_PERMUTATION_11_22_33_44.to_vec(),
        "permutation drifted"
    );

    for (input, expected) in NOIR_HASHES {
        let line = lines.next().expect("hash output line");
        assert_eq!(line.trim(), expected, "noir hash of {input:?} drifted");
        // And the Rust side reproduces the LIVE value, not just the vendored one.
        let fields: Vec<Fr> = input.iter().map(|&x| Fr::from(x)).collect();
        assert_eq!(field_to_hex(&poseidon2::hash(&fields)), line.trim());
    }
    let line = lines.next().expect("40-leaf output line");
    assert_eq!(line.trim(), NOIR_HASH_40_LEAVES, "40-leaf fold drifted");
}

/// The encoding layer's hashes are plain sponge calls over field elements,
/// so the cross-vectors above transfer: spot-check that `h_2`/`h_3` layouts
/// used by `encode` are exactly 2- and 3-element sponge hashes.
#[test]
fn encode_layers_are_plain_sponge_calls() {
    let a = Fr::from(7u64);
    let b = Fr::from(9u64);
    let c = Fr::from(11u64);
    // h_2(a, b) and h_3(a, b, c) must be the same function the circuits call
    // (Poseidon2::hash with message_size 2 / 3) — no extra domain tags beyond
    // the library's own length-bearing IV.
    let h2 = poseidon2::hash(&[a, b]);
    let h3 = poseidon2::hash(&[a, b, c]);
    assert_ne!(h2, h3);
    // Padding-collision guard: hash([a,b]) != hash([a,b,0]) (length in IV).
    assert_ne!(h2, poseidon2::hash(&[a, b, Fr::from(0u64)]));
    // Sanity against a vendored vector to pin the layout.
    assert_eq!(
        field_to_hex(&poseidon2::hash(&[Fr::from(1u64), Fr::from(2u64)])),
        NOIR_HASHES[1].1
    );
    let _ = field_from_hex_str(NOIR_HASHES[0].1).unwrap();
}
