// [OPUS-5] sq-rsd3v.6 (#3265): owl:sameAs equality reasoning -- the host mirror
// of the in-circuit union-find canonicalisation gadget
// (`zk/compose/compose_core/src/sameas.nr`). Epic sq-rsd3v; parent #2616.
//! `owl:sameAs` canonicalisation: the union-find canon table, its witness
//! builder, and the host re-check that mirrors the in-circuit relation.
//!
//! # Why this is SEPARATE from [`crate::derivation`] (the whole point)
//! [`crate::derivation`] re-checks each RDFS rule's variable-sharing shape by
//! **term-encoding equality** — an encoding equality is a term IDENTITY. That
//! proxy is exact for RDFS and for the OWL-RL rules whose antecedents are
//! fixed-shape Datalog over ids, and it **breaks under equality reasoning**:
//! `owl:sameAs` quotients the term universe, so two syntactically distinct
//! terms may denote the same thing and term identity is strictly FINER than
//! entailment. Relaxing the equality test to "equal up to some claimed
//! `sameAs`" would TRUST the claimed equalities rather than prove them. The fix
//! is canonicalisation: prove a representative map, then run the ordinary
//! encoding-equality test over representatives.
//!
//! So `owl:sameAs` must NOT ride the fixed-shape path. Two things enforce that:
//! - this module, which is the equality path and is deliberately not reachable
//!   from [`crate::derivation::EntailmentRule`]; and
//! - [`crate::derivation::DerivationStep::mentions_equality_predicate`], wired
//!   into `verifier::bind_entailment`, which REFUSES fail-closed any derivation
//!   step that introduces or consumes an `owl:sameAs` fact.
//!
//! # The soundness argument (design record §3.5)
//! Write `~` for the equivalence relation on terms generated by the committed
//! `(a, owl:sameAs, b)` triples — exactly what OWL-RL's `eq-ref`/`eq-sym`/
//! `eq-trans` derive. [`CanonTable::check`] establishes, for a table that
//! passes:
//! - **L1** every active entry has `member ~ representative` (induction on the
//!   strictly-backwards parent chain; each tree edge is a committed `sameAs`
//!   triple, either orientation, so `eq-sym` covers the reverse);
//! - **L2** [`CanonTable::canon`] is class-preserving: `canon(t) ~ t` for every
//!   term (a term with no entry is its own representative — `eq-ref`);
//! - **L3** `canon` is idempotent (this is what the distinct-members rule is
//!   for; L1/L2 do not need it);
//! - **THEOREM** `canon(x) == canon(y)` implies `x ~ y`. So encoding equality
//!   OVER CANONICAL REPRESENTATIVES is a sound test for "the same thing under
//!   equality reasoning" — the property raw encoding equality lacks;
//! - **COROLLARY (representative-membership)** if a committed triple's three
//!   canonical representatives equal a row's, the row is entailed under
//!   OWL-RL `eq-rep-s`/`eq-rep-p`/`eq-rep-o` — this is
//!   [`CanonTable::entails_row`].
//!
//! # What is NOT claimed
//! - **Completeness is not claimed in either direction.** A prover may omit
//!   entries or edges, so `canon` is only a REFINEMENT of `~`. Under-merging
//!   costs provability, never soundness — a row this module cannot show
//!   entailed is not thereby shown non-entailed. Fixpoint saturation is
//!   `sq-rsd3v.7`, unbuilt.
//! - **Blank nodes.** Blank-node encodings are salt-dependent, so a `sameAs`
//!   edge touching a bnode is per-graph; the estate's cross-graph non-bnode
//!   (Q6) obligation is unchanged and NOT discharged here.
//! - **No cost claim.** The in-circuit gadget's cost has NOT been measured
//!   (`bb gates` has not been run over a compiled monomorphisation), and repo
//!   policy forbids an unmeasured figure.
//! - **Status.** Research-grade, NOT externally audited (`sq-qhy4`); the
//!   composition seam is the maintainer's own not-yet-sound position. This
//!   module is the host MIRROR + witness builder: no `ProofManifest` schema,
//!   `CircuitId`, or `verify_manifest` dispatch binds a `sameas` proof yet, and
//!   no compiled `sameas_k{K}_n{N}_u{U}` bin package exists.

use std::collections::{BTreeMap, BTreeSet, VecDeque};

use serde::{Deserialize, Serialize};

use crate::manifest::FieldHex;
use crate::verifier::normalize_hex;

/// The `owl:sameAs` IRI. Its term encoding is salt-independent (it is an IRI),
/// so the verifier recomputes it exactly as it recomputes the RDFS vocabulary
/// encodings — it is a PUBLIC constant, never a trusted schema edge.
pub const OWL_SAME_AS: &str = "http://www.w3.org/2002/07/owl#sameAs";

/// One entry of the union-find canon table: a term, its class representative,
/// and the index of the entry it was merged into (`parent == own index` marks a
/// class root). Mirrors the `(mem, rep, parent)` witness arrays of the
/// in-circuit `canon_table_check`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CanonEntry {
    /// The member term's encoding.
    pub member: FieldHex,
    /// The class representative's encoding.
    pub representative: FieldHex,
    /// Index of the entry this one was merged into; `== own index` for a root.
    pub parent: usize,
}

/// Why a canon table was rejected. Each variant mirrors one in-circuit assert
/// of `canon_table_check` / `sameas_entails_row`, so the host re-check and the
/// relation cannot drift apart.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CanonError {
    /// Two active entries carry the same member, so `canon` would be
    /// multi-valued (breaks idempotence — L3).
    DuplicateMember { entry: usize },
    /// A non-root's parent is not a STRICTLY earlier entry. Without this the
    /// forest could contain a cycle with no root and the induction behind L1
    /// would have no base case.
    ParentNotEarlier { entry: usize },
    /// A root does not represent itself.
    RootNotSelfRepresenting { entry: usize },
    /// A non-root's representative differs from its parent's, so the
    /// representative is not constant along the tree edge.
    RepresentativeBreak { entry: usize },
    /// A merge is not justified by a committed `owl:sameAs` triple in either
    /// orientation — the over-merge forgery ("claim `alice sameAs bob` and
    /// inherit bob's facts").
    UnjustifiedMerge { entry: usize },
}

impl std::fmt::Display for CanonError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CanonError::DuplicateMember { entry } => write!(
                f,
                "canon table entry {entry} re-enters a member already present (canon would be multi-valued)"
            ),
            CanonError::ParentNotEarlier { entry } => write!(
                f,
                "canon table entry {entry} has a parent that is not a strictly earlier entry (the forest must be well-founded)"
            ),
            CanonError::RootNotSelfRepresenting { entry } => write!(
                f,
                "canon table entry {entry} is a root but is not its own representative"
            ),
            CanonError::RepresentativeBreak { entry } => write!(
                f,
                "canon table entry {entry} disagrees with its parent's representative"
            ),
            CanonError::UnjustifiedMerge { entry } => write!(
                f,
                "canon table entry {entry} merges without a committed owl:sameAs triple justifying it (sq-rsd3v.6: an equality must be proved, never claimed)"
            ),
        }
    }
}

impl std::error::Error for CanonError {}

/// The witnessed union-find canon table — a spanning FOREST of the committed
/// `owl:sameAs` edge graph. Build one with [`CanonTable::from_committed_sameas`]
/// (the off-circuit witness generator), re-check it with [`CanonTable::check`]
/// (the mirror of the in-circuit relation), read representatives with
/// [`CanonTable::canon`].
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct CanonTable {
    /// Entries in an order where every non-root's parent appears STRICTLY
    /// earlier (breadth-first from each class root).
    pub entries: Vec<CanonEntry>,
}

impl CanonTable {
    /// Build the witness from the committed `owl:sameAs` edges: `edges[i]` is
    /// the `(subject, object)` pair of a committed `(s owl:sameAs o)` triple.
    ///
    /// The result is a breadth-first spanning forest — one class root per
    /// connected component, every other member carrying the index of the entry
    /// it was DISCOVERED FROM. That ordering is what makes each merge's
    /// justifying edge a real committed triple (a flat "everyone points at the
    /// root" star would not be: in a chain `a—b—c`, `(a sameAs c)` need not be
    /// committed). Self-edges (`a sameAs a`) contribute a root and nothing else.
    ///
    /// Iteration order is deterministic (terms are visited in sorted encoding
    /// order), so the same committed edges always yield the same witness.
    pub fn from_committed_sameas(edges: &[[FieldHex; 2]]) -> Self {
        // Adjacency over NORMALIZED encodings, plus the first-seen `FieldHex`
        // spelling for each so the witness round-trips the manifest's form.
        let mut adjacency: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
        let mut spelling: BTreeMap<String, FieldHex> = BTreeMap::new();
        for [a, b] in edges {
            let (ka, kb) = (normalize_hex(&a.0), normalize_hex(&b.0));
            spelling.entry(ka.clone()).or_insert_with(|| a.clone());
            spelling.entry(kb.clone()).or_insert_with(|| b.clone());
            adjacency.entry(ka.clone()).or_default();
            adjacency.entry(kb.clone()).or_default();
            if ka != kb {
                adjacency.entry(ka.clone()).or_default().insert(kb.clone());
                adjacency.entry(kb).or_default().insert(ka);
            }
        }

        let mut entries: Vec<CanonEntry> = Vec::new();
        let mut index_of: BTreeMap<String, usize> = BTreeMap::new();
        for root in adjacency.keys() {
            if index_of.contains_key(root) {
                continue;
            }
            let root_index = entries.len();
            let root_spelling = spelling[root].clone();
            index_of.insert(root.clone(), root_index);
            entries.push(CanonEntry {
                member: root_spelling.clone(),
                representative: root_spelling.clone(),
                parent: root_index,
            });
            let mut queue: VecDeque<String> = VecDeque::from([root.clone()]);
            while let Some(node) = queue.pop_front() {
                let node_index = index_of[&node];
                for neighbour in &adjacency[&node] {
                    if index_of.contains_key(neighbour) {
                        continue;
                    }
                    index_of.insert(neighbour.clone(), entries.len());
                    entries.push(CanonEntry {
                        member: spelling[neighbour].clone(),
                        representative: root_spelling.clone(),
                        parent: node_index,
                    });
                    queue.push_back(neighbour.clone());
                }
            }
        }
        CanonTable { entries }
    }

    /// The canonical representative of `term`: the representative of the unique
    /// entry whose member it is, else `term` itself (a term with no entry is
    /// its own class — OWL-RL `eq-ref`). Mirrors the in-circuit `canon_of`.
    ///
    /// Sound only for a table that has passed [`CanonTable::check`]: reading a
    /// table nobody checked establishes nothing.
    pub fn canon(&self, term: &FieldHex) -> FieldHex {
        let key = normalize_hex(&term.0);
        self.entries
            .iter()
            .find(|e| normalize_hex(&e.member.0) == key)
            .map(|e| e.representative.clone())
            .unwrap_or_else(|| term.clone())
    }

    /// Re-check the table against the committed triples — the host mirror of
    /// the in-circuit `canon_table_check`. `committed` is the set of triples of
    /// the committed graph(s) (term encodings, `[s, p, o]`); `sameas` is the
    /// `owl:sameAs` term encoding the verifier recomputed from [`OWL_SAME_AS`].
    ///
    /// Every merge must be JUSTIFIED by a committed `owl:sameAs` triple in
    /// either orientation; every representative must be constant along a tree
    /// edge; the parent chain must run strictly backwards; members must be
    /// distinct. A table that fails any of these is rejected fail-closed.
    pub fn check(&self, committed: &[[FieldHex; 3]], sameas: &FieldHex) -> Result<(), CanonError> {
        let triples: BTreeSet<[String; 3]> = committed
            .iter()
            .map(|t| {
                [
                    normalize_hex(&t[0].0),
                    normalize_hex(&t[1].0),
                    normalize_hex(&t[2].0),
                ]
            })
            .collect();
        let same = normalize_hex(&sameas.0);

        // Distinct members (L3's precondition), checked first.
        let mut seen: BTreeSet<String> = BTreeSet::new();
        for (i, entry) in self.entries.iter().enumerate() {
            if !seen.insert(normalize_hex(&entry.member.0)) {
                return Err(CanonError::DuplicateMember { entry: i });
            }
        }

        for (i, entry) in self.entries.iter().enumerate() {
            if entry.parent > i {
                return Err(CanonError::ParentNotEarlier { entry: i });
            }
            let member = normalize_hex(&entry.member.0);
            let representative = normalize_hex(&entry.representative.0);
            if entry.parent == i {
                // Root: represents itself, and has no edge to justify.
                if representative != member {
                    return Err(CanonError::RootNotSelfRepresenting { entry: i });
                }
                continue;
            }
            let parent = &self.entries[entry.parent];
            if representative != normalize_hex(&parent.representative.0) {
                return Err(CanonError::RepresentativeBreak { entry: i });
            }
            let parent_member = normalize_hex(&parent.member.0);
            let forward = [member.clone(), same.clone(), parent_member.clone()];
            let backward = [parent_member, same.clone(), member];
            if !triples.contains(&forward) && !triples.contains(&backward) {
                return Err(CanonError::UnjustifiedMerge { entry: i });
            }
        }
        Ok(())
    }

    /// Representative-membership: whether some committed triple's three
    /// canonical representatives equal `row`'s — the module-doc COROLLARY, and
    /// the mirror of the in-circuit `sameas_entails_row` step 3.
    ///
    /// TRUE means `row` is entailed by the committed triples under OWL-RL
    /// equality reasoning **for a table that has passed [`CanonTable::check`]**
    /// — call it first; this function does not re-check the table. FALSE means
    /// only "not shown entailed by THIS table" (completeness is not claimed).
    pub fn entails_row(&self, committed: &[[FieldHex; 3]], row: &[FieldHex; 3]) -> bool {
        let target: Vec<String> = row
            .iter()
            .map(|t| normalize_hex(&self.canon(t).0))
            .collect();
        committed.iter().any(|base| {
            base.iter()
                .zip(target.iter())
                .all(|(b, want)| normalize_hex(&self.canon(b).0) == *want)
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fh(s: &str) -> FieldHex {
        FieldHex(s.to_string())
    }

    const SAMEAS: &str = "0x41";
    const P: &str = "0x51"; // <worksAt>
    const O: &str = "0x61"; // <acme>
    const A: &str = "0xa1"; // <alice>
    const B: &str = "0xa2"; // <alice-2>, committed sameAs <alice>
    const C: &str = "0xa3"; // <alice-3>, committed sameAs <alice-2>
    const GHOST: &str = "0xff9"; // no committed sameAs edge

    /// { (A P O), (A sameAs B), (B sameAs C) } — so A ~ B ~ C and (C P O) is
    /// entailed from the hidden (A P O) under eq-rep-s.
    fn committed() -> Vec<[FieldHex; 3]> {
        vec![
            [fh(A), fh(P), fh(O)],
            [fh(A), fh(SAMEAS), fh(B)],
            [fh(B), fh(SAMEAS), fh(C)],
        ]
    }

    fn sameas_edges() -> Vec<[FieldHex; 2]> {
        vec![[fh(A), fh(B)], [fh(B), fh(C)]]
    }

    #[test]
    fn builder_emits_a_checkable_spanning_forest() {
        let table = CanonTable::from_committed_sameas(&sameas_edges());
        assert_eq!(table.entries.len(), 3);
        // Every non-root points STRICTLY backwards (the well-foundedness the
        // in-circuit relation asserts).
        for (i, e) in table.entries.iter().enumerate() {
            assert!(e.parent <= i, "entry {i} points forward");
        }
        table
            .check(&committed(), &fh(SAMEAS))
            .expect("honest witness must check");
    }

    #[test]
    fn builder_chains_rather_than_starring() {
        // The chain A—B—C must be emitted as a CHAIN: C's parent is B, not A.
        // A star would claim the merge (A sameAs C), which is NOT committed —
        // `check` would reject it, so this ordering is load-bearing.
        let table = CanonTable::from_committed_sameas(&sameas_edges());
        let c = table
            .entries
            .iter()
            .position(|e| normalize_hex(&e.member.0) == normalize_hex(C))
            .expect("C is a member");
        let b = table
            .entries
            .iter()
            .position(|e| normalize_hex(&e.member.0) == normalize_hex(B))
            .expect("B is a member");
        assert_eq!(table.entries[c].parent, b);
    }

    #[test]
    fn canon_maps_members_and_fixes_strangers() {
        let table = CanonTable::from_committed_sameas(&sameas_edges());
        let rep = table.canon(&fh(A));
        assert_eq!(normalize_hex(&table.canon(&fh(B)).0), normalize_hex(&rep.0));
        assert_eq!(normalize_hex(&table.canon(&fh(C)).0), normalize_hex(&rep.0));
        // Not a member: its own representative (eq-ref).
        assert_eq!(normalize_hex(&table.canon(&fh(P)).0), normalize_hex(P));
        assert_eq!(
            normalize_hex(&table.canon(&fh(GHOST)).0),
            normalize_hex(GHOST)
        );
        // Idempotence (L3).
        let once = table.canon(&fh(C));
        assert_eq!(normalize_hex(&table.canon(&once).0), normalize_hex(&once.0));
    }

    #[test]
    fn entails_row_accepts_the_rewritten_row() {
        let table = CanonTable::from_committed_sameas(&sameas_edges());
        table.check(&committed(), &fh(SAMEAS)).unwrap();
        // (C P O) is entailed from the hidden (A P O) across A ~ B ~ C.
        assert!(table.entails_row(&committed(), &[fh(C), fh(P), fh(O)]));
        // ... and so is the base row itself.
        assert!(table.entails_row(&committed(), &[fh(A), fh(P), fh(O)]));
    }

    #[test]
    fn entails_row_refuses_a_row_outside_the_class() {
        let table = CanonTable::from_committed_sameas(&sameas_edges());
        table.check(&committed(), &fh(SAMEAS)).unwrap();
        // GHOST has no entry, so canon(GHOST) = GHOST != canon(A).
        assert!(!table.entails_row(&committed(), &[fh(GHOST), fh(P), fh(O)]));
        // A different predicate is not licensed either.
        assert!(!table.entails_row(&committed(), &[fh(C), fh(GHOST), fh(O)]));
    }

    // FORGE (the core soundness regression — the OVER-MERGE): a table that
    // merges a fabricated term into A's class with NO committed sameAs triple
    // justifying it. Every other rule is satisfied (the parent is earlier, the
    // representative agrees), so only the committed-edge anchor can catch it.
    #[test]
    fn check_rejects_an_unjustified_merge() {
        let mut table = CanonTable::from_committed_sameas(&sameas_edges());
        let root = table.entries[0].representative.clone();
        table.entries.push(CanonEntry {
            member: fh(GHOST),
            representative: root,
            parent: 0,
        });
        assert_eq!(
            table.check(&committed(), &fh(SAMEAS)),
            Err(CanonError::UnjustifiedMerge { entry: 3 })
        );
        // And the forgery is exactly what would have licensed the false row.
        assert!(table.entails_row(&committed(), &[fh(GHOST), fh(P), fh(O)]));
    }

    #[test]
    fn check_rejects_a_representative_break() {
        let mut table = CanonTable::from_committed_sameas(&sameas_edges());
        table.entries[1].representative = table.entries[1].member.clone();
        assert_eq!(
            table.check(&committed(), &fh(SAMEAS)),
            Err(CanonError::RepresentativeBreak { entry: 1 })
        );
    }

    #[test]
    fn check_rejects_a_forward_parent() {
        let mut table = CanonTable::from_committed_sameas(&sameas_edges());
        table.entries[1].parent = 2;
        assert_eq!(
            table.check(&committed(), &fh(SAMEAS)),
            Err(CanonError::ParentNotEarlier { entry: 1 })
        );
    }

    #[test]
    fn check_rejects_a_non_self_representing_root() {
        let mut table = CanonTable::from_committed_sameas(&sameas_edges());
        table.entries[0].representative = fh(GHOST);
        assert_eq!(
            table.check(&committed(), &fh(SAMEAS)),
            Err(CanonError::RootNotSelfRepresenting { entry: 0 })
        );
    }

    #[test]
    fn check_rejects_a_duplicate_member() {
        let mut table = CanonTable::from_committed_sameas(&sameas_edges());
        let dup = table.entries[1].clone();
        table.entries.push(dup);
        assert_eq!(
            table.check(&committed(), &fh(SAMEAS)),
            Err(CanonError::DuplicateMember { entry: 3 })
        );
    }

    #[test]
    fn a_star_witness_over_a_chain_is_refused() {
        // The star a prover might be tempted to emit: C attached directly to
        // the root A. `(A sameAs C)` is NOT committed, so it is refused — this
        // is why the builder emits a BFS chain.
        let table = CanonTable {
            entries: vec![
                CanonEntry {
                    member: fh(A),
                    representative: fh(A),
                    parent: 0,
                },
                CanonEntry {
                    member: fh(B),
                    representative: fh(A),
                    parent: 0,
                },
                CanonEntry {
                    member: fh(C),
                    representative: fh(A),
                    parent: 0,
                },
            ],
        };
        assert_eq!(
            table.check(&committed(), &fh(SAMEAS)),
            Err(CanonError::UnjustifiedMerge { entry: 2 })
        );
    }

    #[test]
    fn merges_are_justified_in_either_orientation() {
        // owl:sameAs is symmetric (eq-sym): a witness whose tree edge runs
        // against the committed triple's direction is still justified.
        let committed_reverse = vec![[fh(B), fh(SAMEAS), fh(A)]];
        let table = CanonTable {
            entries: vec![
                CanonEntry {
                    member: fh(A),
                    representative: fh(A),
                    parent: 0,
                },
                CanonEntry {
                    member: fh(B),
                    representative: fh(A),
                    parent: 0,
                },
            ],
        };
        assert_eq!(table.check(&committed_reverse, &fh(SAMEAS)), Ok(()));
    }

    #[test]
    fn hex_spelling_does_not_change_the_verdict() {
        // Encodings round-trip through the manifest as `0x`-prefixed hex; the
        // re-check normalizes exactly as `bind_entailment` does, so an
        // upper-case / unprefixed spelling is the same term.
        let table = CanonTable {
            entries: vec![
                CanonEntry {
                    member: fh("0xA1"),
                    representative: fh("A1"),
                    parent: 0,
                },
                CanonEntry {
                    member: fh("A2"),
                    representative: fh("0xa1"),
                    parent: 0,
                },
            ],
        };
        assert_eq!(table.check(&committed(), &fh("41")), Ok(()));
        assert_eq!(normalize_hex(&table.canon(&fh("0xa2")).0), normalize_hex(A));
    }

    #[test]
    fn a_self_edge_contributes_only_a_root() {
        let table = CanonTable::from_committed_sameas(&[[fh(A), fh(A)]]);
        assert_eq!(table.entries.len(), 1);
        assert_eq!(table.entries[0].parent, 0);
        assert_eq!(
            table.check(&[[fh(A), fh(SAMEAS), fh(A)]], &fh(SAMEAS)),
            Ok(())
        );
    }
}
