//! [FABLE-5] sq-tonhr.6 drift check — pure-Rust, no Node in the loop:
//!
//! * the vendored grammar's SHA-256 must equal the pin recorded by
//!   `scripts/regen-shuttle-parsers.sh` at generation time, so editing
//!   `grammar/shaclc12ext.shuttle` without regenerating the artifacts (or
//!   regenerating without re-vendoring) turns the suite red;
//! * the checked-in artifacts must carry the generator's DO-NOT-EDIT header
//!   for this grammar (a hand-edited or foreign file fails).

use sha2::{Digest, Sha256};

const GRAMMAR: &str = include_str!("../grammar/shaclc12ext.shuttle");
const STRICT_RS: &str = include_str!("../src/raw/shaclc12.rs");
const EXT_RS: &str = include_str!("../src/raw/shaclc12ext.rs");

#[test]
fn vendored_grammar_matches_the_recorded_generation_pin() {
    let digest = Sha256::digest(GRAMMAR.as_bytes());
    let hex: String = digest.iter().map(|b| format!("{b:02x}")).collect();
    assert_eq!(
        hex,
        sparq_shaclc::provenance::GRAMMAR_SHA256,
        "grammar/shaclc12ext.shuttle drifted from the generation pin — run scripts/regen-shuttle-parsers.sh"
    );
}

#[test]
fn artifacts_carry_the_generator_header() {
    for (name, src) in [("shaclc12.rs", STRICT_RS), ("shaclc12ext.rs", EXT_RS)] {
        assert!(
            src.starts_with("//! GENERATED by @rdf-shuttle/gen-rs from shaclc12ext.shuttle"),
            "{name}: missing/foreign generator header — regenerate, do not hand-edit"
        );
        assert!(
            src.contains("DO NOT EDIT"),
            "{name}: DO-NOT-EDIT marker missing"
        );
    }
}

#[test]
fn provenance_pins_are_well_formed() {
    let p = sparq_shaclc::provenance::RDF_SHUTTLE_COMMIT;
    assert_eq!(p.len(), 40, "full commit hash expected");
    assert!(p.bytes().all(|b| b.is_ascii_hexdigit()));
    assert_eq!(sparq_shaclc::provenance::GRAMMAR_SHA256.len(), 64);
    assert_eq!(sparq_shaclc::provenance::REGEN_COMMANDS.len(), 2);
}
