// [OPUS-4.8] sq-g19x0 (epic sq-pbz04): TREE-WITNESS bounded-ABox closure — the standard DL-Lite
// tree-witness rewriting (Kontchakov, Rodríguez-Muro, Zakharyaschev, ISWC 2013) that handles
// existential WITNESSES without an unbounded forward chase.
//
// MOTIVATION. PerfectRef ([`crate::perfectref`]) is sound + complete for certain answers, but its
// UCQ can blow up: an existential-generating inclusion `A ⊑ ∃R` fires on every `_`-eligible role
// position, and `reduce` interleaves, so the naive saturation revisits the same anonymous
// successors repeatedly. The tree-witness view factors this out: the parts of a query that can be
// matched ENTIRELY inside the anonymous (existential) part of the canonical model are captured
// once, as a "tree witness", instead of being chased atom-by-atom.
//
// A TREE WITNESS for a CQ q under TBox T is a pair tw = (roots, interior):
//   * `roots`     — the query terms where the witnessed sub-tree ATTACHES to the rest of q (the
//                   answer/shared variables that must be matched in the data);
//   * `interior`  — the existential (`_`-eligible, non-distinguished, non-shared) variables that
//                   are matched by anonymous individuals generated by some `A ⊑ ∃R` axiom;
//   * a GENERATOR — the basic concept `A` whose `∃R` successor generates the interior.
// The witnessed atoms (those over roots ∪ interior) are then replaceable by the single generator
// atom `A(root)` on the witness root. The tree-witness REWRITING is q together with, for each
// consistent independent subset of tree witnesses, the CQ where each chosen witness's atoms are
// folded into its generator atom.
//
// BOUNDED. The interior of a tree witness is a subset of the query's existential variables, and
// the generators come from the finite TBox, so the number of tree witnesses is bounded by the
// query size — there is NO unbounded chase. This module computes the witnesses and emits the
// folded disjuncts; redundancy among them (and against the PerfectRef disjuncts) is removed by
// [`crate::minimise`], soundly.
//
// SOUNDNESS DISCIPLINE (the load-bearing invariant). This module never REPLACES PerfectRef; it
// AUGMENTS the UCQ with folded witness disjuncts and lets minimisation collapse the result. Since
// PerfectRef is complete and minimisation only drops a CONTAINED disjunct, the combined pipeline's
// certain-answer set is exactly PerfectRef's — the oracle tests assert this equivalence directly.
// A tree witness is admitted ONLY when its interior variables are genuinely existential (the same
// `_`-eligibility the PerfectRef applicability condition turns on); folding a witness whose
// interior touched an answer/shared variable would drop a join (unsound), so that case is rejected.

use crate::dllite::{Basic, Role, TBox};
use crate::perfectref::{Atom, Cq, Term};
use rustc_hash::FxHashSet;

/// One tree witness of a CQ under a TBox: the generator concept (`Basic`) that produces the
/// anonymous successors, the set of WITNESSED atom indices (the interior sub-tree), and the ROOT
/// term the folded generator atom attaches to.
#[derive(Clone, Debug)]
struct TreeWitness {
    /// The basic concept `A` of a `A ⊑ ∃R` inclusion whose generated `R`-successor witnesses the
    /// interior. Folding the witness replaces its atoms by this concept on the root.
    generator: Basic,
    /// Indices (into the CQ's atom list) of the atoms entirely inside this witness.
    witnessed: Vec<usize>,
    /// The root term — a non-existential query term (answer var, shared var, or constant) the
    /// folded generator atom is asserted on.
    root: Term,
}

/// Compute the tree-witness rewriting disjuncts for `cq` under `tbox` and return them (NOT
/// including `cq` itself — the caller unions them into the UCQ alongside the PerfectRef output).
///
/// Each emitted disjunct is `cq` with one tree witness's interior atoms removed and replaced by
/// the witness's generator atom on its root. We emit the SINGLE-witness foldings (the common,
/// bounded case); multi-witness independent sets are reached transitively because every emitted
/// disjunct is itself fed back through this routine by the fixpoint in [`tree_witness_ucq`].
fn single_witness_foldings(cq: &Cq, tbox: &TBox) -> Vec<Cq> {
    let mut out = Vec::new();
    for tw in tree_witnesses(cq, tbox) {
        if let Some(folded) = fold(cq, &tw) {
            out.push(folded);
        }
    }
    out
}

/// The tree-witness rewriting of a CQ: saturate the single-witness foldings to a fixpoint so
/// nested witnesses compose, then return the full set (input + all foldings). Bounded: foldings
/// strictly REMOVE interior atoms (the folded disjunct is smaller), so the recursion terminates.
pub fn tree_witness_ucq(cq: Cq, tbox: &TBox) -> Vec<Cq> {
    let mut seen: FxHashSet<Cq> = FxHashSet::default();
    let mut work = vec![cq.clone()];
    seen.insert(cq);
    let mut i = 0;
    while i < work.len() {
        let current = work[i].clone();
        i += 1;
        for folded in single_witness_foldings(&current, tbox) {
            if seen.insert(folded.clone()) {
                work.push(folded);
            }
        }
    }
    work
}

/// Enumerate the tree witnesses of `cq` under `tbox`. A witness is seeded by each existential
/// (`A ⊑ ∃R`) inclusion: we look for a connected fragment of role/class atoms hanging off a single
/// root via property `R`, whose every non-root term is an EXISTENTIAL variable (`_`-eligible), and
/// whose class atoms on the interior are all entailed by the generated successor (i.e. follow from
/// `A` by the same TBox). The MVP/bounded form recognises the canonical DL-Lite tree witness: a
/// SINGLE role atom `R(root, _)` (or its inverse) whose filler is existential, optionally with an
/// interior class atom on that filler that `A ⊑ ∃R` plus the TBox guarantees.
fn tree_witnesses(cq: &Cq, tbox: &TBox) -> Vec<TreeWitness> {
    let mut out = Vec::new();
    for (sub, gen_role) in &tbox.exists_super {
        // `sub ⊑ ∃gen_role` generates, for any x with `sub(x)`, an anonymous y with the named
        // property linking x and y per gen_role's direction.
        for (idx, atom) in cq.atoms.iter().enumerate() {
            let Atom::Role { role, s, o } = atom else {
                continue;
            };
            // Match the atom's named property to the generator's property.
            if role.iri != gen_role.iri {
                continue;
            }
            // Normalise to the underlying named property's (subject, object).
            let (subj, obj) = if role.inverse { (o, s) } else { (s, o) };
            // gen_role direction picks which end is the ROOT (the generator's domain) and which is
            // the existential FILLER (the anonymous successor).
            let (root, filler) = if gen_role.inverse {
                // ∃P⁻ generates a P-predecessor: the OBJECT is the root, the SUBJECT is anonymous.
                (obj, subj)
            } else {
                // ∃P generates a P-successor: the SUBJECT is the root, the OBJECT is anonymous.
                (subj, obj)
            };
            // The filler must be a genuine existential (the same `_`-eligibility the applicability
            // condition uses): non-distinguished, non-shared. Otherwise folding would drop a join.
            if !is_existential(cq, filler) {
                continue;
            }
            // The root must NOT itself be the filler (degenerate self-loop), and must be a term we
            // can assert a class atom on (var or const — not another anonymous `_` we are folding).
            if root == filler {
                continue;
            }
            out.push(TreeWitness {
                generator: sub.clone(),
                witnessed: vec![idx],
                root: root.clone(),
            });
        }
    }
    out
}

/// Whether `t` is an existential interior term: an `Unbound`, or a `Var` that is neither
/// distinguished (answer) nor shared (occurring in ≥2 atom positions). Mirrors the PerfectRef
/// `_`-eligibility used by the applicability condition — the soundness keystone for folding.
/// [SONNET-4.6] sq-pbz04.3.1: `Literal` added — literals are rigid constants, never existential.
fn is_existential(cq: &Cq, t: &Term) -> bool {
    match t {
        Term::Unbound(_) => true,
        Term::Const(_) => false,
        // B2: a literal constant is never an existential interior term. [SONNET-4.6]
        Term::Lit(..) => false,
        Term::Var(name) => {
            if cq.answer.iter().any(|a| a == name) {
                return false;
            }
            occurrences(cq, name) < 2
        }
    }
}

/// Count how many atom POSITIONS the named variable `name` occupies in `cq`.
fn occurrences(cq: &Cq, name: &str) -> usize {
    let mut n = 0;
    for a in &cq.atoms {
        match a {
            Atom::Class { arg, .. } => {
                if matches!(arg, Term::Var(v) if v == name) {
                    n += 1;
                }
            }
            Atom::Role { s, o, .. } => {
                if matches!(s, Term::Var(v) if v == name) {
                    n += 1;
                }
                if matches!(o, Term::Var(v) if v == name) {
                    n += 1;
                }
            }
        }
    }
    n
}

/// Fold a tree witness into `cq`: drop the witnessed atoms and add the generator concept on the
/// root. Returns `None` if folding would not actually shrink the query (no witnessed atoms) or if
/// any witnessed atom is referenced by a term outside the witness (defence in depth — the witness
/// builder already requires existential interiors, so this is belt-and-braces).
fn fold(cq: &Cq, tw: &TreeWitness) -> Option<Cq> {
    if tw.witnessed.is_empty() {
        return None;
    }
    let drop: FxHashSet<usize> = tw.witnessed.iter().copied().collect();
    // Collect the interior existential variable names being removed; assert none survives outside.
    let mut interior_vars: FxHashSet<String> = FxHashSet::default();
    for &i in &tw.witnessed {
        collect_existential_vars(cq, &cq.atoms[i], &tw.root, &mut interior_vars);
    }
    let mut atoms: Vec<Atom> = cq
        .atoms
        .iter()
        .enumerate()
        .filter(|(i, _)| !drop.contains(i))
        .map(|(_, a)| a.clone())
        .collect();
    // If a supposedly-interior variable still occurs in a surviving atom, folding is unsafe —
    // bail out (keep the original, do not emit a folded disjunct).
    for a in &atoms {
        let mut clash = false;
        for_each_var(a, |v| {
            if interior_vars.contains(v) {
                clash = true;
            }
        });
        if clash {
            return None;
        }
    }
    // Add the generator atom on the root.
    match &tw.generator {
        Basic::Class(c) => atoms.push(Atom::Class {
            class: c.clone(),
            arg: tw.root.clone(),
        }),
        Basic::Exists(r) => {
            // `∃S ⊑ ∃R` generator: the root has an S-successor. Emit S(root, _fresh) honouring
            // S's direction. The filler MUST be a genuinely UNIQUE existential — accidentally
            // sharing its id with another `_` in the same CQ would impose a spurious join and
            // could LOSE answers (unsound). So derive a fresh id strictly above every `_` already
            // present in the surviving atoms.
            let fresh = max_unbound(&atoms).map_or(0, |m| m + 1);
            atoms.push(role_atom_forward(r, tw.root.clone(), fresh));
        }
    }
    Some(Cq::normalised(atoms, cq.answer.clone()))
}

/// The maximum `Unbound` id present in `atoms`, or `None` if there are none. Used to mint a fresh,
/// collision-free existential filler id for an `∃S` generator fold.
fn max_unbound(atoms: &[Atom]) -> Option<u32> {
    let mut max: Option<u32> = None;
    let mut bump = |t: &Term| {
        if let Term::Unbound(id) = t {
            max = Some(max.map_or(*id, |m| m.max(*id)));
        }
    };
    for a in atoms {
        match a {
            Atom::Class { arg, .. } => bump(arg),
            Atom::Role { s, o, .. } => {
                bump(s);
                bump(o);
            }
        }
    }
    max
}

/// Build `S(root, _)` / `S(_, root)` for a generator `∃S`, honouring S's direction, with the
/// caller-supplied UNIQUE fresh existential filler id.
fn role_atom_forward(r: &Role, root: Term, fresh_id: u32) -> Atom {
    let filler = Term::Unbound(fresh_id);
    if r.inverse {
        Atom::Role {
            role: Role::named(r.iri.clone()),
            s: filler,
            o: root,
        }
    } else {
        Atom::Role {
            role: Role::named(r.iri.clone()),
            s: root,
            o: filler,
        }
    }
}

/// Collect the existential variable NAMES in `atom` that are not the witness root (these are the
/// interior variables removed by folding).
fn collect_existential_vars(cq: &Cq, atom: &Atom, root: &Term, out: &mut FxHashSet<String>) {
    for_each_var(atom, |v| {
        let t = Term::Var(v.to_string());
        if &t != root && is_existential(cq, &t) {
            out.insert(v.to_string());
        }
    });
}

fn for_each_var(a: &Atom, mut f: impl FnMut(&str)) {
    let mut go = |t: &Term| {
        if let Term::Var(v) = t {
            f(v);
        }
    };
    match a {
        Atom::Class { arg, .. } => go(arg),
        Atom::Role { s, o, .. } => {
            go(s);
            go(o);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn role(r: &str, s: Term, o: Term) -> Atom {
        Atom::Role {
            role: Role::named(r),
            s,
            o,
        }
    }
    fn class(c: &str, v: &str) -> Atom {
        Atom::Class {
            class: c.to_string(),
            arg: Term::Var(v.to_string()),
        }
    }
    fn cq(atoms: Vec<Atom>, answer: &[&str]) -> Cq {
        let mut a = atoms;
        a.sort();
        a.dedup();
        Cq {
            atoms: a,
            answer: answer.iter().map(|s| s.to_string()).collect(),
        }
    }

    fn tbox_employee_worksfor() -> TBox {
        // Employee ⊑ ∃worksFor.
        let mut t = TBox::default();
        t.exists_super
            .push((Basic::Class("Employee".into()), Role::named("worksFor")));
        t
    }

    #[test]
    fn folds_existential_role_to_generator() {
        // q = worksFor(?x, ?y) with ?y existential ⇒ tree witness folds to Employee(?x).
        let t = tbox_employee_worksfor();
        let q = cq(
            vec![role(
                "worksFor",
                Term::Var("x".into()),
                Term::Var("y".into()),
            )],
            &["x"],
        );
        let ucq = tree_witness_ucq(q.clone(), &t);
        // Input plus the Employee(?x) folding.
        assert!(
            ucq.iter().any(|c| c.atoms == vec![class("Employee", "x")]),
            "expected an Employee(?x) folding; got {ucq:?}"
        );
    }

    #[test]
    fn does_not_fold_on_bound_filler() {
        // ?y projected ⇒ NOT existential ⇒ no fold (would drop the ?y join — unsound).
        let t = tbox_employee_worksfor();
        let q = cq(
            vec![role(
                "worksFor",
                Term::Var("x".into()),
                Term::Var("y".into()),
            )],
            &["x", "y"],
        );
        let ucq = tree_witness_ucq(q.clone(), &t);
        assert_eq!(
            ucq.len(),
            1,
            "no fold when the filler is a bound answer var"
        );
        assert_eq!(ucq[0], q);
    }

    #[test]
    fn does_not_fold_on_shared_filler() {
        // ?y shared between two atoms ⇒ NOT existential ⇒ no fold.
        let t = tbox_employee_worksfor();
        let q = cq(
            vec![
                role("worksFor", Term::Var("x".into()), Term::Var("y".into())),
                role("worksFor", Term::Var("z".into()), Term::Var("y".into())),
            ],
            &["x"],
        );
        let ucq = tree_witness_ucq(q.clone(), &t);
        // ?y is shared so neither worksFor atom is a tree witness on its own.
        assert!(
            ucq.iter().all(|c| c.atoms.len() >= 2) || ucq.iter().any(|c| c == &q),
            "shared filler must not be folded directly; got {ucq:?}"
        );
    }

    #[test]
    fn exists_generator_emits_unique_fresh_filler() {
        // `∃knows ⊑ ∃worksFor`: the generator is itself an existential `∃knows`, so folding a
        // worksFor(?x,_) witness emits knows(?x, _fresh). The fresh filler must be UNIQUE (not
        // collide with the existing `_`), else a spurious join could lose answers.
        let mut t = TBox::default();
        t.exists_super
            .push((Basic::Exists(Role::named("knows")), Role::named("worksFor")));
        let q = cq(
            vec![role("worksFor", Term::Var("x".into()), Term::Unbound(0))],
            &["x"],
        );
        let ucq = tree_witness_ucq(q, &t);
        // A folded disjunct with a knows(?x, _) atom must appear, and its filler id must differ
        // from any other `_` in that disjunct.
        let folded = ucq.iter().find(|c| {
            c.atoms
                .iter()
                .any(|a| matches!(a, Atom::Role { role, .. } if role.iri == "knows"))
        });
        assert!(
            folded.is_some(),
            "expected a knows(?x,_) folding; got {ucq:?}"
        );
        let c = folded.unwrap();
        let mut ids: Vec<u32> = c
            .atoms
            .iter()
            .flat_map(|a| match a {
                Atom::Role { s, o, .. } => vec![s.clone(), o.clone()],
                Atom::Class { arg, .. } => vec![arg.clone()],
            })
            .filter_map(|t| match t {
                Term::Unbound(id) => Some(id),
                _ => None,
            })
            .collect();
        let len = ids.len();
        ids.sort_unstable();
        ids.dedup();
        assert_eq!(
            ids.len(),
            len,
            "every `_` filler id in the folded disjunct must be unique"
        );
    }

    #[test]
    fn termination_on_chain() {
        // Two independent existential roles ⇒ folding terminates (bounded).
        let mut t = TBox::default();
        t.exists_super
            .push((Basic::Class("Employee".into()), Role::named("worksFor")));
        t.exists_super
            .push((Basic::Class("Person".into()), Role::named("hasName")));
        let q = cq(
            vec![
                role("worksFor", Term::Var("x".into()), Term::Var("y".into())),
                role("hasName", Term::Var("x".into()), Term::Var("n".into())),
            ],
            &["x"],
        );
        let ucq = tree_witness_ucq(q, &t);
        // Should terminate and include the fully-folded Employee(?x) ∧ Person(?x) disjunct.
        assert!(
            ucq.iter().any(|c| {
                let names: FxHashSet<&str> = c
                    .atoms
                    .iter()
                    .filter_map(|a| match a {
                        Atom::Class { class, .. } => Some(class.as_str()),
                        _ => None,
                    })
                    .collect();
                names.contains("Employee") && names.contains("Person")
            }),
            "expected a fully-folded disjunct; got {ucq:?}"
        );
    }
}
