#!/usr/bin/env python3
# [OPUS-5] sq-1d528 (issue #3171) — STALENESS GATE for the committed
# inference-conformance-report.md.
#
# WHY: the inference ratchet number lives in FOUR places, and only one of them is
# regenerated by a machine:
#   • bench/conformance-scoreboard.generated.json  — the `inference-conformance`
#     row's `ratchet_floor` (exported from crates/sparq-conformance/src/scoreboard.rs
#     and byte-compared by tests/scoreboard_export.rs). SOURCE OF TRUTH here.
#   • .github/workflows/ci.yml — the `inference-conformance` job's `RATCHET=<n>`
#     (the value CI actually enforces) and the job `name:` that advertises it.
#   • inference-conformance-report.md — the COMMITTED snapshot of the run. CI
#     regenerates this file as a side effect of the conformance run and enforces the
#     floor against the FRESH copy, then uploads it as an artifact — nothing ever
#     compared it to the copy in git.
#
# The gap bit: sq-pbz04.1.3 (#1428) found the tracked report a full suite behind the
# enforced snapshot (a 1637-era report while CI enforced a much higher floor) with
# every gate green. A stale committed report is a published-honesty problem — it is
# what a reader (and research/inference-completeness-audit.md) treats as the current
# conformance state.
#
# THE INVARIANT (one number, three files):
#   committed report Overall `pass + documented divergence`  ==  scoreboard ratchet_floor
#   ci.yml `RATCHET=<n>`                                     ==  scoreboard ratchet_floor
#   ci.yml job name `(ratchet >= <n> pass+divergence)`       ==  scoreboard ratchet_floor
#
# EQUALITY, not `>=`, in BOTH directions, on purpose:
#   • report BELOW the floor  → the committed report is STALE (the #1428 bug).
#   • report ABOVE the floor  → conformance improved but the ratchet was never raised,
#     so CI is guarding a number the engine has already beaten and a regression back
#     to the old level would pass. Raise the floor with the improvement.
# The ratchet itself may still only ever RISE — that direction is the scoreboard's
# own rule (scoreboard.rs); this gate only pins the copies together.
#
# HEADING NOTE: the report generator (crates/sparq-conformance/src/inference/report.rs)
# writes `## Overall (all inference suites)`, which is the exact string ci.yml greps
# for; the COMMITTED report carries a hand-annotated `## Overall (all suites)` heading
# plus a paragraph explaining that the rdf-turtle lane rides the same ratchet without
# being an inference suite. So this gate matches `## Overall (all …)` either way and
# pins only the NUMBERS — a byte-comparison against generator output would be a
# different (and currently false) claim.
#
# Deterministic: stdlib only, text + JSON parsing, no cargo build, no network.
#
# Exit codes:  0 = in sync;  1 = drift (every mismatch is printed);  2 = usage/parse
# error (a missing file or an unparseable/ambiguous anchor — fail-closed, never a
# silent pass).
#
# Run:  python3 scripts/check-inference-report-drift.py
#       python3 scripts/check-inference-report-drift.py --self-test

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# The scoreboard row this gate is about.
CI_JOB = "inference-conformance"
RUNNER_KIND = "inference-binary"

# `## Overall (all suites)` / `## Overall (all inference suites)` — see HEADING NOTE.
OVERALL_HEADING_RE = re.compile(r"^##[ \t]+Overall \(all[^)\n]*\)[ \t]*$", re.MULTILINE)
# The bold totals line the generator emits under that heading. The `**` prefix is what
# separates it from the per-suite `**Overall (<suite>): 48 pass / …**` subtotal lines
# (same shape, but the digits do not follow the `**` directly) — ci.yml's own grep
# makes the same distinction.
TOTALS_RE = re.compile(
    r"\*\*(\d+) pass / (\d+) fail / (\d+) documented divergence / (\d+) out-of-scope"
)

# The ci.yml `inference-conformance` job block, and the two ratchet copies inside it.
JOB_START_RE = re.compile(r"^  %s:[ \t]*$" % re.escape(CI_JOB), re.MULTILINE)
NEXT_JOB_RE = re.compile(r"^  [A-Za-z0-9_.-]+:[ \t]*$", re.MULTILINE)
CI_RATCHET_RE = re.compile(r"^[ \t]*RATCHET=(\d+)[ \t]*$", re.MULTILINE)
CI_JOB_NAME_RE = re.compile(
    r"^[ \t]*name: Inference conformance \(ratchet >= (\d+) pass\+divergence\)[ \t]*$",
    re.MULTILINE,
)


class DriftError(Exception):
    """A file is missing, unparseable, or its anchor is ambiguous (exit 2)."""


def scoreboard_floor(text: str) -> int:
    """The `ratchet_floor` of the inference row in the scoreboard export."""
    try:
        doc = json.loads(text)
    except json.JSONDecodeError as e:
        raise DriftError(f"scoreboard is not valid JSON: {e}") from e
    rows = [
        s
        for s in doc.get("suites", [])
        if s.get("ci_job") == CI_JOB and s.get("runner", {}).get("kind") == RUNNER_KIND
    ]
    if len(rows) != 1:
        raise DriftError(
            f"expected exactly 1 scoreboard suite with ci_job={CI_JOB!r} and "
            f"runner.kind={RUNNER_KIND!r}, found {len(rows)}"
        )
    floor = rows[0].get("ratchet_floor")
    if not isinstance(floor, int):
        raise DriftError(f"scoreboard row has no integer ratchet_floor (got {floor!r})")
    return floor


def report_totals(text: str) -> tuple[int, int, int, int]:
    """`(pass, fail, divergence, out-of-scope)` from the report's FINAL Overall section."""
    headings = list(OVERALL_HEADING_RE.finditer(text))
    if not headings:
        raise DriftError(
            "report has no `## Overall (all …)` section — it is empty, truncated, or "
            "the generator's heading changed (see HEADING NOTE in this script)"
        )
    m = TOTALS_RE.search(text, headings[-1].end())
    if not m:
        raise DriftError(
            "report's final `## Overall (all …)` section has no "
            "`**<N> pass / <M> fail / <D> documented divergence / <K> out-of-scope` line"
        )
    return (int(m.group(1)), int(m.group(2)), int(m.group(3)), int(m.group(4)))


def ci_ratchets(text: str) -> tuple[int, int]:
    """`(RATCHET=<n>, job-name <n>)` from ci.yml's `inference-conformance` job block."""
    start = JOB_START_RE.search(text)
    if not start:
        raise DriftError(f"ci.yml has no `  {CI_JOB}:` job")
    nxt = NEXT_JOB_RE.search(text, start.end())
    block = text[start.end() : nxt.start() if nxt else len(text)]

    enforced = CI_RATCHET_RE.findall(block)
    if len(enforced) != 1:
        raise DriftError(
            f"expected exactly 1 `RATCHET=<n>` line in the {CI_JOB} job, "
            f"found {len(enforced)}"
        )
    advertised = CI_JOB_NAME_RE.findall(block)
    if len(advertised) != 1:
        raise DriftError(
            f"expected exactly 1 `name: Inference conformance (ratchet >= <n> "
            f"pass+divergence)` line in the {CI_JOB} job, found {len(advertised)}"
        )
    return (int(enforced[0]), int(advertised[0]))


def evaluate(
    floor: int, totals: tuple[int, int, int, int], enforced: int, advertised: int
) -> tuple[bool, list[str]]:
    """Pure decision core: is every copy of the ratchet number the same?"""
    passed, _fail, divergence, _oos = totals
    reported = passed + divergence
    problems: list[str] = []

    if reported != floor:
        direction = "STALE (behind)" if reported < floor else "AHEAD of"
        problems.append(
            f"  inference-conformance-report.md is {direction} the ratchet: its Overall "
            f"section says {passed} pass + {divergence} documented divergence = "
            f"{reported}, but the scoreboard floor is {floor}."
        )
        if reported < floor:
            problems.append(
                "    → the committed report predates the enforced snapshot. Re-run "
                "`scripts/fetch-inference-suites.sh` then `cargo run --release -p "
                "sparq-conformance --bin sparq-inference-conformance` and commit the "
                "regenerated inference-conformance-report.md."
            )
        else:
            problems.append(
                "    → conformance improved but the ratchet was never raised, so CI "
                "still guards the OLD number. Raise `ratchet_floor` in "
                "crates/sparq-conformance/src/scoreboard.rs, regenerate "
                "bench/conformance-scoreboard.generated.json, and update ci.yml's "
                "RATCHET + job name to match."
            )
    if enforced != floor:
        problems.append(
            f"  .github/workflows/ci.yml `{CI_JOB}` enforces RATCHET={enforced}, but "
            f"the scoreboard floor is {floor}. CI must enforce the declared floor."
        )
    if advertised != floor:
        problems.append(
            f"  .github/workflows/ci.yml `{CI_JOB}` job name advertises "
            f"`ratchet >= {advertised}`, but the scoreboard floor is {floor}."
        )

    if not problems:
        return True, [
            f"inference conformance ratchet in sync at {floor}: committed report "
            f"({passed} pass + {divergence} documented divergence), scoreboard "
            f"ratchet_floor, and ci.yml RATCHET + job name all agree."
        ]

    return False, [
        "DRIFT: the inference conformance ratchet disagrees across its copies.",
        f"  Source of truth: bench/conformance-scoreboard.generated.json "
        f"`{CI_JOB}` ratchet_floor = {floor}.",
        *problems,
    ]


# --------------------------------------------------------------------------- self-test

_GOOD_SCOREBOARD = json.dumps(
    {
        "suites": [
            {"ci_job": "conformance", "ratchet_floor": 1229, "runner": {"kind": "sparql-binary"}},
            {"ci_job": CI_JOB, "ratchet_floor": 1967, "runner": {"kind": RUNNER_KIND}},
        ]
    }
)

_GOOD_REPORT = """# sparq inference conformance report

**Overall (OWL 2 RL): 78 pass / 0 fail / 13 documented divergence / 36 out-of-scope.**

## Overall (all suites)

Covers the four inference regime suites plus the rdf-turtle parser suite.

**1950 pass / 0 fail / 17 documented divergence / 185 out-of-scope — pass+divergence 100.0% of run.**
"""

_STALE_REPORT = _GOOD_REPORT.replace("1950 pass", "1620 pass")

_GOOD_CI = """jobs:
  conformance:
    name: SPARQL conformance
    steps:
      - run: |
          RATCHET=1229
  inference-conformance:
    name: Inference conformance (ratchet >= 1967 pass+divergence)
    steps:
      - name: Enforce ratchet
        run: |
          RATCHET=1967
          FLOOR=1
  coverage-floors:
    name: Coverage
"""


def _self_test() -> int:
    failures: list[str] = []

    def check(label: str, cond: bool) -> None:
        if not cond:
            failures.append(label)

    # Parsers land on the real values.
    check("scoreboard floor parses", scoreboard_floor(_GOOD_SCOREBOARD) == 1967)
    check("report totals parse", report_totals(_GOOD_REPORT) == (1950, 0, 17, 185))
    check("ci ratchets parse", ci_ratchets(_GOOD_CI) == (1967, 1967))
    # The per-suite subtotal line above the Overall heading must NOT be picked up.
    check("subtotal line ignored", report_totals(_GOOD_REPORT)[0] != 78)

    # In-sync repo state passes.
    ok, _ = evaluate(1967, (1950, 0, 17, 185), 1967, 1967)
    check("in-sync state passes", ok)

    # Each drift direction fires, and says which file is wrong.
    ok, lines = evaluate(1967, (1620, 0, 17, 185), 1967, 1967)
    check("stale report fails", not ok)
    check("stale report names the report", any("STALE (behind)" in x for x in lines))
    ok, lines = evaluate(1967, (1990, 0, 17, 185), 1967, 1967)
    check("report ahead of floor fails", not ok)
    check("ahead report says AHEAD", any("AHEAD of" in x for x in lines))
    ok, lines = evaluate(1967, (1950, 0, 17, 185), 1637, 1967)
    check("lowered ci RATCHET fails", not ok)
    check("lowered RATCHET names ci.yml", any("RATCHET=1637" in x for x in lines))
    ok, _ = evaluate(1967, (1950, 0, 17, 185), 1967, 1637)
    check("stale job-name ratchet fails", not ok)

    # pass+divergence is the unit: moving a test from pass to documented divergence
    # keeps the total, and so must keep the gate green.
    ok, _ = evaluate(1967, (1949, 0, 18, 185), 1967, 1967)
    check("pass<->divergence reclassification stays green", ok)

    # Fail-closed on unparseable/ambiguous inputs — never a silent pass.
    for label, fn in (
        ("empty report", lambda: report_totals("# nothing here\n")),
        ("headless totals", lambda: report_totals("**1 pass / 0 fail / 0 documented divergence / 0 out-of-scope**")),
        ("missing scoreboard row", lambda: scoreboard_floor('{"suites": []}')),
        ("bad json", lambda: scoreboard_floor("{")),
        ("missing ci job", lambda: ci_ratchets("jobs:\n  other:\n    name: x\n")),
        (
            "ci job without RATCHET",
            lambda: ci_ratchets(
                "jobs:\n  inference-conformance:\n"
                "    name: Inference conformance (ratchet >= 1967 pass+divergence)\n"
            ),
        ),
    ):
        try:
            fn()
        except DriftError:
            pass
        else:
            failures.append(f"{label} must raise DriftError")

    # The RATCHET of a NEIGHBOURING job must not be read as this job's.
    try:
        enforced, _ = ci_ratchets(_GOOD_CI)
        check("neighbouring job's RATCHET not borrowed", enforced == 1967)
    except DriftError as e:  # pragma: no cover - only on a regression
        failures.append(f"block extraction raised: {e}")

    for f in failures:
        print(f"self-test FAILED: {f}", file=sys.stderr)
    if failures:
        return 1
    print("check-inference-report-drift self-test: all checks passed.")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Fail if the committed inference-conformance-report.md, the "
        "conformance scoreboard's ratchet_floor, and ci.yml's enforced RATCHET "
        "disagree (sq-1d528)."
    )
    ap.add_argument("--self-test", action="store_true", help="hermetic logic check, no repo read")
    ap.add_argument(
        "--report", default=str(REPO_ROOT / "inference-conformance-report.md"),
        help="path to the committed inference conformance report",
    )
    ap.add_argument(
        "--scoreboard",
        default=str(REPO_ROOT / "bench" / "conformance-scoreboard.generated.json"),
        help="path to the machine-readable conformance scoreboard export",
    )
    ap.add_argument(
        "--workflow", default=str(REPO_ROOT / ".github" / "workflows" / "ci.yml"),
        help="path to the workflow carrying the inference-conformance job",
    )
    args = ap.parse_args(argv)

    if args.self_test:
        return _self_test()

    try:
        floor = scoreboard_floor(Path(args.scoreboard).read_text(encoding="utf-8"))
        totals = report_totals(Path(args.report).read_text(encoding="utf-8"))
        enforced, advertised = ci_ratchets(Path(args.workflow).read_text(encoding="utf-8"))
    except OSError as e:
        print("check-inference-report-drift: ERROR: {}".format(e), file=sys.stderr)
        return 2
    except DriftError as e:
        print("check-inference-report-drift: ERROR: {}".format(e), file=sys.stderr)
        return 2

    ok, lines = evaluate(floor, totals, enforced, advertised)
    out = sys.stdout if ok else sys.stderr
    for line in lines:
        print(line, file=out)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
