//! # sparq-kb — the Project-Knowledge-Graph (PKG) ontology + SHACL guardrails
//!
//! [OPUS-4.8] sq-2m6zm.1 (epic sq-2m6zm); design record
//! `research/dogfooding-sparq-knowledge-graph.md` (PR #1063). 🤖 SPARQ agent —
//! dogfooding sparq as a project knowledge graph. Written while Fable unavailable;
//! flag for re-review when Fable returns.
//!
//! This crate ships the **data artifacts** of Phase 1 of the PKG dogfooding design:
//!
//! - [`PKG_ONTOLOGY`] — the reuse-first PKG vocabulary (Turtle), generalising the
//!   vendored `zkp-sparql` `sig-impl:Assertion` reified-claim pattern into
//!   `pkg:Finding` and reusing PROV-O / SKOS / DCAT / FaBiO-FRBR-DC / CiTO /
//!   schema.org / nanopublications. Only ~4 terms are net-new plus the single
//!   `pkg:dependsOn owl:inverseOf pkg:blockedBy` pair (there is NO `pkg:blocks`).
//! - [`PKG_SHAPES`] — the SHACL **write-time guardrails**: every `pkg:Finding` must
//!   carry a source + a confidence value + an assurance basis + non-filler content,
//!   and every `pkg:Task` must have a valid status / bounded priority / no stale
//!   `pkg:blockedBy` edge.
//! - [`PKG_EXAMPLE`] — a tiny hand-written instance file (valid Findings/Tasks plus
//!   deliberately invalid ones) used to dogfood the guardrails.
//! - [`vocab`] — the `pkg:` IRIs as Rust constants, byte-pinned against the Turtle.
//!
//! The crate is `publish = false` and pulls in `sparq-shacl` only as a dev-dependency
//! for the dogfooding validation test, so it does not change any shipped build (the
//! ontology files are data, not code). The validation helpers below are gated behind
//! the default-OFF `validate` feature so the lean default build of this crate is a
//! pure data + constants crate.

pub mod vocab;

/// The PKG ontology (Turtle), `ontology/pkg/pkg.ttl`.
pub const PKG_ONTOLOGY: &str = include_str!("../ontology/pkg/pkg.ttl");

/// The PKG SHACL guardrail shapes (Turtle), `shapes/pkg.shapes.ttl`.
pub const PKG_SHAPES: &str = include_str!("../shapes/pkg.shapes.ttl");

/// A tiny hand-written PKG instance file (valid + deliberately-invalid nodes),
/// `examples/pkg-example.ttl`.
pub const PKG_EXAMPLE: &str = include_str!("../examples/pkg-example.ttl");

/// The Phase-1 **ingested** PKG graph (Turtle), `ingest/pkg-instances.ttl` —
/// generated by `ingest/ingest_pkg.py` (sq-2m6zm.2): a mechanical projection of
/// `.beads/issues.jsonl` into `pkg:Task` triples + a structured parse of the heaviest
/// `skills/*/SKILL.md` front-matter into `pkg:Source`/`pkg:Technique` triples, with
/// the hand-authored `pkg:Finding`s of `ingest/agents-findings.ttl` appended. It
/// conforms to [`PKG_SHAPES`] (0 violations); the bd backlog's stale closed→open
/// dependency edges are guardrail-excluded (see the ingest script + README).
pub const PKG_INSTANCES: &str = include_str!("../ingest/pkg-instances.ttl");

/// Validation helpers over `sparq-shacl`. OPT-IN behind the default-OFF `validate`
/// cargo feature so the default build of this crate carries no engine/SHACL code.
#[cfg(feature = "validate")]
pub mod validate {
    use oxrdf::Triple;
    use sparq_core::Graph;
    use sparq_shacl::{validate, ValidationReport};

    /// Parse one Turtle document into a `Vec<Triple>`, resolving relative IRIs
    /// against `base`. Errors carry the parser message.
    pub fn parse_turtle(text: &str, base: &str) -> Result<Vec<Triple>, String> {
        let parser = oxttl::TurtleParser::new()
            .with_base_iri(base)
            .map_err(|e| e.to_string())?;
        let mut out = Vec::new();
        for t in parser.for_slice(text.as_bytes()) {
            out.push(t.map_err(|e| e.to_string())?);
        }
        Ok(out)
    }

    /// Build one [`Graph`] from the concatenation of several Turtle documents
    /// (each parsed independently so prefix scopes do not leak across documents),
    /// resolving relative IRIs against `base`.
    pub fn graph_from_turtle_docs(docs: &[&str], base: &str) -> Result<Graph, String> {
        let mut triples = Vec::new();
        for d in docs {
            triples.extend(parse_turtle(d, base)?);
        }
        Ok(sparq_shacl::graph_from_triples(triples))
    }

    /// Load the PKG ontology + a set of instance documents into one data graph and
    /// validate it against the PKG SHACL shapes. Returns the [`ValidationReport`].
    pub fn validate_instances(instance_docs: &[&str]) -> Result<ValidationReport, String> {
        let base = "https://sparq.dev/ns/pkg/example#";
        let mut docs = vec![super::PKG_ONTOLOGY];
        docs.extend_from_slice(instance_docs);
        let data = graph_from_turtle_docs(&docs, base)?;
        let shapes = graph_from_turtle_docs(&[super::PKG_SHAPES], base)?;
        Ok(validate(&data, &shapes))
    }
}

/// SPARQL-query helpers over the ingested PKG graph — the **introspect → ground →
/// ask** mechanism of the dogfooding epic (sq-2m6zm.3). OPT-IN behind the default-OFF
/// `query` cargo feature (pulls in the SPARQL engine); the optional [`close`](query::close)
/// step is gated behind the further default-OFF `close` feature (pulls in
/// `sparq-reason`). The answers are computed deterministically by the engine, not
/// generated, so within the store the agent cannot fabricate a fact the data does not
/// contain.
///
/// > **Honesty (per the design record §1).** This module is the *mechanism*. Whether
/// > querying the PKG actually cuts an agent's token spend versus reading the source
/// > document is **measured by sq-2m6zm.4**, not claimed here — this code carries no
/// > token-saving number.
#[cfg(feature = "query")]
pub mod query {
    use sparq_core::Graph;
    use sparq_engine::{query, QueryResult};

    pub mod canned;

    /// Load the PKG ontology + the ingested instances into one queryable [`Graph`].
    /// The `kb:` instances use absolute IRIs, so no base is needed.
    pub fn load_pkg() -> Result<Graph, String> {
        let combined = format!("{}\n{}", super::PKG_ONTOLOGY, super::PKG_INSTANCES);
        Graph::load_str(&combined, "turtle")
    }

    /// Run a SPARQL `SELECT` over the ingested PKG graph and return the result set.
    pub fn ask_pkg(graph: &Graph, sparql: &str) -> Result<QueryResult, String> {
        query(graph, sparql)
    }

    /// The optional RDFS / OWL-RL **closure-before-query** step the design record
    /// (§3.1: "always close first") calls for. Materialising the OWL-RL closure makes
    /// the `pkg:dependsOn owl:inverseOf pkg:blockedBy` pair and the
    /// `pkg:couldBeMergedWith` symmetry *entailed*, so a query written over the inverse
    /// / symmetric direction sees edges that were only asserted the other way round.
    /// OPT-IN behind the default-OFF `close` feature (pulls in `sparq-reason`).
    ///
    /// [OPUS-4.8] sq-2m6zm.3
    #[cfg(feature = "close")]
    pub mod close {
        use sparq_core::Graph;
        pub use sparq_reason::Profile;

        /// Load the PKG (ontology + instances), materialise the `profile` closure
        /// ([`Profile::Rdfs`] or [`Profile::OwlRl`]) in place, and return the closed
        /// [`Graph`] together with the number of entailed triples added.
        ///
        /// The closure step never fails (materialisation only *adds* triples); the
        /// only error path is the Turtle parse.
        pub fn load_pkg_closed(profile: Profile) -> Result<(Graph, usize), String> {
            let combined = format!(
                "{}\n{}",
                super::super::PKG_ONTOLOGY,
                super::super::PKG_INSTANCES
            );
            let (mut dict, mut triples) = Graph::parse_to_triples(&combined, "turtle")?;
            let entailed = sparq_reason::materialize(profile, &mut dict, &mut triples);
            Ok((Graph::from_parts(dict, triples), entailed))
        }
    }
}
