import * as React from "react";

import { cn } from "@/lib/utils";

/*
 * [OPUS-4.8] sq-8pbx — shield + lightning logo CONCEPTS, ROUND 2, for issue #207.
 *
 * The maintainer rejected the ENTIRE first round (#823's original four) as too
 * generic — a textbook heraldic-pentagon shield with a lightning bolt placed inside
 * it, which read like clip-art — and asked for a markedly better pass.
 *
 * This is that fresh round. Every mark here is rebuilt for: a TIGHTER, more modern
 * silhouette (flatter shoulders / confident point or a real squircle, not a floppy
 * pentagon); a CHUNKY negative-space bolt that survives 16px (the prior round's thin
 * bolts and fiddly speed-lines vanished small); and far LESS reliance on the warm
 * accent that cluttered the first round. Each was authored as a standalone SVG and
 * rasterised at 16 / 32 / 64 / 256px on BOTH a white and a near-black field, and the
 * geometry iterated against what the rendered pixels actually showed.
 *
 * Tooling note (honest): no external "Claude Design"/image-generation API was wired
 * into this environment, so these are HAND-AUTHORED SVGs produced via the repo's
 * bundled `logo-designer` skill process — parallel concept generation + a strict
 * raster-then-look favicon-legibility loop — NOT generated by an image API.
 *
 * Palette: the real site teal. The brand teal is pinned to the `--primary` token
 * with an sRGB hex fallback (#007883, the light-theme --primary) so a standalone
 * export with no CSS-variable context still renders correctly. Deeper / brighter
 * teals (#005966, #00424d, #1a9aa5, the #0a8f9a→#006d77 tile gradient) are derived
 * from the same hue. Marks are SELF-COLOURED teal (not currentColor) because a brand
 * mark should stay teal on any field; they read on both light and dark because the
 * teal silhouette + the void/field-showing-through bolt carry their own contrast.
 *
 * These are CONCEPTS to choose from; they do NOT replace the live favicon/header
 * `Logo` yet. The two strongest (Q-Shield, Shield Tile) carry full wordmark lockups.
 */

// Brand teal, pinned to the site token with an sRGB hex fallback for standalone export.
const TEAL = "var(--primary, #007883)";

type MarkProps = React.ComponentProps<"svg">;

/**
 * Concept 1 — "Q-Shield" (flagship).
 * A solid teal shield with the lightning bolt knocked clean out as negative space
 * (fill-rule evenodd, so the field shows through). The silhouette is deliberately
 * tightened vs. a floppy heraldic crest: a flat, squared top with softened corners,
 * straight shoulders, and a confident chiselled point. The bolt limbs are fattened
 * so the zigzag stays unmistakable down to 16px — the single strongest, most
 * favicon-ready direction, and the one given the primary wordmark lockup.
 */
export function MarkQShield({ className, ...props }: MarkProps) {
  return (
    <svg
      viewBox="0 0 64 64"
      role="img"
      aria-label="sparq shield-bolt mark, concept Q-Shield"
      className={cn(className)}
      {...props}
    >
      <path
        fill={TEAL}
        fillRule="evenodd"
        d="M14 8 H50 Q53 8 53 11 V32 C53 45 44 54 32 59 C20 54 11 45 11 32 V11 Q11 8 14 8 Z
           M39 14 L22 35 H31 L27 49 L42 29 H33 Z"
      />
    </svg>
  );
}

/**
 * Concept 2 — "Shield Tile".
 * A modern iOS-style squircle tile (the silhouette app/PWA icons actually use) that
 * tapers to a shield-like chin at the base, so it reads as a hybrid app-tile +
 * shield rather than a plain rounded square. A bold knockout bolt sits dead-centre;
 * a subtle vertical teal gradient (#0a8f9a → #006d77) gives it real app-icon depth.
 * No speed lines, no fiddly trailing detail (the first round's tile had those and
 * they vanished small). The most shippable app-icon of the set; carries a lockup.
 */
export function MarkTile({ className, ...props }: MarkProps) {
  return (
    <svg
      viewBox="0 0 64 64"
      role="img"
      aria-label="sparq shield-bolt mark, concept Shield Tile"
      className={cn(className)}
      {...props}
    >
      <defs>
        <linearGradient
          id="sparq-tile-grad"
          x1="32"
          y1="4"
          x2="32"
          y2="62"
          gradientUnits="userSpaceOnUse"
        >
          <stop offset="0" stopColor="#0a8f9a" />
          <stop offset="1" stopColor="#006d77" />
        </linearGradient>
      </defs>
      <path
        fill="url(#sparq-tile-grad)"
        fillRule="evenodd"
        d="M32 4 C10 4 4 10 4 32 C4 41 5 46 10 51 C15 57 23 60.5 32 62
           C41 60.5 49 57 54 51 C59 46 60 41 60 32 C60 10 54 4 32 4 Z
           M41 13 L19 35 L31 35 L26 51 L45 30 L33 30 Z"
      />
    </svg>
  );
}

/**
 * Concept 3 — "Sealed Crest".
 * A double-frame emblem: a solid teal shield border with a slightly inset darker-teal
 * panel inside it, and the bolt carved out of that inner panel so the void reveals the
 * brighter outer teal behind it. The concentric border → inset field → bolt gives it a
 * "sealed / verified credential" gravitas a flat single shield lacks. Richest at
 * 32–256px; at 16px it reduces to a clean shield-with-bolt (the double frame is large-
 * size polish). The more heraldic, badge-like option.
 */
export function MarkSealed({ className, ...props }: MarkProps) {
  return (
    <svg
      viewBox="0 0 64 64"
      role="img"
      aria-label="sparq shield-bolt mark, concept Sealed Crest"
      className={cn(className)}
      {...props}
    >
      <path
        fill={TEAL}
        d="M32 4 L55 10 V31 C55 44 45 53 32 60 C19 53 9 44 9 31 V10 Z"
      />
      <path
        fill="#00424d"
        fillRule="evenodd"
        d="M32 11 L49 15 V31 C49 41 42 48 32 53 C22 48 15 41 15 31 V15 Z
           M37 17 L25 35 H31 L29 49 L41 31 H35 Z"
      />
    </svg>
  );
}

/**
 * Concept 4 — "Bolt-Lock".
 * The boldest, most graphic option: the shield is two solid teal tone-halves (deep
 * #005966 left, brand #007883 right) meeting on the centreline, and one chunky bolt
 * subpath is knocked out of BOTH halves (evenodd), so a single transparent bolt-void
 * cleaves the shield — energy passing through the guard. Striking at 32–256px; the
 * two-tone offset is deliberately subtle and the bolt is the hero. At 16px it reads as
 * a single-tone shield-with-bolt (the correct favicon priority).
 */
export function MarkBoltLock({ className, ...props }: MarkProps) {
  return (
    <svg
      viewBox="0 0 64 64"
      role="img"
      aria-label="sparq shield-bolt mark, concept Bolt-Lock"
      className={cn(className)}
      {...props}
    >
      <path
        fill="#005966"
        fillRule="evenodd"
        d="M32 4 L9 11 L9 32 C9 45 19 54 32 60 Z
           M43 9 L16 34 L32 34 L22 53 L48 30 L32 30 L43 9 Z"
      />
      <path
        fill={TEAL}
        fillRule="evenodd"
        d="M32 4 L55 11 L55 32 C55 45 45 54 32 60 Z
           M43 9 L16 34 L32 34 L22 53 L48 30 L32 30 L43 9 Z"
      />
    </svg>
  );
}

/**
 * Concept 5 — "Facet Crest" (most experimental).
 * A shield built from a few flat geometric facets (a cut gem / origami), where the
 * lightning bolt is the SEAM between a deep-teal and a bright-teal plane rather than a
 * separate object — a crystalline, engineered feel. A faint void hairline along the
 * seam reads as a beveled edge, and a small mid-teal highlight facet catches light on
 * the top-right shoulder. Most distinctive at 64–256px. HONEST CAVEAT: at 16–32px the
 * zigzag seam softens to a strong diagonal tonal split rather than a fully crisp bolt —
 * an inherent limit of a seam-as-bolt at that pixel count; the shield read stays clean.
 */
export function MarkFacet({ className, ...props }: MarkProps) {
  return (
    <svg
      viewBox="0 0 64 64"
      role="img"
      aria-label="sparq shield-bolt mark, concept Facet Crest"
      className={cn(className)}
      {...props}
    >
      <defs>
        <clipPath id="sparq-facet-clip">
          <path d="M32 5 L54 12 V32 C54 45 44 54 32 59 C20 54 10 45 10 32 V12 Z" />
        </clipPath>
      </defs>
      <g clipPath="url(#sparq-facet-clip)">
        <rect width="64" height="64" fill="#1a9aa5" />
        <path d="M39 0 L54 0 L54 25 Z" fill="#007883" />
        <path d="M0 0 H40 L22 29 H38 L16 59 H0 Z" fill="#005966" />
        <path
          d="M40 0 L22 29 H38 L16 59"
          fill="none"
          stroke="#081116"
          strokeWidth={1.5}
          strokeLinejoin="miter"
          opacity={0.3}
        />
      </g>
    </svg>
  );
}

/** Shared wordmark used in the lockups — matches the existing header type
 * (JetBrains Mono, weight 700). currentColor so it follows the field. */
function Wordmark() {
  return (
    <text
      x="74"
      y="44"
      fill="currentColor"
      fontFamily="ui-monospace,'JetBrains Mono','SF Mono',Menlo,monospace"
      fontSize="40"
      fontWeight={700}
      letterSpacing="-1"
    >
      sparq
    </text>
  );
}

/** Full lockup for the flagship Q-Shield: mark + monospace wordmark. */
export function LockupQShield({ className, ...props }: MarkProps) {
  return (
    <svg
      viewBox="0 0 232 64"
      role="img"
      aria-label="sparq"
      className={cn("text-foreground", className)}
      {...props}
    >
      <path
        fill={TEAL}
        fillRule="evenodd"
        d="M14 8 H50 Q53 8 53 11 V32 C53 45 44 54 32 59 C20 54 11 45 11 32 V11 Q11 8 14 8 Z
           M39 14 L22 35 H31 L27 49 L42 29 H33 Z"
      />
      <Wordmark />
    </svg>
  );
}

/** Full lockup for the Shield Tile (app-icon direction) + wordmark. */
export function LockupTile({ className, ...props }: MarkProps) {
  return (
    <svg
      viewBox="0 0 232 64"
      role="img"
      aria-label="sparq"
      className={cn("text-foreground", className)}
      {...props}
    >
      <defs>
        <linearGradient
          id="sparq-tile-lockup-grad"
          x1="32"
          y1="4"
          x2="32"
          y2="62"
          gradientUnits="userSpaceOnUse"
        >
          <stop offset="0" stopColor="#0a8f9a" />
          <stop offset="1" stopColor="#006d77" />
        </linearGradient>
      </defs>
      <path
        fill="url(#sparq-tile-lockup-grad)"
        fillRule="evenodd"
        d="M32 4 C10 4 4 10 4 32 C4 41 5 46 10 51 C15 57 23 60.5 32 62
           C41 60.5 49 57 54 51 C59 46 60 41 60 32 C60 10 54 4 32 4 Z
           M41 13 L19 35 L31 35 L26 51 L45 30 L33 30 Z"
      />
      <Wordmark />
    </svg>
  );
}

export type Concept = {
  id: string;
  name: string;
  tagline: string;
  idea: string;
  Mark: React.ComponentType<MarkProps>;
  Lockup?: React.ComponentType<MarkProps>;
};

export const CONCEPTS: Concept[] = [
  {
    id: "qshield",
    name: "Q-Shield",
    tagline: "Solid shield, carved bolt",
    idea: "Flagship. A solid teal shield with the bolt knocked clean out as negative space; the silhouette is tightened to a flat-topped, confident-point crest (no floppy pentagon), and the bolt limbs are fattened so the zigzag stays unmistakable at 16px. The strongest, most favicon-ready mark — shown with a full wordmark lockup.",
    Mark: MarkQShield,
    Lockup: LockupQShield,
  },
  {
    id: "tile",
    name: "Shield Tile",
    tagline: "App-icon squircle + carved bolt",
    idea: "A modern iOS-style squircle tile that tapers to a shield chin at the base (app-tile + shield hybrid), with a bold centred knockout bolt and a subtle teal gradient for depth. No speed lines, no fiddly detail. The most shippable OS/PWA app-icon of the set — also carries a full lockup.",
    Mark: MarkTile,
    Lockup: LockupTile,
  },
  {
    id: "sealed",
    name: "Sealed Crest",
    tagline: "Double-frame seal, carved bolt",
    idea: 'A double-frame emblem: a teal shield border, a darker inset panel, and the bolt carved out of the panel so the void reveals the brighter outer teal. The concentric border → field → bolt gives it a "verified credential" gravitas a flat shield lacks. Richest at 32–256px; reduces to a clean shield-with-bolt at 16px.',
    Mark: MarkSealed,
  },
  {
    id: "boltlock",
    name: "Bolt-Lock",
    tagline: "Two-tone shield, bolt cleaves it",
    idea: "The boldest, most graphic option. Two solid teal tone-halves meet on the centreline and a single chunky bolt-void is knocked out of both — energy cleaving the guard. Striking at 32–256px; the two-tone offset is subtle and the bolt is the hero. At 16px it reads as a single-tone shield-with-bolt.",
    Mark: MarkBoltLock,
  },
  {
    id: "facet",
    name: "Facet Crest",
    tagline: "Cut-gem facets, bolt as seam",
    idea: "Most experimental. A shield built from a few flat teal facets (a cut gem / origami) where the bolt is the seam between a deep and a bright plane, not a separate object — a crystalline, engineered feel. Most distinctive at 64–256px. Honest caveat: at 16–32px the seam softens to a strong diagonal tonal split rather than a fully crisp bolt.",
    Mark: MarkFacet,
  },
];
