// [FABLE-5] sq-ohnj1 — one-time loader for the bundled sparq-reason wasm.
//
// The wasm asset ships INSIDE this npm tarball (packages/eyereasoner-compat/wasm/). The loader
// NEVER references a site-hosted URL — it resolves the `.wasm` relative to the bundled glue.
//   - Node:    Node's `fetch` cannot read `file://`, so we read the bytes with `fs` and hand
//              them to the wasm-bindgen init.
//   - Browser / CDN (esm.sh, jsdelivr, unpkg): the wasm-bindgen `--target web` glue resolves
//              its sibling `_bg.wasm` via `import.meta.url`, so `init()` with no argument works.
//   - Escape hatch: `configureWasm(input)` lets a caller point at the `.wasm` explicitly
//              (a URL, a fetch `Response`, or the raw bytes) for exotic bundlers/CDNs.

// The wasm-bindgen glue: default export is the async init; `Reasoner` is the class. Types come
// from the sibling `sparq_reason_wasm.d.ts` generated by wasm-pack.
import init, { Reasoner } from '../wasm/sparq_reason_wasm.js';

/** Anything the wasm-bindgen init accepts: a URL/string, a fetch `Response`, or raw bytes. */
export type WasmInput = string | URL | Response | BufferSource | WebAssembly.Module;

let override: WasmInput | undefined;
let ready: Promise<typeof Reasoner> | undefined;

/**
 * Point the loader at the `.wasm` explicitly (for bundlers/CDNs where the default
 * `import.meta.url` resolution does not apply). Must be called before the first reasoning call.
 */
export function configureWasm(input: WasmInput): void {
  if (ready) throw new Error('configureWasm() must be called before the first n3reasoner() call');
  override = input;
}

const isNode = typeof process !== 'undefined' && !!process.versions?.node
  && typeof (globalThis as { window?: unknown }).window === 'undefined';

async function load(): Promise<typeof Reasoner> {
  if (override !== undefined) {
    await init({ module_or_path: override });
  } else if (isNode) {
    // Node: read the sibling wasm bytes (fetch() has no file:// support in Node).
    const { readFile } = await import('node:fs/promises');
    const bytes = await readFile(new URL('../wasm/sparq_reason_wasm_bg.wasm', import.meta.url));
    await init({ module_or_path: bytes });
  } else {
    // Browser / CDN: the glue self-resolves its sibling _bg.wasm via import.meta.url.
    await init();
  }
  return Reasoner;
}

/**
 * Initialise (idempotently) and return the wasm `Reasoner`. The fetch/compile/instantiate cold
 * start happens at most once; a failed load resets the cache so a later call can retry.
 */
export function loadReasoner(): Promise<typeof Reasoner> {
  if (!ready) {
    ready = load().catch((e) => { ready = undefined; throw e; });
  }
  return ready;
}
