// AUTHORED-BY Claude Fable 5
//! DPoP-SK key material — the exporter label, HKDF session-key derivation, the key-confirmation
//! value, and the HMAC-SHA256 attestation primitive.
//!
//! Normative source: the DPoP-SK profile ([[DPOP-SK]] — <https://jeswr.github.io/dpop-sk-spec/>),
//! whose §"Key derivation" defines byte-for-byte:
//!
//! ```text
//! EKM = TLS-Exporter("EXPERIMENTAL-dpop-sk-v1", context = "" (zero-length), 32 bytes)
//! PRK = HKDF-Extract(salt = ASCII(session_id), IKM = EKM)
//! K   = HKDF-Expand(PRK, info = ASCII("dpop-sk/v1") || 0x00 || ASCII(ath) || 0x00 || ASCII(jkt), 32)
//! confirm = base64url(HMAC-SHA256(K, "dpop-sk/v1 confirm" || 0x00 || ASCII(session_id)))
//! ```
//!
//! The exporter label is DELIBERATELY a dedicated RFC 5705 §4 private-use label
//! (`EXPERIMENTAL-dpop-sk-v1`) and NOT the RFC 9266 `EXPORTER-Channel-Binding` value — RFC 9266
//! registers that value as non-secret and forbids using it as key material ("MUST NOT use channel
//! binding as a secret key"); reusing it was a FINDING against the design basis (spec Appendix B
//! entry A14). [`EXPORTER_LABEL`] is pinned by a test against the spec string so a regression back
//! to the channel-binding value cannot land silently.
//!
//! All primitives go through `aws-lc-rs` (the house rustls crypto provider — already the process
//! crypto backend): HKDF-SHA256 for derivation, HMAC-SHA256 (constant-time `verify`) for the
//! per-request attestation. Nothing here is hand-rolled.
//!
//! Every computed value is pinned against the spec's execution-verified Appendix-A worked example
//! (generated by `dpop-sk-spec/tools/compute-examples.mjs`) in the tests below, so this
//! implementation and the spec cannot silently diverge.

use aws_lc_rs::{hkdf, hmac};
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use base64::Engine as _;

/// The RFC 5705 §4 private-use TLS exporter label for the `cb=tls-exporter` flavour.
///
/// MUST equal the spec's `EXPERIMENTAL-dpop-sk-v1` (pinned by a test). It is NOT the RFC 9266
/// `EXPORTER-Channel-Binding` label — see the module docs.
pub const EXPORTER_LABEL: &[u8] = b"EXPERIMENTAL-dpop-sk-v1";

/// The exporter context: explicitly present and zero-length (spec §"Key derivation"; RFC 8446 §7.5
/// notes an empty context is permitted, and in TLS 1.3 an empty context equals an absent one).
pub const EXPORTER_CONTEXT: &[u8] = b"";

/// The HKDF info-prefix / profile version string (`dpop-sk/v1`).
const INFO_PREFIX: &[u8] = b"dpop-sk/v1";

/// The key-confirmation HMAC message prefix (`"dpop-sk/v1 confirm"`).
const CONFIRM_PREFIX: &[u8] = b"dpop-sk/v1 confirm";

/// 32 bytes of TLS Exported Keying Material (the `cb=tls-exporter` IKM). A per-connection SECRET:
/// `Debug` is redacted and the bytes are zeroed on drop (best-effort in-process hygiene — spec
/// §"Key handling": key material MUST NOT be logged).
#[derive(Clone, PartialEq, Eq)]
pub struct Ekm([u8; 32]);

impl Ekm {
    pub fn new(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }
}

impl std::fmt::Debug for Ekm {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("Ekm(<redacted>)")
    }
}

impl Drop for Ekm {
    fn drop(&mut self) {
        // Best-effort zeroization (no `zeroize` dep — keep the supply-chain surface unchanged).
        for b in self.0.iter_mut() {
            *b = 0;
        }
    }
}

/// The 32-byte symmetric session key `K`. Same secrecy discipline as [`Ekm`]: redacted `Debug`,
/// zero-on-drop, and the raw bytes only leave via [`SessionKey::to_base64url`] (the one place the
/// `cb=none` establishment response needs them).
#[derive(Clone, PartialEq, Eq)]
pub struct SessionKey([u8; 32]);

impl SessionKey {
    pub fn new(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    /// A fresh CSPRNG session key (the `cb=none` flavour).
    pub fn random() -> Result<Self, getrandom::Error> {
        let mut k = [0u8; 32];
        getrandom::getrandom(&mut k)?;
        Ok(Self(k))
    }

    /// base64url-no-pad encoding — used ONLY by the `cb=none` establishment response `key` member.
    pub fn to_base64url(&self) -> String {
        URL_SAFE_NO_PAD.encode(self.0)
    }
}

impl std::fmt::Debug for SessionKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("SessionKey(<redacted>)")
    }
}

impl Drop for SessionKey {
    fn drop(&mut self) {
        for b in self.0.iter_mut() {
            *b = 0;
        }
    }
}

/// Derive the `cb=tls-exporter` session key per the spec (see the module docs for the exact
/// formula). `session_id`/`ath`/`jkt` are bound as their base64url ASCII strings; the `0x00`
/// separators cannot occur in base64url, so the info encoding is injective.
pub fn derive_session_key(ekm: &Ekm, session_id: &str, ath: &str, jkt: &str) -> SessionKey {
    let salt = hkdf::Salt::new(hkdf::HKDF_SHA256, session_id.as_bytes());
    let prk = salt.extract(&ekm.0);
    let info: [&[u8]; 5] = [INFO_PREFIX, &[0u8], ath.as_bytes(), &[0u8], jkt.as_bytes()];
    let okm = prk
        .expand(&info, hkdf::HKDF_SHA256)
        .expect("HKDF-SHA256 expand to 32 bytes is always within bounds");
    let mut k = [0u8; 32];
    okm.fill(&mut k)
        .expect("okm length matches the 32-byte output");
    SessionKey(k)
}

/// The `confirm` member of the `cb=tls-exporter` establishment response:
/// `base64url(HMAC-SHA256(K, "dpop-sk/v1 confirm" || 0x00 || ASCII(session_id)))`. Publishing an
/// HMAC of a fixed public message under `K` does not weaken HMAC-SHA256 (spec §"Response").
pub fn confirm_value(k: &SessionKey, session_id: &str) -> String {
    let key = hmac::Key::new(hmac::HMAC_SHA256, &k.0);
    let mut ctx = hmac::Context::with_key(&key);
    ctx.update(CONFIRM_PREFIX);
    ctx.update(&[0u8]);
    ctx.update(session_id.as_bytes());
    URL_SAFE_NO_PAD.encode(ctx.sign().as_ref())
}

/// HMAC-SHA256 over an RFC 9421 signature base — the CLIENT-side signing primitive (used by the
/// in-repo tests and any co-located client helper; the server itself only verifies).
pub fn hmac_sign(k: &SessionKey, message: &[u8]) -> Vec<u8> {
    let key = hmac::Key::new(hmac::HMAC_SHA256, &k.0);
    hmac::sign(&key, message).as_ref().to_vec()
}

/// Constant-time HMAC-SHA256 verification (aws-lc-rs `hmac::verify` — the vetted primitive; spec
/// §"Key handling": "HMAC comparison MUST be constant-time").
pub fn hmac_verify(k: &SessionKey, message: &[u8], tag: &[u8]) -> bool {
    let key = hmac::Key::new(hmac::HMAC_SHA256, &k.0);
    hmac::verify(&key, message, tag).is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    // ------------------------------------------------------------------------------------------
    // The spec's execution-verified Appendix-A worked example (dpop-sk-spec
    // tools/compute-examples.mjs). Fixed inputs + published outputs, asserted byte-for-byte.
    // Shared vectors live in `crate::pop::sk::test_vectors`.
    // ------------------------------------------------------------------------------------------
    use crate::pop::sk::test_vectors::{
        example_ekm, example_k_none, EXAMPLE_ATH, EXAMPLE_JKT, EXAMPLE_SESSION_ID, EXAMPLE_TOKEN,
    };

    #[test]
    fn exporter_label_is_the_dedicated_private_use_label_not_the_rfc9266_value() {
        // Pins the label against the spec string. A regression to the RFC 9266 channel-binding
        // value (`EXPORTER-Channel-Binding`) would violate RFC 9266's "MUST NOT use channel binding
        // as a secret key" — the spec's Appendix-B A14 FINDING.
        assert_eq!(EXPORTER_LABEL, b"EXPERIMENTAL-dpop-sk-v1");
        assert_ne!(EXPORTER_LABEL, b"EXPORTER-Channel-Binding".as_slice());
        assert!(
            EXPORTER_LABEL.starts_with(b"EXPERIMENTAL"),
            "RFC 5705 §4 private-use labels must begin with EXPERIMENTAL"
        );
        assert_eq!(EXPORTER_CONTEXT, b"");
    }

    #[test]
    fn appendix_a_ath_matches_published_value() {
        use sha2::{Digest as _, Sha256};
        let ath = URL_SAFE_NO_PAD.encode(Sha256::digest(EXAMPLE_TOKEN.as_bytes()));
        assert_eq!(ath, EXAMPLE_ATH);
    }

    #[test]
    fn appendix_a_session_id_and_key_encodings_match() {
        let sid: Vec<u8> = (0u8..0x10).collect();
        assert_eq!(URL_SAFE_NO_PAD.encode(&sid), EXAMPLE_SESSION_ID);
        assert_eq!(
            example_k_none().to_base64url(),
            "EBESExQVFhcYGRobHB0eHyAhIiMkJSYnKCkqKywtLi8"
        );
    }

    #[test]
    fn appendix_a_hkdf_derivation_matches_published_k() {
        // K = HKDF(salt=session_id, IKM=EKM, info="dpop-sk/v1"||0||ath||0||jkt) — published value.
        let k = derive_session_key(&example_ekm(), EXAMPLE_SESSION_ID, EXAMPLE_ATH, EXAMPLE_JKT);
        assert_eq!(
            k.to_base64url(),
            "B2D8_PhuOLMzvM9-ND2aVCXoz8ADWeTfhqiZV3yUvD4"
        );
    }

    #[test]
    fn appendix_a_confirm_value_matches() {
        let k = derive_session_key(&example_ekm(), EXAMPLE_SESSION_ID, EXAMPLE_ATH, EXAMPLE_JKT);
        assert_eq!(
            confirm_value(&k, EXAMPLE_SESSION_ID),
            "gvocwuudE9yiXXU5jINFTekorDybyEj_tQWPljW8eRA"
        );
    }

    #[test]
    fn appendix_a_hmac_signature_matches() {
        use base64::engine::general_purpose::STANDARD;
        // The exact signature base from the spec's Appendix A (LF-joined, no trailing LF).
        let base = format!(
            "\"@method\": GET\n\
             \"@target-uri\": https://pod.example/alice/private/doc\n\
             \"authorization\": DPoP {EXAMPLE_TOKEN}\n\
             \"@signature-params\": (\"@method\" \"@target-uri\" \"authorization\");created=1720000000;keyid=\"{EXAMPLE_SESSION_ID}\";alg=\"hmac-sha256\";nonce=\"1\";tag=\"dpop-sk\""
        );
        let tag = hmac_sign(&example_k_none(), base.as_bytes());
        assert_eq!(
            STANDARD.encode(&tag),
            "hPkuPd32xbb4hUjR/hjbj0Cp445ZfWoOgrcq8+f3I3g="
        );
        assert!(hmac_verify(&example_k_none(), base.as_bytes(), &tag));
    }

    #[test]
    fn wrong_exporter_label_derives_a_different_key() {
        // Simulate a TLS exporter keyed by label (as a real one is): a client that derives from
        // the WRONG label (e.g. the RFC 9266 channel-binding value) obtains different EKM, hence a
        // different K — its confirm check fails and its attestations cannot verify. This is the
        // fail-closed behaviour the dedicated label + confirm member exist for (spec A14/A22).
        use sha2::{Digest as _, Sha256};
        let fake_exporter = |label: &[u8]| -> Ekm {
            let mut h = Sha256::new();
            h.update(b"per-connection-exporter-master-secret");
            h.update(label);
            Ekm::new(h.finalize().into())
        };
        let server_k = derive_session_key(
            &fake_exporter(EXPORTER_LABEL),
            EXAMPLE_SESSION_ID,
            EXAMPLE_ATH,
            EXAMPLE_JKT,
        );
        let wrong_label_k = derive_session_key(
            &fake_exporter(b"EXPORTER-Channel-Binding"),
            EXAMPLE_SESSION_ID,
            EXAMPLE_ATH,
            EXAMPLE_JKT,
        );
        assert_ne!(server_k, wrong_label_k);
        // The client detects the mismatch via `confirm` BEFORE sending any attested request…
        assert_ne!(
            confirm_value(&server_k, EXAMPLE_SESSION_ID),
            confirm_value(&wrong_label_k, EXAMPLE_SESSION_ID)
        );
        // …and an attestation signed under the wrong-label key does not verify.
        let msg = b"any signature base";
        let tag = hmac_sign(&wrong_label_k, msg);
        assert!(!hmac_verify(&server_k, msg, &tag));
    }

    #[test]
    fn derivation_binds_session_ath_and_jkt() {
        // Changing ANY of the HKDF inputs changes K (cross-session / cross-token / cross-key
        // replay of a derived key is impossible by construction).
        let ekm = example_ekm();
        let k = derive_session_key(&ekm, EXAMPLE_SESSION_ID, EXAMPLE_ATH, EXAMPLE_JKT);
        assert_ne!(
            k,
            derive_session_key(&ekm, "b3RoZXItc2Vzc2lvbi1pZA", EXAMPLE_ATH, EXAMPLE_JKT)
        );
        assert_ne!(
            k,
            derive_session_key(&ekm, EXAMPLE_SESSION_ID, EXAMPLE_JKT, EXAMPLE_JKT)
        );
        assert_ne!(
            k,
            derive_session_key(&ekm, EXAMPLE_SESSION_ID, EXAMPLE_ATH, EXAMPLE_ATH)
        );
    }

    #[test]
    fn secrets_debug_is_redacted() {
        // Spec §"Key handling": key material MUST NOT be logged. `Debug` (the accidental-log path)
        // is redacted for both secret types.
        assert_eq!(format!("{:?}", example_k_none()), "SessionKey(<redacted>)");
        assert_eq!(format!("{:?}", example_ekm()), "Ekm(<redacted>)");
    }
}
